### ISSUE TITLE
Building on UE5.1 Ubuntu

### ISSUE THREAD

**Issue by KieranCoppins** [CesiumGS/cesium-unreal#1000]
Hi, I noticed you guys made a very recent PR for building on UE5.1. When launching a project using this plugin on UE5.1 I get a dialogue that says: "The CesiumForUnreal plugin was designed for build 5.0.0. Attempt to load it anyway?". When I click "yes" the project does load with no issues, but I wonder if it's actually building using UE5.1 or still using UE5.0.

I have updated my cesium-unreal submodule to use the latest commit in branch ue51 and ran `git submodule update --init --recursive` and re-ran the cmake commands in command-line. I also ensured to clear out any older builds of Cesium in case they were conflicting.

Here is what the git submodule command returns inside my root directory:
`fc20db5505561a704fb0684c20d627ec5dc01b8c Plugins/cesium-unreal (v1.19.0-ue5-2-gfc20db55)`

And here is what it shows in Plugins/cesium-unreal:
` 3e895b49d05ea07e4c2133156cfa94369e19e409 extern/MikkTSpace (heads/master)`
` 2920bb1b2169315e35fad2c8eccca0550b86bd91 extern/cesium-native (v0.21.0)`
` e32922175afec345aef7ceaaaf6c677dc6c6dc12 extern/tidy-html5 (5.9.14-next)`

I still have my UE5.0.3 installed and I wonder if it may be using that version for build tools but unsure where that maybe configured?

**Comment by KieranCoppins** [comment]
Just to add to this, I do get errors when building on Ubuntu. What I described above is what occurs on Windows. Here is an error log of my issues with Ubuntu (Seems mostly a lot of depreciated things inside Cesium Editor):

`[47/49] Compile Module.CesiumEditor.cpp
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/CesiumEditor/Module.CesiumEditor.cpp:9:
/home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Source/CesiumEditor/Private/CesiumIonTokenTroubleshooting.cpp:297:49: warning: 'GetBrush' is deprecated: FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                     .BorderImage(FEditorStyle::GetBrush("Menu.Background"))
                                                ^
/home/ubuntu/UnrealEngine/Engine/Source/Editor/EditorStyle/Public/EditorStyleSet.h:92:2: note: 'GetBrush' has been explicitly marked deprecated here
        UE_DEPRECATED(5.1, "FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead.")
        ^
/home/ubuntu/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:232:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/CesiumEditor/Module.CesiumEditor.cpp:9:
/home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Source/CesiumEditor/Private/CesiumIonTokenTroubleshooting.cpp:456:47: warning: 'GetBrush' is deprecated: FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
                   .BorderImage(FEditorStyle::GetBrush("Menu.Background"))
                                              ^
/home/ubuntu/UnrealEngine/Engine/Source/Editor/EditorStyle/Public/EditorStyleSet.h:92:2: note: 'GetBrush' has been explicitly marked deprecated here
        UE_DEPRECATED(5.1, "FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead.")
        ^
/home/ubuntu/UnrealEngine/Engine/Source/Runtime/Core/Public/Misc/CoreMiscDefines.h:232:43: note: expanded from macro 'UE_DEPRECATED'
#define UE_DEPRECATED(Version, Message) [[deprecated(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")]]
                                          ^
`

**Comment by kring** [comment]
> "The CesiumForUnreal plugin was designed for build 5.0.0. Attempt to load it anyway?"

This is normal, and in fact proves that it's being loaded by UE 5.1 not 5.0. The message isn't caused by building with the UE5.0 build tools, it's caused by this line in the uplugin file:
https://github.com/CesiumGS/cesium-unreal/blob/9632569d204b40262dbe87aedab2a44b64fe69ad/CesiumForUnreal.uplugin#L13

Change that to `"EngineVersion": "5.1.0",` if it bothers you (our build process will do this automatically once it's set up), but other than the message it is harmless.

> I do get errors when building on Ubuntu

I only see deprecation warnings in the log you shared. Are there errors as well?

**Comment by KieranCoppins** [comment]
Hi @kring,

Thank you for your reply, I will have a look at setting the .uplugin version. It appears the error I was getting is actually from the Unreal source not Cesium:

`/home/ubuntu/UnrealEngine/Engine/Source/Runtime/Renderer/Private/VirtualShadowMaps/VirtualShadowMapArray.h:7:10: fatal error: 'MeshDrawCommands.h' file not found
#include "MeshDrawCommands.h"`

There may have been an issue in my upgrading from source and will investigate this. The error was quite high up in the build log and just thought the depreciation messages were causing the build to fail, my apologies.

**Comment by KieranCoppins** [comment]
Hi @kring,

I've been doing some investigating into the building issues on UE5.1 on Ubuntu. It turns out that include error I mentioned comes from the Cesium Runtime build. Here is the full error message:
```[9/49] Compile Module.CesiumRuntime.1_of_6.cpp
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/CesiumRuntime/Module.CesiumRuntime.1_of_6.cpp:6:
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Inc/CesiumRuntime/UHT/CesiumBoundingVolumeComponent.gen.cpp:8:
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Source/CesiumRuntime/Private/CesiumBoundingVolumeComponent.h:5:
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Source/CesiumRuntime/Private/CesiumViewExtension.h:6:
In file included from ./Runtime/Renderer/Private/ScenePrivate.h:33:
In file included from ./Runtime/Renderer/Private/LightSceneInfo.h:15:
In file included from ./Runtime/Renderer/Private/SceneRendering.h:29:
In file included from ./Runtime/Renderer/Private/SkyAtmosphereRendering.h:15:
/home/ubuntu/UnrealEngine/Engine/Source/Runtime/Renderer/Private/VirtualShadowMaps/VirtualShadowMapArray.h:7:10: fatal error: 'MeshDrawCommands.h' file not found
#include "MeshDrawCommands.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

This is because in Unreal 5.1 they have changed the include paths, [here](https://github.com/EpicGames/UnrealEngine/commit/2f7a6424206c111bd816a9dfe63c6f0607c122d2#diff-2b220da703f567cdf490db53f314ae21b5958b0a019ed133c1acaafb7d0c7706) is the commit where this was changed in Unreal 5.1. I also get this upgrade message that I think addresses this:

```
Building CesiumDemoEditor...
[Upgrade]
[Upgrade] Using backward-compatible include order. The latest version of UE has changed the order of includes, which may require code changes. The current setting is:
[Upgrade]     IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_0
[Upgrade] Suppress this message by setting 'IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_1;' in CesiumDemoEditor.Target.cs.
[Upgrade] Alternatively you can set this to 'EngineIncludeOrderVersion.Latest' to always use the latest include order. This will potentially cause compile errors when integrating new versions of the engine.
[Upgrade]
```
Let me know what you think and I hope this helps!

**Comment by KieranCoppins** [comment]
After some more investigation and to see if my hypothesis was correct (That we don't have the include paths saved) I added this to the `CesiumRuntime.Build.cs`:

```
PrivateIncludePaths.AddRange(
    new string[]
    {
        Path.Combine(GetModuleDirectory("Renderer"), "Private")
    }
);
```

This then no longer gave any include errors however it did throw a new error:

```
[32/36] Compile Module.CesiumRuntime.4_of_6.cpp
In file included from /home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/CesiumRuntime/Module.CesiumRuntime.4_of_6.cpp:18:
/home/ubuntu/AzureAgent/_work/1/s/Plugins/cesium-unreal/Source/CesiumRuntime/Private/Cesium3DTileset.cpp:546:39: error: member access into incomplete type 'ULevelSequencePlayer'
    sequenceActor->GetSequencePlayer()->OnPlay.Add(playMovieSequencerDelegate);
```

I imagine that adding this include path inside the plugin build has messed up the order in how the compiler compiled things? And now the `ULevelSequencePlayer` isn't ready? This also feels like a _hacky_ fix and I'm still unsure if this is an Unreal issue or Cesium issue but hopefully this can shed some light on some more well informed people :)

**Comment by KieranCoppins** [comment]
I haven't had this issue occur since my PR so I'll close this issue now

**Comment by kring** [comment]
We have official support for UE 5.2 on Linux now, including for use in the Editor.

**Comment by KieranCoppins** [comment]
> Hi Kieran, I am about to re-embark on compiling the latest Cesium for Unreal on Linux under Ubuntu . For Cesium 4.xx previously I succeeded in having a semi stable version of the editor and simple output running on Ubuntu.
> 
> I would like to try again. What version would you suggest?

Hi @darius-endpoint, currently we have Cesium for Unreal v1.20.0-ue5 (Commit id: 2baf3b9f416dfdb4b18f8656171bcf0b874f39d0 to be specific) running on UE 5.1 where in our build pipeline we manually update Cesium's .uplugin file to match our engine version (See [here](https://github.com/CesiumGS/cesium-unreal/issues/1005)). This has been very stable for us so far. I should also mention that we have Cesium added into our project as a submodule and during our build pipeline we build Cesium from source including Cesium Native. We chose to do this for easier updating and downloading of our project and dependencies. 

However, as @kring said they do now have official support for UE5.2 on Linux so I would say possibly best to use the latest version of everything. We're only using these older versions as we haven't had the opportunity to update them yet. But we will do some time soon.
