### ISSUE TITLE
Packing Project cannot find files inside /CesiumForUnreal/

### ISSUE THREAD

**Issue by KieranCoppins** [CesiumGS/cesium-unreal#1005]
When packaging a project in UE5.1 I get the following warnings:
```
Packaging (Windows): LogUObjectGlobals: Warning: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: Failed to load '/CesiumForUnreal/DynamicPawn': Can't find file.
PackagingResults: Warning: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: Failed to load '/CesiumForUnreal/DynamicPawn': Can't find file.
UATHelper: Packaging (Windows): LogLinker: Warning: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: VerifyImport: Failed to load package for import object 'Package /CesiumForUnreal/DynamicPawn'
PackagingResults: Warning: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: VerifyImport: Failed to load package for import object 'Package /CesiumForUnreal/DynamicPawn'
```

Note that the plugin does get mounted to `/CesiumForUnreal/` as denoted by this line in the log:
`LogPackageName: Display: FPackageName: Mount point added: '../../../../Users/Kieran/Documents/iventis_unreal/Plugins/cesium-unreal/Content/' mounted to '/CesiumForUnreal/'` and the `DynamicPawn.uasset` does exist within this directory.

However, maybe this log line has something to do with it:
`UATHelper: Packaging (Windows): LogPluginManager: Display: Skipping load of 'CesiumForUnreal'.`

Could this be because the plugin is meant for UE5.0?:
```
UATHelper: Packaging (Windows): LogPluginManager: Warning: Plugin 'CesiumForUnreal' requires engine version '5.0.0' and may not be compatible with the current current engine version '5.1.0-23058290+++UE5+Release-5.1'
PackagingResults: Warning: Plugin 'CesiumForUnreal' requires engine version '5.0.0' and may not be compatible with the current current engine version '5.1.0-23058290+++UE5+Release-5.1'
```

Also note that the asset can be loaded in editor and works without any issues, these errors only occur when packaging the project. Although these are warnings, it does prompt errors when referencing the blueprint inside the level blueprint:
```
PackagingResults: Error: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: [Compiler] Can't connect pins  <Unnamed>  and  New View Target : Object Reference is not compatible with Actor Object Reference. from Source: /Game/Levels/World/Globe.Globe:PersistentLevel.Globe
UATHelper: Packaging (Windows): LogBlueprint: Error: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: [Compiler] Can't connect pins  New View Target  and  <Unnamed> : Actor Object Reference is not compatible with Object Reference. from Source: /Game/Levels/World/Globe.Globe:PersistentLevel.Globe
UATHelper: Packaging (Windows): LogBlueprint: Error: [AssetLog] C:\Users\Kieran\Documents\iventis_unreal\Content\Levels\World\Globe.umap: [Compiler] Can't connect pins  In Pawn  and  <Unnamed> : Pawn Object Reference is not compatible with Object Reference. from Source: /Game/Levels/World/Globe.Globe:PersistentLevel.Globe
```

I have tried reinstalling the engine, clearing all AppData files but the issue still persists. I'm a bit lost as to what could be the cause for this as the issue didn't happen since my previous PR #1001.

**Comment by kring** [comment]
@KieranCoppins I've just published v1.20.0 with UE5.1 support to the release page:
https://github.com/CesiumGS/cesium-unreal/releases/latest

I'm curious to hear if you still have this same problem if you install this as an engine plugin.

It should be available through the Epic Marketplace soon as well.

**Comment by kring** [comment]
Thanks again for your PR, by the way (#1001). It was very helpful!

**Comment by KieranCoppins** [comment]
Hi @kring This has occured on the latest commit on the UE5-main branch (commit 2baf3b9) and building the plugin from source, I will add the binaries from the release to the engine just to check if maybe theres an issue in my building of the plugin.

**Comment by kring** [comment]
There's probably not anything wrong with your build, but the version built by our CI system will say 5.1.0 instead of 5.0.0, which may help. I've also in the past seen packaging problems when the plugin is embedded in a project that go away when it's installed as an engine plugin instead. So hopefully one or both of those will help!

**Comment by KieranCoppins** [comment]
Hi @kring, I have done some testing and figured the issue is that the .uplugin file says the engine version for 5.0.0, changing this to 5.1.0 loads the plugin within the project no problem. Heres how I found this out:

- I began by downloading the plugin from the GitHub release page (It appears it has not updated in the unreal marketplace, just FYI), and placing it inside UE5.1 plugins/marketplace. There issue still persisted
- I then removed the plugin saved inside the project and the error was gone; I got a successful build.
- I then removed the plugin from the engine and rebuilt it from source inside the project directory. Error persisted.
- I then changed the engine version inside the .uplugin to 5.1 and I got a successful package.

My analysis suggests that because the plugin is for a different engine version, it doesn't manage to load the plugin properly.  I'm not sure if there is an issue within the plugin itself (maybe some incorrect `#ifdef`s or maybe they're not firing properly with mismatching unreal engine versions) or if UE5.1 just skips loading Cesium Runtime all together in the packaging of the project (as mentioned before it appears Cesium Editor works just fine since all Cesium plugin assets load and run just fine in editor).

Let me know what you think. Our current build pipeline relies on the project containing the cesium-unreal plugin (stored as a submodule) so it will keep pulling the .uplugin file with the engine version set to 5.0. Currently a short term solution for us would be to create a fork with the engine version changed to 5.1 but I wonder if theres something deeper thats broken with this.

Thanks for you suggestions & support!

**Comment by kring** [comment]
@KieranCoppins what you're saying isn't too surprising. It helps explain why I've often noticed that packaging is unreliable when using the plugin embedded in the project rather than installed as an engine plugin. If you can't use a pre-built plugin for your engine version, I suggest you modify your build process to change the version in the uplugin file at build time.

**Comment by kring** [comment]
I think it's just a quirk of the UE packaging process that it's sensitive to the plugin's declared engine version matching the actual engine version. It doesn't make sense for us to maintain a separate branch for UE5.0 versus UE5.1 just to have a different target engine version, so changing the version at build time when you build from source seems like the right solution to me. So I'm going to close this, thanks for your help with it!
