### ISSUE TITLE
LineTrace returns incorrect results when camera is far enough from Earth 

### ISSUE THREAD

**Issue by hl1282456555** [CesiumGS/cesium-unreal#1018]
![image](https://user-images.githubusercontent.com/15796135/207296685-816dec9a-9d85-4537-a84c-dcd6b3dcf469.png)

![image](https://user-images.githubusercontent.com/15796135/207296806-c0b49137-cb07-4966-876b-fdea8d178aa6.png)

Unreal engine version is 5.1.
Camera location is (X=-668201130.265745,Y=905272.636728,Z=1688661572.820031)

**Comment by IndigoCloud6** [comment]
Maybe you can try multiply 100.0 or more ，not 10.0

**Comment by kring** [comment]
The Blueprint seems to just not be line tracing far enough to hit the Earth. Please open a new issue with more information if you're still having trouble.
