### ISSUE TITLE
Changing water material in UE 5.1 causes ocean to turn white

### ISSUE THREAD

**Issue by GabrielEnriquezXR** [CesiumGS/cesium-unreal#1024]
Hello.

I posted this as well in the Community Forums [here](https://community.cesium.com/t/changing-water-material-in-ue-5-1-causes-ocean-to-turn-white/21894). I’m using UE 5.1 from Epic Launcher and Cesium for Unreal from the Marketplace.

- Unreal Engine Version: 5.1.0-23058290+++UE5+Release-5.1
- Cesium for Unreal version 1.21.0
- Visual Studio Community 2022 (64-bit) version 17.4.3

I’m following the documentation on [how to edit the water material](https://cesium.com/learn/unreal/unreal-edit-materials/#frequently-asked-questions). However, I seem to have encountered a bug. Here are the steps to reproduce the bug:

1. Download the Cesium for Unreal Samples project and Cesium plugin from the Marketplace.
2. Open the **01_CesiumWorld** level.
3. Copy the **MI_CesiumThreeOverlaysAndClippingAndWater** inside the Cesium Plugins folder and move it to the Content folder.
4. Copy the **MLB_CesiumSimpleWater** inside the Plugins folder and move it to the Content folder.
5. Open the new **MI_CesiumThreeOverlaysAndClippingAndWater**. In the Layer Parameters window, under the Water Material Layer Key, change the old **MLB_CesiumSimpleWater** with the new MLB_CesiumSimpleWater we just created. Save the material.
6. Select the **CesiumWorldTerrain** in the Outliner. Go to the Details panel > Cesium > Rendering > Water Material. Assign the new **MI_CesiumThreeOverlaysAndClippingAndWater** here.
7. Click **Refresh Tileset** multiple times. The ocean will turn white. If it doesn’t turn white, try editing the Georeference Origin a couple of times. The ocean will eventually turn white.

I tested this with UE 5.0.3, and this bug does not happen. Hoping to find a fix for UE 5.1.

**Comment by kring** [comment]
I've responded to your forum post here:
https://community.cesium.com/t/changing-water-material-in-ue-5-1-causes-ocean-to-turn-white/21894

I believe this is a bug in UE 5.1 and not something we can fix in Cesium for Unreal.
