### ISSUE TITLE
V1.21.0 UE5  error occurs when loading TMS service

### ISSUE THREAD

**Issue by HereWeG0** [CesiumGS/cesium-unreal#1027]
![image](https://user-images.githubusercontent.com/35327719/212271507-25a2702c-5ec2-4614-970a-99f6acfbb8d1.png

**Comment by kring** [comment]
Can you please provide an English translation, or at least the text (rather than screenshot) so that we can feed it through Google Translate?

**Comment by HereWeG0** [comment]
Thanks @kring for the response and help.
My C++ project  error occurs in debuggame model when loading TMS service .
![image](https://user-images.githubusercontent.com/35327719/212580230-1eeb6eae-6b42-481a-ab30-71444d98b1e7.png)

**Comment by kring** [comment]
That's a very strange problem @HereWeG0. Can you reproduce it in the Cesium for Unreal Samples project when you add an overlay with your TMS server? Can you reproduce it in your project with another TMS server? This one, for example:
https://sandcastle.cesium.com/CesiumUnminified/Assets/Textures/NaturalEarthII/tilemapresource.xml

**Comment by HereWeG0** [comment]
@kring I can't reproduce it  in the Cesium for Unreal Samples project when I add an overlay with my TMS server. And  I can't reproduce it in my  new  project with your TMS server and my TMS server .  Error still occurs in my old project .Is it related to my project settings?

**Comment by kring** [comment]
I'm not sure. One guess is that it's related to other (non-Cesium) extensions that are enabled in your old project. Or perhaps the code in your old project itself. Particular extensions and code that are using tinyxml2. There could be a conflict between the version of tinyxml2 used in your project and the one used in Cesium for Unreal.

**Comment by HereWeG0** [comment]
When I restore my project settings，the error does not occur again.Until now I don 't know what caused it.

**Comment by kring** [comment]
Ok, then I'm going to close this issue. Please reopen if you learn more and it appears to be something that should be fixed in Cesium for Unreal.
