### ISSUE TITLE
UE5.1 Cesium1.21  Windows packaging Error syntax error: 'constant'

### ISSUE THREAD

**Issue by jayraj2610** [CesiumGS/cesium-unreal#1028]
in UE5.1  
With using latest Cesium plugin When trying To package Project For Windows ith Throws error 

Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26): error C2059: syntax error: 'constant'

**Comment by jayraj2610** [comment]
Logs are as Below

UATHelper: Packaging (Windows): Building 26 actions with 6 processes...
UATHelper: Packaging (Windows): [1/26] Copy boost_regex-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [2/26] Copy tbb12.dll
UATHelper: Packaging (Windows): [3/26] Copy tbb.pdb
UATHelper: Packaging (Windows): [4/26] Copy boost_chrono-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [5/26] Resource Default.rc2
UATHelper: Packaging (Windows): [6/26] Copy boost_system-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [7/26] Copy boost_program_options-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [8/26] Copy boost_python39-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [9/26] Copy d3d12SDKLayers.dll
UATHelper: Packaging (Windows): [10/26] Copy boost_atomic-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [11/26] Copy boost_iostreams-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [12/26] Copy D3D12Core.dll
UATHelper: Packaging (Windows): [13/26] Copy OpenImageDenoise.dll
UATHelper: Packaging (Windows): [14/26] Copy boost_thread-vc142-mt-x64-1_70.dll
UATHelper: Packaging (Windows): [15/26] Copy tbb.dll
UATHelper: Packaging (Windows): [16/26] Compile SharedPCH.Engine.NonOptimized.ShadowErrors.InclOrderUnreal5_0.cpp
UATHelper: Packaging (Windows): [17/26] Compile aiden_geo_tutorial.init.gen.cpp
UATHelper: Packaging (Windows): [18/26] Compile aiden_geo_tutorial.cpp
UATHelper: Packaging (Windows): [19/26] Compile FoliageHISM.gen.cpp
UATHelper: Packaging (Windows): [20/26] Compile FoliageHISM.cpp
UATHelper: Packaging (Windows): [21/26] Compile FoliageCaptureActor.gen.cpp
UATHelper: Packaging (Windows): [22/26] Compile FoliageCaptureActor.cpp
UATHelper: Packaging (Windows): [23/26] Compile ProceduralFoliageEllipsoid.gen.cpp
_**UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26): error C2059: syntax error: 'constant'**
**PackagingResults: Error: 'constant'**_
UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26): error C2238: unexpected token(s) preceding ';'
UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(92): error C2589: 'constant': illegal token on right side of '::'
UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(92): error C2062: type 'unknown-type' unexpected
UATHelper: Packaging (Windows): [24/26] Compile ProceduralFoliageEllipsoid.cpp
_**UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26): error C2059: syntax error: 'constant'**
**PackagingResults: Error: 'constant'**_
UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26): error C2238: unexpected token(s) preceding ';'
UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(92): error C2589: 'constant': illegal token on right side of '::'
UATHelper: Packaging (Windows): C:\UnrealEngine\UE_5.1\Engine\Plugins\Marketplace\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(92): error C2062: type 'unknown-type' unexpected
UATHelper: Packaging (Windows): [25/26] Link aiden_geo_tutorial-Win64-DebugGame.exe cancelled
UATHelper: Packaging (Windows): [26/26] WriteMetadata aiden_geo_tutorial-Win64-DebugGame.target cancelled
UATHelper: Packaging (Windows): Took 58.6580616s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\Admin\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+UnrealEngine+UE_5.1\UBT-aiden_geo_tutorial-Win64-DebugGame.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 1m 0s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
_**PackagingResults: Error: Unknown Error**_

**Comment by kring** [comment]
See here:
https://community.cesium.com/t/unable-to-package-ue5-0-3-project-with-cesium-v1-19-0/21162/19

Most likely you're missing the `bEnableExceptions = true;` bit.

If that doesn't help or you have followup questions, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).
