### ISSUE TITLE
1.21：Press the F key to focus on the position of the 3dtiles model.

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#1032]
In UE5.1 version, the ver-1.21 plug-in is used. When loading the remote 3dtiles model, the model is not loaded. Press the F key to focus on the location of the model. The previous version 4.19 can.

**Comment by kring** [comment]
There's not enough information here for us to help you. As I said in your last issue (#1029), please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) with more detail about what you see. Certainly most 3D Tiles models are working in v1.21. We'll need more information to figure out why yours isn't. Presumably when you mention the "previous version 4.19" you mean 1.19?
