### ISSUE TITLE
Float precision missed when init StaticMeshVertexBuffer

### ISSUE THREAD

**Issue by ycn2022** [CesiumGS/cesium-unreal#1035]
need add a line to "CesiumGltfComponent.cpp", about at line 1162; before code "LODResources.VertexBuffers.StaticMeshVertexBuffer.Init"
Otherwise, value will changed when saved in UV.
For example, store 2677.0 in UV, 2676 will be read. This result can be test and verify by code:

	float testdata = 2677.00000f;

	TUniquePtr<FStaticMeshRenderData> RenderData =
		MakeUnique<FStaticMeshRenderData>();
	RenderData->AllocateLODResources(1);

	FStaticMeshLODResources& LODResources = RenderData->LODResources[0];

	TArray<FStaticMeshBuildVertex> StaticMeshBuildVertices;

	StaticMeshBuildVertices.SetNum(1);

	FStaticMeshBuildVertex& vertex = StaticMeshBuildVertices[0];

	vertex.UVs[0] = TMeshVector2(testdata, 0.0f);

	//comment this line, will miss float precision,  need add it to "CesiumGltfComponent.cpp", about at line 1162;
	// before code "LODResources.VertexBuffers.StaticMeshVertexBuffer.Init"
	//**LODResources.VertexBuffers.StaticMeshVertexBuffer.SetUseFullPrecisionUVs(true);**

	LODResources.VertexBuffers.StaticMeshVertexBuffer.Init(
		StaticMeshBuildVertices,
		1,
		false);

	int vtNum = LODResources.GetNumVertices();

	for (size_t i = 0; i < vtNum; i += 10) {

		auto uv = LODResources
			.VertexBuffers.StaticMeshVertexBuffer.GetVertexUV(i, 0);

		float fid = uv.X;

		GEngine->AddOnScreenDebugMessage(
				-1,
				10.0f,
				FColor::Red,
				FString::Printf(TEXT("value changed?? %f != %f"), fid, testdata)
			);
	}

UE Version 5.0.3, Win64.

**Comment by kring** [comment]
Thanks @ycn2022. Care you open a pull request for it? We'd also be interested in seeing examples of the rendering artifacts this fixes, as well as at least a quick look at the memory usage impact.

**Comment by ycn2022** [comment]
I have create a pull request. this is the debug result of test code. 
![image](https://user-images.githubusercontent.com/124049705/216872999-85d0fee0-084e-400d-810e-f705d7043a51.png)
the value is incorret, I believe the value is I set, but it not, it will make error render result when use materail with metadata.

**Comment by kring** [comment]
I don't know what I'm looking at it that screenshot. Can you elaborate?

**Comment by ycn2022** [comment]
To verification the value I store in vertex UV changed, I write a blueprint callable function in a test project
	UFUNCTION(BlueprintCallable, Category = "Studio")
		static void DebugUV();

![image](https://user-images.githubusercontent.com/124049705/216878781-8324ae16-b0da-453e-8072-031a62b18a31.png)
![image](https://user-images.githubusercontent.com/124049705/216878828-76025337-4b6a-4368-99f6-61fa5b8099df.png)

if vertex's FeatureId is 2677, the value 2677 is stored in vertex's UV in cesium. Then the FeatureId value changed to 2676 when got by vertex's UV.

**Comment by kring** [comment]
I believe this was fixed in #1036.
