### ISSUE TITLE
How to package local 3dtiles files?

### ISSUE THREAD

**Issue by xuncanzhe** [CesiumGS/cesium-unreal#1041]
After packing with local 3dtiles data, it cannot be run on other machines. Is it possible to pack 3dtiles data into the final result? Is it to configure cesium for ue or just ue5.

**Comment by kring** [comment]
Cesium for Unreal doesn't have any special support for this, as the more common scenario by far is to load 3D Tiles from a web server (even if it's a local one). But I would imagine any mechanism to install the necessary files on the target machine - such as an installer - would work just fine. I don't know if Unreal itself has anything built-in that might help. You might consider asking that question in the [Unreal forums](https://forums.unrealengine.com/).

In any case, we use GitHub issues exclusively for concrete bug reports and feature requests. Please use the [communtiy forum](https://community.cesium.com/c/cesium-for-unreal/10) for general help requests.
