### ISSUE TITLE
Crash when switching tokens with an active tileset in level

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-unreal#1042]
**Overview**
Switching project tokens with an active tileset in the level crashes UE5

**Reproduction Steps:**
- Create at least two tokens in Cesium Ion with assets:read access
- Start a new UE project
- Log in to Cesium Ion
- Set one of the existing tokens as project default
- Add Cesium World Terrain + Bing Maps imagery to the level
- Tileset should load correctly
- Open Cesium Token UI and switch to a different existing token
- Click use as project default token
- Unreal will crash

**Versions used**
UE 5.1.1
Cesium for Unreal 1.21.0

**Comment by kring** [comment]
Thanks for reporting this @r-veenstra!
@joseph-kaile can I ask you to investigate this one before our March release? It sounds quite serious.

**Comment by joseph-kaile** [comment]
Yes, will get this done.
