### ISSUE TITLE
Attribute accessor.count doesn't match with number of decoded Draco vertices

### ISSUE THREAD

**Issue by peterchen2001** [CesiumGS/cesium-unreal#1051]
Hi experts,

I got the below errors, can anyone help me shed some light on how to fix them?  thanks in advance.

[2023.03.01-01.51.39:255][219]LogCesium: Warning: [2023-03-01 09:51:39.242] [warning] [ErrorList.h:91] Warning when loading http://192.168.124.53:8020/3DTiles/GaoCheng2.3/Tile_-009_-005/Tile_-009_-005.b3dm:
- Attribute accessor.count doesn't match with number of decoded Draco vertices.

**Comment by kring** [comment]
Please post questions like this to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use GitHub for feature requests and bug reports.

That message indicates that Cesium for Unreal has detected an inconsistency in your tileset that probably indicates a problem with the tileset. You might try running the tileset through a 3D Tiles validator for more details, or report the problem to the developers of the tool that generated the tileset.
