### ISSUE TITLE
Another version of Cesium Web Map Service Overlay

### ISSUE THREAD

**Issue by Leedia-exe** [CesiumGS/cesium-unreal#1053]
Hello! I'm new to working with the Cesium plugin for Unreal (and Unreal in general) and am currently trying to create a new version of the existing component, the Cesium Web Map Service Overlay. My goal is to retrieve all the layers of the WMS with a GetCapabilities request in C++ (although I'm still figuring out the specifics).

My issue is that I'm having trouble replicating the existing component in my own project. I've tried creating an ActorComponent and inheriting it from UCesiumRasterOverlay, and then copying the CesiumWebMapServiceRasterOverlay code, but it doesn't seem to be working.

I'm hoping to get some guidance on the steps I can follow to successfully replicate the component. Any help or advice would be greatly appreciated! Thank you in advance.

**Comment by Leedia-exe** [comment]
Just to give more context, when I override CreateOverlay (as it is done in CesiumWebMapServiceRasterOverlay), I get the LNK2001 error like so:

![image](https://user-images.githubusercontent.com/65299367/222160922-0141f441-25d7-4ba4-b047-808e009e9b3b.png)

**Comment by kring** [comment]
Hi @Leedia-exe,
Can you share your .build.cs file? It looks like you're including the cesium-native .lib files, so I'm not quite sure where that `std::_Xlength_error` symbol is coming from and why it's undefined.

More generally, I think it might be wise to see if you can aggregate the existing `CesiumWebMapServiceRasterOverlay` inside your new one, rather than copying its implementation. If you need to make changes to the existing implementation to support this, we would probably be willing to take such a pull request.

**Comment by Leedia-exe** [comment]
Hello @kring, Thank you for you reply! Here's how my build.cs looks like:

![image](https://user-images.githubusercontent.com/65299367/222363748-b20e899e-2f97-4004-8820-ce107fc36eb5.png)

Also, I had initially thought about aggregating CesiumWebMapServiceRasterOverlay, but instead, I wanted to experiment with creating my own RasterOverlay component.

**Comment by kring** [comment]
Take a look here and see if adding any of these options to your .build.cs helps:
https://community.cesium.com/t/unable-to-package-ue5-0-3-project-with-cesium-v1-19-0/21162/19?u=kevin_ring

In particular `bEnableExceptions = true`.

**Comment by Leedia-exe** [comment]
Thank you very much, it worked!
 I'm surprised I didn't come across this issue despite having read through all the Cesium issues.

**Comment by kring** [comment]
Great, I'm going to close this issue. Please follow up on the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) if you have further questions. We generally use github only for bug reports and feature requests.
