### ISSUE TITLE
Add Night Time Lighting Mode

### ISSUE THREAD

**Issue by shehzan10** [CesiumGS/cesium-unreal#106]
Project Anywhere used a completely unlit mode for night time. We should make an effort to add in night time lighting similar to [CesiumJS](https://sandcastle.cesium.com/index.html?src=Clock.html)

![image](https://user-images.githubusercontent.com/2288659/101686807-8e4dae80-3a37-11eb-9b45-0ca73ac2c7e9.png)

**Comment by kring** [comment]
I don't think there's anything actionable here, closing.
