### ISSUE TITLE
how can I transparent this skirt?

### ISSUE THREAD

**Issue by VegetableWithChicken** [CesiumGS/cesium-unreal#1062]
When I make the terrain transparent, a skirt will appear, how can I transparent this skirt?

**Comment by VegetableWithChicken** [comment]
![image](https://user-images.githubusercontent.com/56669924/225818458-a74238a9-93b1-451f-85e1-67d55a44072f.png)

**Comment by kring** [comment]
Answered this here:
https://github.com/CesiumGS/cesium-unreal-samples/issues/40
