### ISSUE TITLE
I want to get the real position of 3DTiles, please help me! !

### ISSUE THREAD

**Issue by FatsWang** [CesiumGS/cesium-unreal#1063]
I am trying to get the position of a 3DTiles model in Unreal Engine. But if I get the ActorLocation directly, the obtained position is 0.0.0, but my model is very far away from the position of 0.0.0, which is not what I want. How can I modify it to get the real model position, thank you very much for helping me

**Comment by kring** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use github issues exclusively for feature requests and bug reports.

Most 3D Tiles models use ECEF coordinates, which means that the origin is that the center of the Earth. Are you trying to find the location of the center of the Earth in Unreal's coordinate system? If so, you can use `TransformEcefToUnreal` (or `InaccurateTransformEcefToUnreal` from Blueprints in UE4) on the CesiumGeoreference, and pass it (0,0,0).

However, if your model does not use ECEF but instead has a local origin, you'll want to give it a _separate_ CesiumGeoreference set to "True Origin" mode. And once you do that, the model's origin coincide with the ActorLocation.
