### ISSUE TITLE
04_MAIN_CesiumSublevels sample ends up with multiple credit systems 

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1069]
Open `04_MAIN_CesiumSublevels` in [cesium-unreal-samples](https://github.com/CesiumGS/cesium-unreal-samples). Start Play-in-Editor mode. Press 3 to fly to Paris. The credits display in the bottom left corner will look funny:

![image](https://user-images.githubusercontent.com/924374/229436433-dcf8e56b-14ec-4fc1-a900-b58352e45aae.png)

And, depending on where you click the Data Attribution link, the credits for Cesium World Terrain and Bing Maps will be missing:

![image](https://user-images.githubusercontent.com/924374/229436555-14d66539-220d-4599-9f61-0509e8e88d3a.png)

This is almost certainly caused by both the persistent level and the sub-level having a credit system:

![image](https://user-images.githubusercontent.com/924374/229436660-019c72f3-49d0-48d3-87bd-498ea1080442.png)

**Comment by csciguy8** [comment]
What is the expected result? Should we show the first or second credits display? Or both?

**Comment by kring** [comment]
We need to show all the credits, both from tilesets in the persistent level and tilesets in the sub-level. Exactly how that should happen is the crux of this issue. I'm not quite sure what is the best way to do it.
