### ISSUE TITLE
Georeference / Globe Anchor / Sub-level improvements

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1072]
The georeferencing system in Cesium for Unreal has served us well, but it is overdue for some improvements:

1. Use cesium-native's new `LocalHorizontalCoordinateSystem` and `GlobeAnchor` classes as the basis for the implementation of CesiumGeoreference and CesiumGlobeAnchor, respectively.
2. Use Actor nesting to indicate the relationship between a CesiumGeoreference and tilesets / globe anchors, rather than the kind of weird automatic discovery system we have now.
3. Make CesiumSubLevel a simple component that turns its sub-objects on and off, rather than using the now deprecated world composition system (see #729, #858, and #941)
4. Make CesiumOriginShift a component that can be attached to any object, rather than the georeference finding the first camera.

These changes will all be familiar from Cesium for Unity, which we implemented based on lots of experience from Unreal, so look at that for inspiration.

These probably represent breaking changes, though. It might justify a v2.0.

**Comment by kring** [comment]
This should enable this as well:
* #1049

**Comment by john-terrell** [comment]
This would be really good to have.   I'm in the situation where I'm scaling the cesium globe down but all of my georeferenced actors don't follow suit.   Is there a workaround for this?

**Comment by kring** [comment]
It would be helpful if Cesium could either use the built-in Unreal Engine georeference, or if the CesiumGeoreference could be sync'd from it. As mentioned here:
https://community.cesium.com/t/unreal-georeference-synch-with-cesium/23960

**Comment by kring** [comment]
I created issues for the parts of this that didn't already have them (and aren't already done) and will now close this issue.

* #1154 
* #1169

**Comment by Cyrilsauret** [comment]
Could i hading cesiumglobanchor to an actor or a mesh et runtime and retreive the longitude, latitude... of the actor or static mesh ?
I had tried to do it in blueprint with how i bealeve it wwould working, but without success
Thank you very much for your help

**Comment by csciguy8** [comment]
Hi @Cyrilsauret , please use our community forum for usage questions like this. 

This is the best place get help from other users, and see previous related posts.

https://community.cesium.com/c/cesium-for-unreal/10
