### ISSUE TITLE
How to get elevation by latitude and longitude

### ISSUE THREAD

**Issue by VegetableWithChicken** [CesiumGS/cesium-unreal#1077]
version: unreal 5.0
platform: windows x64

**Comment by j9liu** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use Github exclusively for confirmed bug reports and feature requests.

You can find posts asking questions similar to yours. For example, [this post](https://community.cesium.com/t/best-practices-for-obtaining-real-world-lat-long-height-and-converting-that-into-ue4-coordinates/14441/2).
