### ISSUE TITLE
Degenerate triangle crashes in debug mode when using character controller and physics

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1084]
Run 03_CesiumDenver in the Cesium for Unreal samples. As soon as you leave the cube that the character initially stands on, Unreal Engine crashes:

```
[2023.05.02-14.49.06:878][500]LogChaos: Warning: Degenerate triangle 2449: (26.909554 1580.875610 -317.959564) (26.919434 1580.875610 -317.987000) (26.900770 1580.875610 -317.987000)
[2023.05.02-14.49.06:881][500]LogOutputDevice: Warning: 

Script Stack (0 frames):

Ensure condition failed: false [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Experimental\Chaos\Private\Chaos\TriangleMeshImplicitObject.cpp] [Line: 1285] 

[2023.05.02-14.49.06:882][500]LogOutputDevice: Error: Ensure condition failed: false [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Experimental\Chaos\Private\Chaos\TriangleMeshImplicitObject.cpp] [Line: 1285] 


[2023.05.02-14.49.06:883][500]LogStats:             FDebug::EnsureFailed -  0.003 s
A breakpoint instruction (__debugbreak() statement or a similar call) was executed in UnrealEditor.exe.

The program '[38628] UnrealEditor.exe' has exited with code 0 (0x0).
```

The line number corresponds to the `ensure` in this part of the engine code:
```
if(Normal.SafeNormalize() < SMALL_NUMBER)
{
   UE_LOG(LogChaos, Warning, TEXT("Degenerate triangle %d: (%f %f %f) (%f %f %f) (%f %f %f)"), FaceIdx, A.X, A.Y, A.Z, B.X, B.Y, B.Z, 
   C.X, C.Y, C.Z);
   ensure(false);
   return FVec3(0, 0, 1);
}
```

Note that in a non-development build, the framerate stalls when you leave the cube, but the program _does_ resume and you are able to run across the tileset. I don't know if this is something we can reliably catch, but I'm noting it for future reference.

**Comment by kring** [comment]
We should modify `BuildChaosTriangleMeshes` (in CesiumGltfComponent.cpp) to filter out degenerate triangles, using the same definition of degeneracy that Chaos itself uses. See the code in `TriangleMeshImplicitObject.cpp` mentioned in the log above.

This risks creating (small) holes in the physics mesh, but I'm not sure we can do anything better.

I'm not entirely sure why the framerate stalls in shipping builds, though. We'll have to see if that still happens after filtering out the degenerate triangles.
