### ISSUE TITLE
CesiumJS-style camera

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#11]
Implement a camera similar to the one in CesiumJS, making it easy to navigate a global scene.

**Comment by xuelongmu** [comment]
I have a basic dynamic camera system working in Unreal, here's a video: https://drive.google.com/file/d/1p9wNMR5QQ4MUAXm2_njX0v3qAW1BQK-Q/view?usp=sharing

I am doing a "infinite" line trace (largest floating point number I think) down in the Z direction of the pawn and using the distance as the new camera speed, with a minimum clamp of 8000 and a large number as the maximum clamp. I suspect that this will break when you move far away from the world origin, as the direction from pawn -> terrain will diverge from Unreal's Z axis AFAIK. I will try finding a function that will return the globe-aware Z vector.

**Comment by xuelongmu** [comment]
I used the `InaccurateTransformRotatorEnuToUe` to create a Down pointing vector (in East North Up ref frame) and convert it to Unreal ref frame. Screenshot below of my code:
![image](https://user-images.githubusercontent.com/10490807/114108162-8c3e1400-98a0-11eb-93ce-c1d2848701de.png)

This seems to work correctly near the Georeference origin, but it breaks down when moving far away from the origin. I recorded [it as a video here](https://drive.google.com/file/d/1SNMReh-JC1Mkg3DXqroVMK7rteXANeBn/view?usp=sharing). The red line is the Enu-converted line trace. For comparison, the blue line is the ordinary Unreal world space Z axis vector. Interestingly, it seems to hold up better than the red line, which by the end of the video is shooting off into space...

@nithinp7 @kring Do you have any ideas for what may be happening here?

**Comment by nithinp7** [comment]
@xuelongmu That may be related to a problem I ran into recently (and probably introduced): https://github.com/CesiumGS/cesium-unreal/issues/265
`TransformRotatorEnuToUe` is implemented using `ComputeEastNorthUpToUnreal`, I remember looking for a while and not being able to find why it wasn't working. 

Also have you tried using the ellipsoid height, what kind of results does that give? That may be simpler than the line-trace, but line-trace probably works more consistently near the ground across the world. It may be worth doing a smaller line-trace and then switching to ellipsoid height once you hit a certain altitude (or just if the line-trace fails for any reason). That way, you wouldn't have to do raycasts over huge distances. 

Another point, I think when the camera starts glitching out that's probably just about the furthest it's possible to go in Unreal. Even an integer origin (in cm) + floating point coordinates aren't enough to get too far from the Earth iirc. We should confirm if that's the case and then maybe consider clamping the player's position before they start approaching that limit.

**Comment by nithinp7** [comment]
The newly added dynamic pawn makes it much easier to maintain a convenient speed both near the ground as well as way up in space. But it is not a Cesium JS style camera exactly (probably the dynamic pawn is more useful in most cases). But we may still want an actual Cesium JS style camera at some point, especially if we create a full custom editor mode, so reopening this.

**Comment by shehzan10** [comment]
@nithinp7 I think this issue is more of a misnomer - probably should have been called "Improved camera system". The CesiumJS camera has both good and bad, and we don't necessarily have to replicate it. We want to take the best intuitive camera setup of CesiumJS + Unreal to create the best experience.

I would suggest that if there are specific camera features we want to borrow from CesiumJS, we should open a dedicated issue for that feature instead of a long-standing issue that will be kept open for a long time.
