### ISSUE TITLE
Crash when creating new scene with CWT + Bing Imagery

### ISSUE THREAD

**Issue by joseph-kaile** [CesiumGS/cesium-unreal#1100]
Steps to reproduce:

1. Create a blank Level.
2. Quick add a CWT + Bing Imagery.
3. Project will crash in CesiumCreditSystem::createCredit

**Comment by j9liu** [comment]
I can reproduce this with UE 5. Apparently the crash is happening because `_credits` is null in `createCredit`. Here's the callstack for reference:

![image](https://github.com/CesiumGS/cesium-unreal/assets/32226860/161fc022-580d-423c-9709-97f336610e24)
