### ISSUE TITLE
Is possible add WMS component and change wms Base URL runtime UE5?

### ISSUE THREAD

**Issue by chase03** [CesiumGS/cesium-unreal#1108]
Hi！ Is possible adding WMS  rasterOverlay component and changing  Base, layers URL runtime（game mode） UE5?

![image](https://github.com/CesiumGS/cesium-unreal/assets/26050994/27f6d296-9e82-4c0f-baab-397e978ea3b9)

**Comment by kring** [comment]
Please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead. We use GitHub issues for confirmed bug reports and feature requests.

But yes, it's possible to change WMS parameters at runtime. You'll need to call the Refresh function on it afterward.
