### ISSUE TITLE
Condition failed (debug) in ACesiumCreditSystem::removeCreditsFromViewports

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unreal#1121]
- In Visual Studio, build a debug version of the Unreal sample (and plugin)
- Press F5 to run
- In Unreal, open 04_MAIN_CesiumSublevels in [cesium-unreal-samples](https://github.com/CesiumGS/cesium-unreal-samples). 
- Start Play-in-Editor mode. 
- Press 4 to fly to Paris.
- Once you land, press 1 to go back to Denver

Almost right away, you'll see an exception thrown in Visual Studio...
(you can continue past it though)

```
Ensure condition failed: !IsGarbageCollecting() [File:D:\build\++UE5\Sync\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp] [Line: 43] 
SObjectWidget for 'ScreenCredits_C /Engine/Transient.UnrealEdEngine_0:GameInstance_0.ScreenCredits_C_2' destroyed while collecting garbage.  This can lead to multiple GCs being required to cleanup the object.  Possible causes might be,
1) ReleaseSlateResources not being implemented for the owner of this pointer.
2) You may just be holding onto some slate pointers on an actor that don't get reset until the actor is Garbage Collected.  You should avoid doing this, and instead reset those references when the actor is Destroyed.
[2023.06.08-17.03.54:392][209]LogOutputDevice: Error: Ensure condition failed: !IsGarbageCollecting() [File:D:\build\++UE5\Sync\Engine\Source\Runtime\UMG\Private\Slate\SObjectWidget.cpp] [Line: 43] 
SObjectWidget for 'ScreenCredits_C /Engine/Transient.UnrealEdEngine_0:GameInstance_0.ScreenCredits_C_2' destroyed while collecting garbage.  This can lead to multiple GCs being required to cleanup the object.  Possible causes might be,
1) ReleaseSlateResources not being implemented for the owner of this pointer.
2) You may just be holding onto some slate pointers on an actor that don't get reset until the actor is Garbage Collected.  You should avoid doing this, and instead reset those references when the actor is Destroyed.

[2023.06.08-17.03.54:392][209]LogStats:             FDebug::EnsureFailed -  0.000 s
UnrealEditor-Win64-DebugGame.exe has triggered a breakpoint.


```

**Comment by kring** [comment]
Thanks @csciguy8. The good (but not great) news here is this isn't an exception but an assertion, and it's essentially asserting to avoid a (basically irrelevant in this case) performance problem. So it won't show up in release builds, and it's only embrassing rather than actually harmful. We should see if there's an easy fix, but there may not be.

**Comment by csciguy8** [comment]
Looked for an easy fix, and haven't found one yet. It's a bit of guess and check, trying different changes with `ACesiumCreditSystem`.

Here's what I've found:
* Seems to be specific with destination 4 (Paris) in 04_MAIN_CesiumSublevels
* This destination is the only one that calls `ACesiumCreditSystem::BeginDestroy` when you fly away from it
* Commenting out `AddToViewport` and `RemoveViewport` in `ACesiumCreditSystem` makes the assertion go away, hinting it's related to these two calls
* Moving the call `this->removeCreditsFromViewports()` from `::BeginDestroy` to `::FinishDestroy` didn't fix it
