### ISSUE TITLE
Create tests for AGlobeAwareDefaultPawn

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unreal#1122]
These tests would be the first iteration and need to test base functionality.

Of particular interest are the FlyToXXXX functions, which are time-based. Ideally, we would be able to run time-based tests, but not wait in real time. (maybe override game time inside the test)

Piggyback on the new testing framework introduced in #1109 

Relates to latest rework in this class in #1120

**Comment by csciguy8** [comment]
Might be some useful testing code in this old draft PR, #548

**Comment by csciguy8** [comment]
@kring , do you think this is good enough to call done from your latest PR? #1149 

(introduction of Source/CesiumRuntime/Private/Tests/GlobeAwareDefaultPawn.spec.cpp)

**Comment by kring** [comment]
I only added one test for the very specific issue I ran into. I think it may be worthwhile to add some more general tests of the functionality.
