### ISSUE TITLE
Unable clone the repo recursively (KTX-Software)

### ISSUE THREAD

**Issue by wulcat** [CesiumGS/cesium-unreal#1125]
Error with LFS while pulling modules: 
```
$git sub module update --unit --recursive
```
```
> other_lib/ios/Debug_iphoneos/libSDL2.a Smudge error: Error downloading (This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.)
```

**Comment by kring** [comment]
I'm not seeing this error with a fresh clone and submodule update. It's possible it's already been fixed on the KTX-Software side. In any case, it's something they would have to fix, not us, so I'm going to close this.
