### ISSUE TITLE
=== Lightmass crashed: ===

### ISSUE THREAD

**Issue by zhanglf1982** [CesiumGS/cesium-unreal#1128]
=== Lightmass crashed: ===
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 691] 
Array index out of bounds: 1452 from an array of size 1452
0x00007ff6be7f2dac UnrealLightmass.exe!Lightmass::FStaticMeshStaticLightingMesh::GetTriangleIndices() []
0x00007ff6be76b05a UnrealLightmass.exe!Lightmass::FEmbreeGeometry::FEmbreeGeometry() []
0x00007ff6be774f55 UnrealLightmass.exe!Lightmass::FEmbreeAggregateMesh::AddMesh() []
0x00007ff6be7c421e UnrealLightmass.exe!Lightmass::FStaticLightingSystem::FStaticLightingSystem() []
0x00007ff6be7798b1 UnrealLightmass.exe!Lightmass::BuildStaticLighting() []
0x00007ff6be79cda1 UnrealLightmass.exe!Lightmass::LightmassMain() []
0x00007ff6be7bcf97 UnrealLightmass.exe!main() []
0x00007ff6be825ebc UnrealLightmass.exe!__scrt_common_main_seh() []
0x00007fffcc6126ad KERNEL32.DLL!UnknownFunction []
0x00007fffcd86aa08 ntdll.dll!UnknownFunction []
*** CRITICAL ERROR! Machine: DESKTOP-SJBE0HN
*** CRITICAL ERROR! Logfile: UnrealLight_DESKTOP-SJBE0HN_70633F284B00122BE7EFE3BD238A06F2.log
*** CRITICAL ERROR! Crash report: 
LightingResults: Error: <None> === Lightmass crashed: ===
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 691] 
Array index out of bounds: 1452 from an array of size 1452
0x00007ff6be7f2dac UnrealLightmass.exe!Lightmass::FStaticMeshStaticLightingMesh::GetTriangleIndices() []
0x00007ff6be76b05a UnrealLightmass.exe!Lightmass::FEmbreeGeometry::FEmbreeGeometry() []
0x00007ff6be774f55 UnrealLightmass.exe!Lightmass::FEmbreeAggregateMesh::AddMesh() []
0x00007ff6be7c421e UnrealLightmass.exe!Lightmass::FStaticLightingSystem::FStaticLightingSystem() []
0x00007ff6be7798b1 UnrealLightmass.exe!Lightmass::BuildStaticLighting() []
0x00007ff6be79cda1 UnrealLightmass.exe!Lightmass::LightmassMain() []
0x00007ff6be7bcf97 UnrealLightmass.exe!main() []
0x00007ff6be825ebc UnrealLightmass.exe!__scrt_common_main_seh() []
0x00007fffcc6126ad KERNEL32.DLL!UnknownFunction []
0x00007fffcd86aa08 ntdll.dll!UnknownFunction []
Job has failed! Job executable didn't exit cleanly. Exit code: 1
LogStaticLightingSystem: Warning: Failed to build lighting!!! Lighting build failed.

**Comment by kring** [comment]
@zhanglf1982 there is nothing obviously Cesium-related in that callstack. What makes you think that it is caused by Cesium?

**Comment by kring** [comment]
Closing due to no response. Please reopen (and include more details) if you're still having trouble.
