### ISSUE TITLE
Unreal 5.2 Build Fail

### ISSUE THREAD

**Issue by AntonMikhet** [CesiumGS/cesium-unreal#1145]
I have some problems with packaging a project for the Linux platform
I am using a version of Cesium for Unreal v1.27.1 downloaded from your github
I am using a cross compilation system from windows to linux and I am getting these errors:

```

PackagingResults: Error: call to implicitly-deleted default constructor of 'std::hash<std::string>'
PackagingResults: Error: static assertion failed due to requirement 'integral_constant<bool, false>::value': the specified hash does not meet the Hash requirements
PackagingResults: Error: type 'const std::hash<std::string>' does not provide a call operator
PackagingResults: Error: no matching function for call to object of type 'std::__hash_table<std::__hash_value_type<std::string, FString>, std::__unordered_map_hasher<std::string, std::__hash_value_type<std::string, FString>, std::hash<std::string>, std::equal_to<std::string>, true>, std::__unordered_map_equal<std::string, std::__hash_value_type<std::string, FString>, std::equal_to<std::string>, std::hash<std::string>, true>, std::allocator<std::__hash_value_type<std::string, FString>>>::hasher' (aka 'std::__unordered_map_hasher<std::string, std::__hash_value_type<std::string, FString>, std::ha
sh<std::string>, std::equal_to<std::string>, true>')
```

**Comment by kring** [comment]
Are you using Cesium for Unreal installed from the Epic Launcher? Or from our [releases page](https://github.com/CesiumGS/cesium-unreal/releases)? Try the latter if you haven't already.

Packaging a game that includes Cesium for Unreal for Linux from a Windows system should work, at least when using our build (not sure about Epic's at the moment). You definitely need to be using Epic's cross-compiling toolchain, though:
https://docs.unrealengine.com/5.2/en-US/linux-development-requirements-for-unreal-engine/

**Comment by AntonMikhet** [comment]
> Are you using Cesium for Unreal installed from the Epic Launcher? Or from our [releases page](https://github.com/CesiumGS/cesium-unreal/releases)? Try the latter if you haven't already.
> 
> Packaging a game that includes Cesium for Unreal for Linux from a Windows system should work, at least when using our build (not sure about Epic's at the moment). You definitely need to be using Epic's cross-compiling toolchain, though: https://docs.unrealengine.com/5.2/en-US/linux-development-requirements-for-unreal-engine/

I wrote in my post above that I was using your latest version of Cesium from your GitHub.
And I also use cross compilation tools from Unreal Engine documentation page
But still I get the following error

**Comment by kring** [comment]
Are you able to package the Cesium for Unreal Samples project? That will help narrow down if it's something specific to your project (perhaps a conflicting plugin). It may also help to see your entire log.

**Comment by kring** [comment]
Closing due to no response. Please reopen (and include more details) if you're still having trouble.
