### ISSUE TITLE
PackagingResults: Error: Unknown Cook Failure

### ISSUE THREAD

**Issue by YYSN6699** [CesiumGS/cesium-unreal#1147]
”PackagingResults: Error: Unknown Cook Failure“
and 
”LoadErrors: Error: Collision Profile settings do not include an entry for the Water Body Collision profile, which is required for water collision to function. Add entry to DefaultEngine.ini?“

This error shows up when I bundle the project, and only when CesiumForUnreal is used
Please forgive me for my poor English
My UE version is 5.1.1
I don't know how to solve these problems, they have been bothering me for a week
!
[微信图片_20230625173219](https://github.com/CesiumGS/cesium-unreal/assets/134681508/8d9969a3-e733-4866-b7bd-628fc4c0e2eb)

**Comment by YYSN6699** [comment]
That's all there is in the scene，I think it's pretty simple already
![微信图片_20230625173458](https://github.com/CesiumGS/cesium-unreal/assets/134681508/8e9c6370-8c3f-4d6f-b805-d8ed06429ddd)

**Comment by jianxiao1754** [comment]
自己手动加上就行了：
`Config/DefaultEngine.ini`下的`[/Script/Engine.CollisionProfile]`
补上
`+Profiles=(Name="WaterBodyCollision",CollisionEnabled=QueryOnly,bCanModify=False,ObjectTypeName="",CustomResponses=((Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)),HelpMessage="Default Water Collision Profile (Created by Water Plugin)")`

**Comment by YYSN6699** [comment]
> 自己手动加上就行了： 下的 补上`Config/DefaultEngine.ini``[/Script/Engine.CollisionProfile]` `+Profiles=(Name="WaterBodyCollision",CollisionEnabled=QueryOnly,bCanModify=False,ObjectTypeName="",CustomResponses=((Channel="WorldDynamic",Response=ECR_Overlap),(Channel="Pawn",Response=ECR_Overlap),(Channel="Visibility",Response=ECR_Ignore),(Channel="Camera",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Overlap),(Channel="Vehicle",Response=ECR_Overlap),(Channel="Destructible",Response=ECR_Overlap)),HelpMessage="Default Water Collision Profile (Created by Water Plugin)")`

请问是要加在哪里？

**Comment by jianxiao1754** [comment]
你项目根目录下的`Config/DefaultEngine.ini`文件的`[/Script/Engine.CollisionProfile]`部分

**Comment by kring** [comment]
@YYSN6699 did the above solve the problem for you? Please close this issue if so.

**Comment by YYSN6699** [comment]
> 以上是否为您解决了问题？如果是这样，请关闭此问题。

NO，Still wrong

**Comment by kring** [comment]
Well, you'll have to give us more than "no" if you want further help. What is it doing? The steps suggested have worked for others, for what it's worth.

**Comment by YYSN6699** [comment]
> 你项目根目录下的文件的部分`Config/DefaultEngine.ini``[/Script/Engine.CollisionProfile]`

谢谢！已经解决了！（づ￣3￣）づ╭❤～
