### ISSUE TITLE
CameraComponent Transform Error

### ISSUE THREAD

**Issue by mrs-angryman** [CesiumGS/cesium-unreal#1167]
I have a set of camera transformations in the ECEF coordinate system, and now when I convert them to the UE coordinate system, I find that the camera always deviates by 180 ° from the correct transformation. I guess it is because the scaling factor in the origin transformation does not take effect on the camera components, resulting in the final orientation being incorrect. How should I solve this problem?

**Comment by j9liu** [comment]
@mrs-angryman Please repost this question on our [community forum](https://community.cesium.com/c/cesium-for-unreal/10) with more information. We reserve Github for confirmed bug reports and feature requests.

In your forum post, it would help if you described how you're converting them to UE coordinates. For example, tell us what functions you're using. If you are using Blueprints, screenshots help as well.
