### ISSUE TITLE
How the dynamic pawn rotates and moves?

### ISSUE THREAD

**Issue by PIPA12344** [CesiumGS/cesium-unreal#1177]
I am trying to write a method that uses a mouse to control dynamic pawn, but the method I wrote will be affected by the original control method, causing the camera to rotate when I use the left mouse button to drag to move position. But I didn't find any relevant methods in the blueprint of dynamic pawn.

**Comment by kring** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use GitHub issues for specific feature requests and confirmed bugs.

I'd suggest simply copying the DynamicPawn and then modifying its Blueprints however you see fit.
