### ISSUE TITLE
 Lightmass crashed when build lighting(ue 5.2)

### ISSUE THREAD

**Issue by hehuasa** [CesiumGS/cesium-unreal#1180]
When I enable the cesium plugin in my project and choose to build lights, I get an error.
 Error log:

`LightingResults: Error: <无> === Lightmass crashed: ===
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 752] 
Array index out of bounds: 4134 from an array of size 4134
0x00007ff65aed9af3 UnrealLightmass.exe!Lightmass::FStaticMeshLOD::GetIndex() []
0x00007ff65aedaf9d UnrealLightmass.exe!Lightmass::FStaticMeshStaticLightingMesh::GetTriangleIndices() []
0x00007ff65ae4b3c9 UnrealLightmass.exe!Lightmass::FEmbreeGeometry::FEmbreeGeometry() []
0x00007ff65ae5516a UnrealLightmass.exe!Lightmass::FEmbreeAggregateMesh::AddMesh() []
0x00007ff65aeaa8f0 UnrealLightmass.exe!Lightmass::FStaticLightingSystem::FStaticLightingSystem() []
0x00007ff65ae5bd71 UnrealLightmass.exe!Lightmass::BuildStaticLighting() []
0x00007ff65ae810eb UnrealLightmass.exe!Lightmass::LightmassMain() []
0x00007ff65aea3410 UnrealLightmass.exe!main() []
0x00007ff65af116cc UnrealLightmass.exe!__scrt_common_main_seh() []
0x00007ffec77026ad KERNEL32.DLL!UnknownFunction []
0x00007ffec944aa68 ntdll.dll!UnknownFunction []
0x00007ff65aed9af3 UnrealLightmass.exe!Lightmass::FStaticMeshLOD::GetIndex() []
0x00007ff65aedaf9d UnrealLightmass.exe!Lightmass::FStaticMeshStaticLightingMesh::GetTriangleIndices() []
0x00007ff65ae4b3c9 UnrealLightmass.exe!Lightmass::FEmbreeGeometry::FEmbreeGeometry() []
0x00007ff65ae5516a UnrealLightmass.exe!Lightmass::FEmbreeAggregateMesh::AddMesh() []
0x00007ff65aeaa8f0 UnrealLightmass.exe!Lightmass::FStaticLightingSystem::FStaticLightingSystem() []
0x00007ff65ae5bd71 UnrealLightmass.exe!Lightmass::BuildStaticLighting() []
0x00007ff65ae810eb UnrealLightmass.exe!Lightmass::LightmassMain() []
0x00007ff65aea3410 UnrealLightmass.exe!main() []
0x00007ff65af116cc UnrealLightmass.exe!__scrt_common_main_seh() []
0x00007ffec77026ad KERNEL32.DLL!UnknownFunction []
0x00007ffec944aa68 ntdll.dll!UnknownFunction []`

Then I downloaded  **Cesium for Unreal Samples** in the Marketplace；
and run it with ue 5.2.1; choose build-- build lighting only.
it also report the same error

**Comment by kring** [comment]
Thanks for reporting this @hehuasa. That has been fixed in v1.29.0 which was released today.
