### ISSUE TITLE
glTF 2.0 asset directly as tile content is not visible

### ISSUE THREAD

**Issue by jianxiao1754** [CesiumGS/cesium-unreal#1195]
In the tileset.json, `a.gltf` is a simple yellow cone of gltf 2.0 asset exported from blender. When double click the Cesium3DTileset Actor, it jumps to the correct location, but the gltf model is not visible. I use the latest version of CesiumForUnreal in UE5.2.1.
[glTFTest.zip](https://github.com/CesiumGS/cesium-unreal/files/12445269/glTFTest.zip)

**Comment by kring** [comment]
The tileset.json looks to me like it has a very wrong bounding volume, so Cesium for Unreal is almost certainly zooming to the wrong place. What makes you think it's the correct place?

My basis for saying the bounding volume is wrong is that the position accessor says the position coordinate values range from -100 to 100. There's no transformation on the glTF's node. Therefore the model's position values will all fall in the -100 to 100 range.

The `boundingVolume` in the tileset.json, though, has a center of position of -1595126.571984,5332950.556331,3105417.135419 and half-axis lengths in each direction of 200. So this bounding box is not anywhere near the actual model and doesn't contain any part of it.

I'm closing this issue as it's a problem with the data, not with Cesium for Unreal.
