### ISSUE TITLE
Support non-glTF, non-b3dm tile payloads

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#12]
Specifically pnts, i3dm, and cmpt. We should track the development of the newer glTF-centric 3D Tiles spec, but we also should support these older tile payload types.

**Comment by Tofull** [comment]
Would love to enable `.pnts` payloads. I tried to see some 3dtiles from Asset Depot (Montreal Point Cloud) and got the following log : 
`[warning] [TileContentFactory.cpp:74] No loader registered for tile with content type 'application/octet-stream' and magic value 'pnts'.`

**Comment by GeoSpark** [comment]
We too would like to see point cloud tiles supported. If it would help bump it up you to-do list, we might be able to offer our help, having done a lot of work with Cesium tiles in Unity. I will need to discuss it with the team first.

**Comment by TechArtistG** [comment]
Is it possible to rename this to something less cryptic and more specific, or split this into multiple items to support Instance and point cloud tiles?
