### ISSUE TITLE
Cleanup usage of engine version #defines

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unreal#1214]
Let's cleanup the preprocessor logic that deals with `ENGINE_MAJOR_VERSION` and `ENGINE_MINOR_VERSION` in the cesium-unreal codebase.

Ex.
```
  if (pMesh) {
#if ENGINE_MAJOR_VERSION >= 5 ||                                               \
    (ENGINE_MAJOR_VERSION == 4 && ENGINE_MINOR_VERSION >= 27)
    pMesh->SetRenderData(nullptr);
#else
    pMesh->RenderData.Reset();
#endif
  }
```

In this example it would be nice to have a single `IS_VERSION_4_27_OR_HIGHER` define. And if we do introduce this, it should be defined in one place only, plugin wide.

The goal is to have code that is easier to read, easier to verify correct, and less error prone.

A few more instances coming in from PR #1207

**Comment by kring** [comment]
Any sections targeting UE versions earlier than 5.0 can be removed completely.
