### ISSUE TITLE
CesiumForUnreal52 artifacts do not include Apple CPU binaries

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unreal#1215]
Is this something we need to fix? 

> ...I confirmed with the lipo tool that our 5.2 build only includes Intel binaries, no Apple ones....it's largely gone unnoticed because the binaries on the Unreal Marketplace are built by Epic, and those do support both CPU architectures. The sizes of the Marketplace binaries are larger, just like our CI-built 5.3 binaries.

_Originally posted by @kring in https://github.com/CesiumGS/cesium-unreal/pull/1207#discussion_r1325130565_

From these comments, this would really only affect macOS users running on M1 or M2 chips, who choose to download Cesium from our release or pre-release artifacts, rather than the Unreal Marketplace.

**Comment by kring** [comment]
It would be nice to fix, but the priority is low. It's nice that 5.3 doesn't have the problem, though.

**Comment by csciguy8** [comment]
Closing this one.

We haven't found that anyone thinks this is a priority. Also, this isn't a problem if you're using the latest Unreal 5.3.
