### ISSUE TITLE
Crash when a selected tile leaves the viewport

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1220]
As reported on the forum [here](https://community.cesium.com/t/fatal-error-when-adding-water-material/26780). [This](url) happens in Unreal Engine 5.1 with Windows 10, Cesium for Unreal Samples 1.30.1.

1. Open `02_CesiumMelbourne` in the Cesium for Unreal Samples.
2. Double-click any visible tile.
3. Look away from the tile, such that it leaves the viewport. This will make Unreal crash.

Here is the callstack:

```
Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h] [Line: 276] Element 'CesiumGltfPrimitiveComponent /Game/CesiumSamples/Maps/02/02_CesiumMelbourne.02_CesiumMelbourne:PersistentLevel.MelbournePhotogrammetry.None.None - ID: 836' is still externally referenced when being destroyed! Ref-count: 3; see above for reference information (if available).

UnrealEditor_Engine!FTypedElementInternalData::CheckNoExternalReferencesOnDestruction() [D:\build\++UE5\Sync\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementData.h:276]
UnrealEditor_Engine!UTypedElementRegistry::TRegisteredElementType<FComponentElementData,1>::ProcessDeferredElementsToRemove() [D:\build\++UE5\Sync\Engine\Source\Runtime\TypedElementFramework\Public\Elements\Framework\TypedElementRegistry.h:498]
UnrealEditor_TypedElementFramework!UTypedElementRegistry::ProcessDeferredElementsToDestroy() [D:\build\++UE5\Sync\Engine\Source\Runtime\TypedElementFramework\Private\Elements\Framework\TypedElementRegistry.cpp:151]
UnrealEditor_TypedElementFramework!UTypedElementRegistry::OnEndFrame() [D:\build\++UE5\Sync\Engine\Source\Runtime\TypedElementFramework\Private\Elements\Framework\TypedElementRegistry.cpp:336]
UnrealEditor_TypedElementFramework!TBaseUObjectMethodDelegateInstance<0,UTypedElementRegistry,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:618]
UnrealEditor!TMulticastDelegate<void __cdecl(void),FDefaultDelegateUserPolicy>::Broadcast() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:975]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5627]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:202]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll
```

@joseph-kaile was able to reproduce the error in both UE 5.1 and UE 5.3 on Mac.

**Comment by j9liu** [comment]
Also happens on UE 5.2, Windows

**Comment by csciguy8** [comment]
Only seems to happen when selecting tiles in the Melbourne Photogrammetry Cesium3DTileset. 
Turn this actor off, and there's no crash.

**Comment by csciguy8** [comment]
Commenting out this line seems to make the crash go away...

This might be something we can do something about... or not.

![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/cec1f0c6-2d42-4226-8730-7642ce88bada)

**Comment by kring** [comment]
I think that will lead to a major major leak in the Editor, because the Editor only rarely runs garbage collection. And even in-game, it will mean old tiles stick around longer and garbage collections take longer.

**Comment by csciguy8** [comment]
My bad, I didn't mean to suggest we should implement this as a fix. 

Was just reporting what I saw while investigating.

**Comment by csciguy8** [comment]
A reference callstack for what Unreal does when you are clicking in the viewport...

(stick a breakpoint in `UUnrealEdEngine::IsComponentSelected`)

![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/732be552-7f0b-44d8-bdd7-7b11002ed03e)

**Comment by csciguy8** [comment]
I have a candidate fix locally. Assigning to me.
