### ISSUE TITLE
Cesium for Unreal v1.31.0(5.3):  file://url request failed

### ISSUE THREAD

**Issue by yuxueliyuxl** [CesiumGS/cesium-unreal#1222]
Local data by format  'file://url ' Error loading :

LogHttp: Warning: 00000 50C26025000: request failed, libcurl error: 0 (No error)

LogHttp: Warning: 00000 50C26021900: request failed, libcurl error: 0 (No error)

LogCesium: Error: [2023 09 21 14:12:18:18.841] [error] [TilesetContentManager. cpp: 739] An unexpected error occurred when loading tile: Connection failed

LogCesium: Error: [2023 09 21 14:12:18:18.841] [error] [RasterOverlayCollection. cpp: 127] Error while creating tile provider: Connection failed

**Comment by kring** [comment]
Unreal Engine's libcurl doesn't support file URLs on any platform other than Windows. This is not something we can fix, only Epic can.

If you're on Windows and it's not working, though, please check you're using `file:///` (three slashes), not `file://` (two slashes). It's also possible Epic removed file URL support on Windows in 5.3, but that doesn't appear to be the case based on a quick look at the UE source code.

In any case, I'm going to close this issue because there's nothing actionable for us here other than what's already covered by #378.

**Comment by yuxueliyuxl** [comment]
The Windows version I am using has been tested to pass v1.31.0(5.2) file://url (file:///) Normal access

**Comment by lolleko** [comment]
Can confirm `file:///` no longer works for me when using UE 5.3, windows and latest cesium-unreal master.

**Comment by lolleko** [comment]
I did some more digging apparently this has nothing todo with curl but rather a change in Unreals HTTP module. Specifically this commit and change: https://github.com/EpicGames/UnrealEngine/commit/8cf99a3ba95a6c79074825c7a7db4a572c5d8a16#diff-5af25202a26d69b795835d92dfec1588eb0c1aec18dcda4b01930c9075556d6dR30

**Comment by kring** [comment]
That's frustrating! The only thing we can do on our side is implement #378. And stick to UE 5.2 if you're depending on this in the meantime.

**Comment by sethtodd76** [comment]
Doesn't seem to be much to do about this but I'm also receiving a LogHttp error in UE5.3. The number 378 linked above doesn't go anywhere. Are you saying that the only workaround to this is to switch to using Cesium in UE5.2?

**Comment by kring** [comment]
@sethtodd76 no, not at all. This is a very old (and closed) issue. At this point, #378 has been implemented, and file URLs should work in all versions of Unreal Engine and on all platforms. If you're having trouble, I suggest posting the details of the problem on the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by sethtodd76** [comment]
@kring Thank you! Turns out I just had to completely delete the old Cesium plugin and install the new one from repo. Have a great day!
