### ISSUE TITLE
Tileset Z axis position in editor resets on every level load

### ISSUE THREAD

**Issue by kubalobo** [CesiumGS/cesium-unreal#1232]
Hi!
I have a new issue after updating the plugin from 1.29.0 to 1.31.0 and Unreal from 5.2.1 to 5.3.1.

After loading the level in the editor, the tileset is loaded in its default position without respecting the editor's location transform (Z-axis only).
It is displayed correctly when playing in the editor, and it also fixes itself after a slight movement of the tileset but once again resets to default after level reloading.

The video below shows the issue.

https://github.com/CesiumGS/cesium-unreal/assets/3520560/2fa9173a-2319-4dba-b8b2-7aa7f3b249da

**Comment by kring** [comment]
I don't know what could cause that, and it's not something we've seen before. Can you please confirm:

1) the problem goes away when you revert back to Cesium for Unreal v1.29.0.
2) the problem goes away when you revert back to Unreal Engine 5.2.

That will help narrow down the problem. Also, if you can provide detailed instructions for reproducing this problem, preferably starting with the Cesium for Unreal Samples project, that will be a huge help.

**Comment by kubalobo** [comment]
It's impossible to revert back with project version but it is reproducible in the sample project.
I checked in different versions:
It is not present in UE 5.2.1, CesiumForUnreal-52-v1.31.0 
but it is in UE 5.3.1, CesiumForUnreal-53-v1.31.0

Steps to reproduce:
1) Create CesiumForUnrealSamples project from the marketplace
2) Add `Plugins` folder and put the content of [CesiumForUnreal-53-v1.31.0.zip](https://github.com/CesiumGS/cesium-unreal/releases/download/v1.31.0/CesiumForUnreal-53-v1.31.0.zip) inside it
3) Open the project with Unreal 5.3, upgrade in place to newer engine version
4) Change CesiumGeoreference Origin to Latitude 41,0 and Longitude -79,0
5) Chagne CesiumSunSky Solar Time to 12
6) Add new blank 3D Tiles Tileset Actor
7) Set Source to `From url` and Url to: `https://sandcastle.cesium.com/SampleData/Cesium3DTiles/Classification/Photogrammetry/tileset.json`
8) Look 360 around to load this tileset and press `F` to zoom in to it - you should see three big bricks
![image](https://github.com/CesiumGS/cesium-unreal/assets/3520560/748f12e8-52a5-467b-bf93-f54085bfaf8c)
9) Move them above the ground by setting Transform>Location>Z in Actor Details to 5000
10) Save the level and reload it by going to File>Recent Levels>01_CesiumWorld
11) Bricks once again will be on the ground instead of being above it

**Comment by kring** [comment]
Thanks @kubalobo. @joseph-kaile would you mind taking a look at this one?

**Comment by joseph-kaile** [comment]
Thanks @kubalobo, I could easily reproduce the issue. I can confirm that this problem has been fixed in the latest version (2.0). During construction, previous Unreal versions called UCesium3DTilesetRoot::MoveComponentImpl. However, 5.3 does not. With the latest changes, the relative transform is set correctly. It looks like it was fixed with the deprecation of GeoTransforms.

**Comment by kubalobo** [comment]
Yes, I also confirm that it's fixed in 2.0.0Preview1
Thank you for your hard work and this great update!
