### ISSUE TITLE
"FlyToLocation" yaw / pitch values result in different views for `UCesiumFlyToComponent`

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1237]
This was most noticeable in the `12_CesiumGoogleMapsTiles` map with the the following cities:

- Sydney (4 key)
- London (6 key)
- Las Vegas (8 key)

First, check out the views with the deprecated "Fly To Location" Blueprints. Then, replace the blueprint with a "Fly To Location" on the DynamicPawn's `CesiumFlyToComponent`, with the same pitch and yaw. The views end up being different from the original view.

This happens even if origin shifting is disabled. It's totally possible that this new behavior is actually correct, but we should verify just in case it isn't.

**Comment by kring** [comment]
I modified the "FlyToSydney" part of the Blueprint to look like this:
<img width="849" alt="image" src="https://github.com/CesiumGS/cesium-unreal/assets/924374/50591926-452c-42ba-b261-5dde566e20fa">

And the view at the end is identical whether I use the deprecated Fly to function (top) or the non-deprecated one (bottom). Anything I might have missed here?

**Comment by kring** [comment]
Closing this because it appears to be fixed!
