### ISSUE TITLE
Improve DynamicPawn movement after `UCesiumFlyToComponent` flight is interrupted

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1238]
In `04_CesiumSublevels`, try interrupting any of the flights when the pawn is far above the Earth. Sometimes you can still move, but sometimes you are stuck there until you try another flight and move closer to the Earth.

I've seen this behavior sometimes even in the old implementation, so I don't think this is related to the 2.0 changes. It's still worth revisiting the DynamicPawn logic so we can prevent the camera from being stuck high above the Earth.

**Comment by csciguy8** [comment]
I saw this doing the following...
- Start the level in PIE
- Press '2' to go to next location
- At the highest part of the animation, push any of the W A S D keys to cancel it

I can move the camera angle, but it doesn't feel like the pawn is actually moving. Looking at the Details panel, I can see its location is moving, just very slowly. Feels like the logic to speed up the dynamic pawn at high altitudes isn't working.

**Comment by j9liu** [comment]
It's probably because the DynamicPawn relies on its distance from the terrain to compute its dynamic speed. Basically, on every update it raycasts to the center of the earth (ECEF origin), and uses this distance as a multiplier with the base speed of the camera.

There is (Blueprint) code that specifically tests for the difference between the previous raycasted height, and the new one. If the difference in heights is really drastic, it's assumed that the underlying 3D Tiles must still be loading. (In other words, LODs are popping in and out, and the necessary tiles haven't been loaded yet). The dynamic speed adjustment isn't applied when the heights are drastically different.

Obviously, this breaks down when we start far away from the earth and try to move. The Blueprint senses that we're really far away from the Earth, so it won't apply that height-based scalar. But now we won't be able move to a point where we can be close again to the Earth. 😬 

One fix might be, if the difference in heights is really large, we can interpolate between them in some manner. That way we can maintain smooth movement even over height changes, but we won't completely stop ourselves from moving.

**Comment by csciguy8** [comment]
This is sounding right based on what I'm seeing.

In the failing case, the blueprint's Speed Line Trace is always return False

![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/0846b868-379d-4d9a-a1a6-c26d4dc084e1)

In working cases, you see it return true every so often.

**Comment by csciguy8** [comment]
Yup, it seems to be the block that check differences in height...
![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/1b86a22f-fca4-42d9-83b4-d90b2849a78f)

**Comment by csciguy8** [comment]
So if I remove the entire "If speed will increase suddenly by too much" block, the look problem looks fixed.

Based on the comments, it's there to handle bogus speed increases when tiles aren't loaded (thus high speeds). But wouldn't the "If height trace returns 0" logic handle this too?

A quick test flying around and moving backwards (S key, presumably flying over unloaded tiles) seems to work just fine. And I see the "If height trace returns 0" logic firing occasionally too.

![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/f519dbf5-c731-4dd7-96ca-6dfcaf5c5fe4)
