### ISSUE TITLE
Cesium 2.0 Preview. Building for Android on UE 5.3 - App doesn’t start

### ISSUE THREAD

**Issue by COcisuts** [CesiumGS/cesium-unreal#1246]
Posted also on forums, but maybe here there is more info avaiable for preview 2.0: https://community.cesium.com/t/cesium-2-0-preview-building-for-android-on-ue-5-3-app-doesn-t-start/27295

Greetings, i’m trying to package the “cesium unreal samples” project with the new 2.0 preview for android.
It hangs after unreal engine logo.
I managed to compile it in the past for 5.1, 5.2 and install on my phone (xiaomi redmin note 10 M2101K7AG, 4gb ram, octacore max 2.20ghz, android 12) but also on past releases it was hanging after a run of 20 seconds, freezing and overheating all the smartphone (only a plain 01_CesiumWorld wasn’t crashing… all the other 11 level were) but at least was loading maps and google 3dtiles too in that 20 seconds.
I was waiting the release of cesium 2.0 for further bothering you with android packaging and here we are…
Any preferred Android SDK or NDK for compiling or other advanced clues to try?

**Comment by kring** [comment]
I've answered this on the forum. We use GitHub for concrete feature requests and confirmed bugs.
