### ISSUE TITLE
Line trace sometimes passes through tileset geometry

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1250]
While testing metadata picking with 3D Tiles 1.1, I found that the San Francisco Ferry Building had some places where line traces would pass through the tileset geometry. See below:

![image](https://github.com/CesiumGS/cesium-unreal/assets/32226860/b08c1979-1c3e-4ca1-b826-45b50763fc0f)

This is just the debug view of line trace, so I don't think it's related to any of the features / metadata changes I'm making. I haven't tried it with other tilesets, so maybe it's just a quirk of this tileset? You can see this pass-through behavior most prominently in the middle window and around the pillar areas. 

![image](https://github.com/CesiumGS/cesium-unreal/assets/32226860/82fe6af4-693f-43af-aece-0ecc1586a222)

[Tileset Google Drive link](https://drive.google.com/file/d/1giI-mBn156BLXHMkbHRqSVuzCgYbxjzy/view?usp=drive_link)

**Comment by r-veenstra** [comment]
I am experiencing a similar issue with a 3D Tiles dataset of a complex architectural model.  Line Trace will cast straight through some, but not all trianges.  The GLB from the tileset directly imported into Unreal works fine, as does an IFC via datasmith.

The left model is the tilesets GLB directly imported, the middle is the 3D Tiles, and the right is the IFC.

https://github.com/CesiumGS/cesium-unreal/assets/123468416/ba2dd8e6-430c-4eca-9374-bfb3dbbe30d0

Note how some Line Traces do not hit against certain triangles on the central model.

Some observations that may or may not be related.

The 3D Tiles mesh has some black normals in World Normal debug mode
![image](https://github.com/CesiumGS/cesium-unreal/assets/123468416/052dbe62-79d5-485b-9617-459ca8042589)

The GLB import has no such issues
![image](https://github.com/CesiumGS/cesium-unreal/assets/123468416/dd7c7189-49ea-4fd6-8ca8-30c92346e402)

The black normals are not lit correctly, as expected

![image](https://github.com/CesiumGS/cesium-unreal/assets/123468416/1de92975-354d-43b4-b90d-a7535b5e1f71)

All triangles appear to be present when show collision is enabled in the viewport, so it doesn't appear to be that triangles are being excluded from the physics generation.

I've attached this very simple tileset for debugging.  Set your lat/lon to 0,0.  You can also directly import the included .glb
 
[Computer_Collision.zip](https://github.com/CesiumGS/cesium-unreal/files/14987042/Computer_Collision.zip)

cc @lilleyse @kring

**Comment by kring** [comment]
A user reported [here](https://community.cesium.com/t/line-trace-passing-through-cesium3dtileset-on-high-lod/27485/9) that disabling our degenerate triangle filtering fixed this problem for them. 🤔
