### ISSUE TITLE
"Type is not initialized properly" errors

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1257]
Unreal has kind of strange rules for initialization of members, and it detects at runtime when we fail to follow these rules. A user reported on the forum that they saw log messages indicating we have some problems here in v2.0:

https://community.cesium.com/t/cesium-2-0-preview-building-for-android-on-ue-5-3-app-doesn-t-start/27295/7

```
LogClass: Error: EnumProperty FCesiumFeatureIdSetDescription::Type is not initialized properly. Module:CesiumRuntime File:Public/CesiumFeaturesMetadataComponent.h
LogClass: Error: BoolProperty FCesiumFeatureIdSetDescription::bHasNullFeatureId is not initialized properly. Module:CesiumRuntime File:Public/CesiumFeaturesMetadataComponent.h
LogAutomationTest: Error: UObject.Class AttemptToFindUninitializedScriptStructMembers will be marked as failing due to errors being logged
LogAutomationTest: Error: LogClass: EnumProperty FCesiumFeatureIdSetDescription::Type is not initialized properly. Module:CesiumRuntime File:Public/CesiumFeaturesMetadataComponent.h
LogAutomationTest: Error: LogClass: BoolProperty FCesiumFeatureIdSetDescription::bHasNullFeatureId is not initialized properly. Module:CesiumRuntime File:Public/CesiumFeaturesMetadataComponent.h
```

Here's a PR where we previously fixed similar problems:
https://github.com/CesiumGS/cesium-unreal/pull/847

**Comment by NielsHygum** [comment]
@kring could you make a new version 2 release with this fix? Would be really useful for us:)

**Comment by NielsHygum** [comment]
> @kring could you make a new version 2 release with this fix? Would be really useful for us:)

See now a new release came out yesterday - nevermind
