### ISSUE TITLE
Ignore `KHR_materials_unlit` causes crash for point clouds

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1268]
`computeFlatNormals` expects a triangle mesh, so it crashes when run on a point cloud. There should be a catch for this so the Editor doesn't crash.

**Comment by csciguy8** [comment]
Is there an easy way to reproduce this?

**Comment by j9liu** [comment]
In Cesium Samples, open 11_CesiumPointClouds and enable the setting on the Melbourne tileset.

**Comment by j9liu** [comment]
The glTF spec states:
>When normals are not specified, client implementations **MUST** calculate flat normals and the provided tangents (if present) **MUST** be ignored.

However, computing flat normals is only possible for the triangular primitive modes. It's not possible to compute them for `POINTS` or for the line primitives.

Based on [the description in this sample model](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/PrimitiveModeNormalsTest#description), it seems like the communally-agreed solution is to render points and lines as unlit. So let's add a check below this line of code here:

https://github.com/CesiumGS/cesium-unreal/blob/1107e6fc747cd4a275fce4664a25b1f3f1285c2d/Source/CesiumRuntime/Private/CesiumGltfComponent.cpp#L1024-L1027

The check would look like so:
```
if (primitive.mode == POINTS && !hasNormals) {
  // It's not possible to compute flat normals for point primitives, so treat them as unlit.
  primitiveInfo.isUnlit = true;
}
```
