### ISSUE TITLE
How to export some tiles to blender ?

### ISSUE THREAD

**Issue by softyoda** [CesiumGS/cesium-unreal#1271]
I've tried the merge tools to export just certains tiles to blender (As I need reference to make the camera path via blender animation tools witch are better in my opinion) 

![image](https://github.com/CesiumGS/cesium-unreal/assets/13988751/93fa9136-5120-4cc2-96f2-80a1f95e3988)
It crash when I try to export all.
i didn't try to uncheck ~+2000 checkboxes as it doesn't have like blender the click-scroll to uncheck multiple checkbox.

It doesn't want to select only the one I wish to export, are there any other ways?
I don't have access to the old actor merging tool as tile isn't recognized as actor.

**Comment by csciguy8** [comment]
Hi @softyoda , please use our forum for questions like this,
https://community.cesium.com/c/cesium-for-unreal/10

The community might have users with similar problems, or even posts that have solved this already.

Thanks

**Comment by softyoda** [comment]
Done : https://community.cesium.com/t/how-to-export-some-tiles-to-blender/27744

**Comment by softyoda** [comment]
It is already somewhat possible to have tiles visible when exporting through the sequencer as a fbx,

it just doesn't have any vertex color nor any structure and all lod tiles are present at the same time making it hard to locate where to place the camera.
