### ISSUE TITLE
Select a building from Google tiles

### ISSUE THREAD

**Issue by lehuan5062** [CesiumGS/cesium-unreal#1305]
It seems that this method does not work with Google tiles: https://cesium.com/learn/unreal/unreal-visualize-metadata
Is there a way I can select a building from Google tiles at runtime?

**Comment by j9liu** [comment]
Hi @lehuan5062,

Please post questions like this to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use Github for confirmed bug reports and feature requests.

The tutorial is written for datasets containing the `EXT_mesh_features` and / or `EXT_structural_metadata` extensions I don't believe Google Photorealistic 3D Tiles either.
