### ISSUE TITLE
Deprecation warnings when building Cesium for Unreal

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-unreal#1314]
I'm seeing a couple deprecation warnings when building Cesium for Unreal

> 1>C:\...\Plugins\cesium-unreal\Source\CesiumEditor\Private\CesiumIonTokenTroubleshooting.cpp(326): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

> 1>C:\...\Plugins\cesium-unreal\Source\CesiumRuntime\Private\CesiumTextureUtility.cpp(362): warning C4996: 'RHICreateTexture2D': FRHITexture2D is deprecated, please use RHICreateTexture(const FRHITextureCreateDesc&). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

**Comment by TeraDanielR** [comment]
Which version of Unreal is this for?

**Comment by lilleyse** [comment]
Unreal Engine 5.2
