### ISSUE TITLE
Sometimes the operation crashes.

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#1334]
Sometimes the operation crashes.
Just check it and add a sentence here.

![image](https://github.com/CesiumGS/cesium-unreal/assets/37468607/ab462e66-a02c-4059-b9fe-a82afaa4d9f5)

**Comment by j9liu** [comment]
Hi @kak0na,

Thanks for the report. We'd like to know where you are seeing this issue. Can you give us step-by-step instructions to reproduce the crash?

**Comment by kak0na** [comment]
I'm sorry, this happens occasionally.
PIE crashes when running, reporting an error here.
UE5.1
Cesium 1.24.0

**Comment by j9liu** [comment]
@kak0na v1.24.0 is a fairly old version of the plugin. Could you upgrade to the newest version and check if you see the same crash?

**Comment by csciguy8** [comment]
Closing this bug. 

Reported on an old version of the plugin, and not much follow up from the original reporter.

We can reopen if needed.
