### ISSUE TITLE
Can this plugin add a flat satellite base map?

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#1378]
Can this plugin add a flat satellite base map?
The current loading method is to load in the form of Earth. Can it be modified to a flat form?

like this
![image](https://github.com/CesiumGS/cesium-unreal/assets/37468607/fae4acaa-25f7-4178-9445-7ad668f73a70)

**Comment by csciguy8** [comment]
Hi @kak0na , feel free to ask questions like this is our forum.
https://community.cesium.com/c/cesium-for-unreal/10

(maybe it has already been answered?)
