### ISSUE TITLE
Quest 2/Android build: Unable to parse EXT_structural_metadata extension (or  perhaps any extension?)

### ISSUE THREAD

**Issue by mikeucfl** [CesiumGS/cesium-unreal#1380]
I have a 3D Tiles dataset that utilizes EXT_structural_metadata in the gLTF models, however when processing the models I see 

[error] [TilesetContentManager.cpp:997] An unexpected error occurs when loading tile: bad any cast

I built cesium-native in debug to see what was going on and noticed this line was failing https://github.com/CesiumGS/cesium-native/blob/5efd7ba94f61f27a7663bb8ef558120e45bbe71f/CesiumGltfReader/generated/src/GeneratedJsonHandlers.cpp#L808. Puzzling to me as nothing looks wrong with that code to me, seems like something is getting corrupted?

This only happens when I build for the Quest 2, but if I run it on Windows (and or use Quest Link to display on the headset) there is no issue processing the models. 

Unfortunately I'm unable to share the model, is there any small sample out there that uses EXT_structural_metadata that I could test with?

**Comment by csciguy8** [comment]
Hi @mikeucfl , we have a unit test for this extension [here](https://github.com/CesiumGS/cesium-native/blob/main/CesiumGltfReader/test/TestExtensionModelExtStructuralMetadata.cpp).

From what you described, it sounds like the gltf is being corrupted, but only when running on your Quest 2, which is odd.

I'm currently trying to modify that unit test to produce the same `bad any cast`. Ideally exceptions like that should be caught in the `CesiumGltfReader` and returned as in error in the `GltfReaderResult`. 

This wouldn't actually fix your corruption problem though (if that's what it is).

**Comment by kring** [comment]
Just a guess: does `std::any` require a compiler feature (such as RTTI) that is not available or disabled on the Quest 2? If that were the case, I would expect loading any tile with `EXT_structural_metadata` would fail on that device. So: does the Cesium for Unreal Samples project, particularly [level 6](https://github.com/CesiumGS/cesium-unreal-samples?tab=readme-ov-file#six-level-6---features-and-metadata) work for you on the Quest 2?

**Comment by kring** [comment]
@mikeucfl can you please check that you have the latest version of the Samples? That sounds like an outdated version. You can find the latest here:
https://github.com/CesiumGS/cesium-unreal-samples/releases

**Comment by mikedig** [comment]
@kring Oh oops. I was using the one from the marketplace (https://www.unrealengine.com/marketplace/en-US/product/cesium-samples), didn't realize it was on github as well. I will run this tomorrow and see the results.

On another hand, I was able to take a simple cube glb and add some simple EXT_structural_metadata and EXT_mesh_features inputs. I've attached a zip containing the original cube and tileset.json (in the no-crash) folder, and the attributed cube and tileset.json (in the crash folder). Interestingly enough, I'm not getting the bad cast like I was the past few days, but its actually just out right crashing.
[cube.zip](https://github.com/CesiumGS/cesium-unreal/files/14799461/cube.zip)

**Comment by mikeucfl** [comment]
@kring Oh oops. I was using the one from the marketplace (https://www.unrealengine.com/marketplace/en-US/product/cesium-samples), didn't realize it was on github as well. I ran it just now on level 6 and got spammed with the bad any cast error: [2024.03.29-04.17.14:275][507]LogCesium: Error: [2024-03-29 00:17:14.275] [error] [TilesetContentManager.cpp:997] An unexpected error occurs when loading tile: bad any cast

I also was able to take a simple cube glb and add some simple EXT_structural_metadata and EXT_mesh_features inputs. I've attached a zip containing the original cube and tileset.json (in the no-crash) folder, and the attributed cube and tileset.json (in the crash folder). Interestingly enough, I'm not getting the bad cast, but its actually just out right crashing. Works fine running on Windows, but packaging for the Quest 2 and running it there natively doesn't work.

[cube.zip](https://github.com/CesiumGS/cesium-unreal/files/14799662/cube.zip)

**Comment by kring** [comment]
Also reported here:
https://community.cesium.com/t/cesium-osm-building-load-bug-for-quest-3-build-android/32632

**Comment by GhisBntly** [comment]
Hello folks, I ran into the same error this week with my company tilesets.
Thing is, I'm having it on mac arm64 boxes (not tested old Intel macpro yet, I am in the process of upgrading it to that purpose), with apple-clang from Xcode 14.3 and Xcode 15.
I tested the cube.zip MRE and indeed the bad_any_cast is thrown:
```
LogCesium: Loading tileset from URL file:///Users/developer/Downloads/cube/crash/tileset.json
LogCesium: Loading tileset from URL file:///Users/developer/Downloads/cube/crash/tileset.json done
LogCesium: Error: [2024-06-20 09:21:45.902] [error] [TilesetContentManager.cpp:997] An unexpected error occurs when loading tile: bad any cast
LogCesium: Loading tileset from URL file:///Users/developer/Downloads/cube/no-crash/tileset.json
LogCesium: Loading tileset from URL file:///Users/developer/Downloads/cube/no-crash/tileset.json done
```

I did not suspect RTTI as I believe it is enabled by default in clang and did not find -fno-rtti in the build commands.
I did find this thread though: https://stackoverflow.com/questions/51693605/clang-compiled-program-throws-stdbad-any-cast-during-stdany-cast, which hints at visibility and/or static archive symbol duplication issues, but with the "bad cast" occurring in the same compile unit, indeed two lines after the std::any is created, I am quite confused as to how this could apply... I will try a dylib build nonetheless.
Maybe some kind of compiler bug, especially as building Debug libraries removes the issue :-/

**Comment by kring** [comment]
@GhisBntly is that when running in the Editor, or in a packaged game?

**Comment by GhisBntly** [comment]
@kring: in the Editor, it cannot be packaged for the moment.

No luck so far with visibilty changes (I removed the part about macOS symbols visibility -fms-compat etc. in cesium-unreal/extern/CMakeLists.txt)
Same with dylibs, although I have one dylib per former static lib, so there may still be duplications: I see std::__1::__any_imp::__unique_typeinfo<CesiumGltf::ExtensionExtMeshFeatures>::__id in several dylibs, maybe this is the culprit?

But I find a bit strange to not see RTTI symbols for CesiumGltf::ExtensionExtMeshFeatures itself, they _are_ present for example for other types:
```
00000000003dbe00 S typeinfo for CesiumGltfReader::ExtensionExtMeshFeaturesJsonHandler
00000000003232d0 S typeinfo name for CesiumGltfReader::ExtensionExtMeshFeaturesJsonHandler
```
Or maybe I'm misleaded...

**Comment by GhisBntly** [comment]
For the record, no problem on the mac Intel (latest macOS supporting the hardware = Monterey 12.7.5, Xcode 14.2, UE 5.2).
So it looks like it's arm64-specific (or Xcode 14.3+ _ie_ llvm-15+ only, or UE5.3+ only......)

**Comment by kring** [comment]
I can reproduce this on Linux by simply opening the `06_CesiumMetadata` example in the Editor. 

> [2024.06.24-09.29.23:780][220]LogCesium: Error: [2024-06-24 19:29:23.780] [error] [TilesetContentManager.cpp:997] An unexpected error occurs when loading tile: bad any cast

It happens in both v2.6.0 and in a build out of the `vcpkg` branch.

**Comment by GhisBntly** [comment]
Thanks, that's interesting, so this not arm-only, I guess the linux was running on an Intel chip, right?
Did you test with both clang and gcc?

**Comment by kring** [comment]
Yep, Linux on x86-64 in my case. I only tested with the compiler that is shipped with Unreal, which is Clang. Using a different compiler would require recompiling the entire engine, I believe.

**Comment by cdmoye** [comment]
FWiW, I see this same issue in the Editor on Ubuntu 24.04 with Unreal 5.4.2 and Cesium 2.6.0 when just creating an empty level and adding the "Cesium World Terrain + Bing Maps Aerial" and "Cesium OSM Buildings" assets from the Quick Add (as described in the Quick Start).

**Comment by kring** [comment]
I unfortunately have to move this one out of the release, because, even if I fix it right now, there isn't time to review and merge it before the release. I'm still going to look into it today and tomorrow though.

**Comment by kring** [comment]
To everyone who has been running into this problem: I believe we have a fix for it. Please try out the build from this pull request and see if it works for you:
https://github.com/CesiumGS/cesium-unreal/pull/1468

Instructions for installing a build from a pull request can be found here:
https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/using-prerelease-packages.md#download-a-pre-release-version-from-a-pull-request

Thanks!

**Comment by CamilleChigot** [comment]
Thanks @kring .
I can confirm that it is working fine now on macos Arm64.

**Comment by frank0911C** [comment]
> [@kring](https://github.com/kring)哦，糟糕。我使用的是来自市场的一个（https://www.unrealengine.com/marketplace/en-US/product/cesium-samples），没想到它也在 github 上。我刚刚在第 6 级运行它，结果收到了错误的任何转换错误：[2024.03.29-04.17.14:275][507]LogCesium：错误：[2024-03-29 00:17:14.275] [错误] [TilesetContentManager.cpp:997] 加载图块时发生意外错误：任何转换都不正确。在 Windows 上再次正常运行，但打包 Quest 2 并在本机运行不起作用。
> 
> 我还能够使用一个简单的立方体 glb 并添加一些简单的 EXT_structural_metadata 和 EXT_mesh_features 输入。我附加了一个 zip 文件，其中包含原始立方体和 tileset.json（在无崩溃文件夹中），以及属性立方体和 tileset.json（在崩溃文件夹中）。有趣的是，我没有得到坏的转换，但它实际上只是直接崩溃了。在 Windows 上运行良好。
> 
> [立方体.zip](https://github.com/CesiumGS/cesium-unreal/files/14799662/cube.zip)
> 
> 编辑：我只是想补充一下，我正在虚幻引擎 5.3.2 上运行此程序，将项目从 5.1 升级。不确定这是否重要，但我想我应该提一下



> [@kring](https://github.com/kring) Oh oops. I was using the one from the marketplace (https://www.unrealengine.com/marketplace/en-US/product/cesium-samples), didn't realize it was on github as well. I ran it just now on level 6 and got spammed with the bad any cast error: [2024.03.29-04.17.14:275][507]LogCesium: Error: [2024-03-29 00:17:14.275] [error] [TilesetContentManager.cpp:997] An unexpected error occurs when loading tile: bad any cast. Again works fine running on Windows, but packaging for the Quest 2 and running natively doesn't work.
> 
> I also was able to take a simple cube glb and add some simple EXT_structural_metadata and EXT_mesh_features inputs. I've attached a zip containing the original cube and tileset.json (in the no-crash) folder, and the attributed cube and tileset.json (in the crash folder). Interestingly enough, I'm not getting the bad cast, but its actually just out right crashing. Works fine running on Windows.
> 
> [cube.zip](https://github.com/CesiumGS/cesium-unreal/files/14799662/cube.zip)
> 
> edit: Just wanted to add I am running this on Unreal Engine 5.3.2, upgrading the project from 5.1. Not sure if that matters or not but figured I'd mention it

I noticed that you created a model with attributes, and now I am trying to create a model with attributes, but I have modified it for many times without success. Could you please send me the code for creating a cube and adding attributes? Thank you very much！
