### ISSUE TITLE
Customize material for change default texture (flashes white blicking)

### ISSUE THREAD

**Issue by Meybiz** [CesiumGS/cesium-unreal#1382]
Hey, everybody. I'm creating an Entity Plane and I'm adding   
ImageMaterialProperty. When I update the position, the white background flashes. How can I access the original texture and change it?

`
cesium.viewer.entities.add({
  name: "Red plane with black outline",
  position: new Cesium.Cartesian3.fromDegrees(-107.0, 40.0, 300000.0),
  plane: {
    plane: new Cesium.Plane(Cesium.Cartesian3.UNIT_Z, 0.0),
    material: new Cesium.ImageMaterialProperty({
      image: './logo512.png',
      transparent: true,
    }),
    dimensions: new Cesium.Cartesian2(60000.0, 61000.0)
  }
});
`

**Comment by csciguy8** [comment]
Hi @Meybiz , this is a great question for the forum. 
https://community.cesium.com/c/cesium-for-unreal/10

Can you ask your question there? (if you search, it may have already been answered)

Thanks!

**Comment by j9liu** [comment]
@Meybiz that looks like a CesiumJS question, so please post in the [CesiumJS](https://community.cesium.com/c/cesiumjs/5) category instead. Thank you!
