### ISSUE TITLE
Was WMTS removed in 2.4.0?

### ISSUE THREAD

**Issue by janarki** [CesiumGS/cesium-unreal#1383]
I'm looking at upgrading the plugin version and exploring the options. I see WMTS was added in 2.3.0, tested and working, but I cannot find the component within the editor (5.3.1) on 2.4.0? Was it disabled?

**Comment by j9liu** [comment]
Hi @janarki,

That's strange! We did not remove WMTS support in 2.4.0, and we don't have a reason to. I'm able to find the component in 5.3 myself: 
![image](https://github.com/CesiumGS/cesium-unreal/assets/32226860/ee754ba4-5d7e-484a-94e1-74ed6f801e8a)

If you're still having issues, do you mind bringing this discussion over to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) for troubleshooting? We usually reserve Github for confirmed bugs and feature requests. Thank you!
