### ISSUE TITLE
Add compile support for Unreal Engine 5.4

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unreal#1393]
The Cesium for Unreal plugin needs to build successfully when using Unreal Engine 5.4.

(UE 5.4 currently available for download)

**Comment by michael-muir** [comment]
I have been attempting to compile a 5.4 version of the plugin and ran into issues with the UE 5.4 Preview 1 release.   Other developers have also run into the same issues as reported below.   The release is missing some of the UE5Rules and UE5ProgrammingRules libraries.

https://forums.unrealengine.com/t/ue-5-4-compile-error-catch2/1770453

My workaround it to download the latest code release for 5.4 from EpicGames/UnrealEngine github repository and building against it.

**Comment by csciguy8** [comment]
I was able to get [cesium-unreal-samples](https://github.com/CesiumGS/cesium-unreal-samples) up and running with UE 5.4 Preview 1 on Windows.

You can build from [this branch](https://github.com/CesiumGS/cesium-unreal/tree/ue_5.4_support) and follow the typical [developer workflow](https://github.com/CesiumGS/cesium-unreal/blob/ue_5.4_support/Documentation/developer-setup-windows.md) to build cesium-native and the cesium-unreal plugin. In addition, I had to update my samples project build settings to at least V4, `DefaultBuildSettings = BuildSettingsVersion.V4`

Not ready for a pull request quite yet, but should get some users by until full support comes along.

![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/00725d13-b09a-4e91-b8c6-f4f42423f4a0)

**Comment by csciguy8** [comment]
Also tested dropping the plugin directly into a fresh project (blueprints or C++). Seems to work just fine.

You can grab some of the built artifacts from [here](https://github.com/CesiumGS/cesium-unreal/actions/runs/8759997671)

**Comment by wuwei416** [comment]
> Also tested dropping the plugin directly into a fresh project (blueprints or C++). Seems to work just fine.
> 
> You can grab some of the built artifacts from [here](https://github.com/CesiumGS/cesium-unreal/actions/runs/8759997671)

Hi csciguy8,
I download artifact of [CesiumForUnreal-53-ue_5.4_support](https://github.com/CesiumGS/cesium-unreal/actions/runs/8759997671/artifacts/1431640791), and put it into [my UE5.4]/Engine/Plugins/Marketplace, and then i got an error, and UE5.4 exits.

**Comment by wuwei416** [comment]
> Also tested dropping the plugin directly into a fresh project (blueprints or C++). Seems to work just fine.
> 
> You can grab some of the built artifacts from [here](https://github.com/CesiumGS/cesium-unreal/actions/runs/8759997671)

Hi csciguy8,
I download artifact of [CesiumForUnreal-53-ue_5.4_support](https://github.com/CesiumGS/cesium-unreal/actions/runs/8759997671/artifacts/1431640791), and put it into [my UE5.4 directory]/Engine/Plugins/Marketplace, and then i run UE5.4 and i got an error, and UE5.4 exits. Can you give some advices on how to run cesium for unreal in UE5.4?
![20240424-133119](https://github.com/CesiumGS/cesium-unreal/assets/167048838/3e9d10d3-b3cb-443f-ad74-f54e19aab328)

**Comment by vacuitydev** [comment]
Hey @wuwei416. Is your project a C++ project? If so, you have to build and run it from the .sln file. If not, you should convert it to C++ (you can do it with unreal 5.3 by just adding a C++ class).
Check here https://forums.unrealengine.com/t/how-can-i-convert-a-blueprint-project-to-c-project-in-ue5/526755
and here https://www.youtube.com/watch?v=8E0ZbBfNF2E

**Comment by wuwei416** [comment]
> Hey @wuwei416. Is your project a C++ project? If so, you have to build and run it from the .sln file. If not, you should convert it to C++ (you can do it with unreal 5.3 by just adding a C++ class). Check here https://forums.unrealengine.com/t/how-can-i-convert-a-blueprint-project-to-c-project-in-ue5/526755 and here https://www.youtube.com/watch?v=8E0ZbBfNF2E

Hi vacuitydev,
Thank you for the reply.
Now,  I was able to get cesium-unreal-samples up and running with UE5.4 on Mac, but when i try to run the game in iOS or MacOS, i get crash, Can you give some advices on that?  Thanks!

**Comment by wuwei416** [comment]
> Hey @wuwei416. Is your project a C++ project? If so, you have to build and run it from the .sln file. If not, you should convert it to C++ (you can do it with unreal 5.3 by just adding a C++ class). Check here https://forums.unrealengine.com/t/how-can-i-convert-a-blueprint-project-to-c-project-in-ue5/526755 and here https://www.youtube.com/watch?v=8E0ZbBfNF2E

Hi vacuitydev,
Thank you for the reply.
Now, I was able to get cesium-unreal-samples up and running with UE5.4 on Mac, but when i try to run the game in iOS or MacOS, i get crash, Can you give some advices on this error? Thanks!
![截屏2024-04-24 16 31 39](https://github.com/CesiumGS/cesium-unreal/assets/167048838/7fc192af-8ebc-476d-ab66-398bccd1871b)

**Comment by wuwei416** [comment]
> Hey @wuwei416. Is your project a C++ project? If so, you have to build and run it from the .sln file. If not, you should convert it to C++ (you can do it with unreal 5.3 by just adding a C++ class). Check here https://forums.unrealengine.com/t/how-can-i-convert-a-blueprint-project-to-c-project-in-ue5/526755 and here https://www.youtube.com/watch?v=8E0ZbBfNF2E

Hi vacuitydev,
the steps are:
1.I put built artifact into UE5.4/Engine/Plugins/Marketplace
2. create a blank UE5.4 project
3. enable cesium for unreal plugin in UE5.4
4. restart UE5.4, then I get this error
![20240424-133119](https://github.com/CesiumGS/cesium-unreal/assets/167048838/96f1118c-552d-4c7f-a3f1-e608a8f0cd8a)
Besides, i am working on MacOS

**Comment by kring** [comment]
@wuwei416 you need to put the plugin in your project's `Plugins` directory in this case, not in the Engine plugins directory. This is required because the plugin must be built for UE 5.4 (since it doesn't already include 5.4 binaries), and UE will not build a plugin in the Engine/Plugins directory.

**Comment by wuwei416** [comment]
> @wuwei416 you need to put the plugin in your project's `Plugins` directory in this case, not in the Engine plugins directory. This is required because the plugin must be built for UE 5.4 (since it doesn't already include 5.4 binaries), and UE will not build a plugin in the Engine/Plugins directory.

Hi Kring,
Thanks for your information.

**Comment by wuwei416** [comment]
> @wuwei416 you need to put the plugin in your project's `Plugins` directory in this case, not in the Engine plugins directory. This is required because the plugin must be built for UE 5.4 (since it doesn't already include 5.4 binaries), and UE will not build a plugin in the Engine/Plugins directory.

Hi Kring,
Thanks for your information.
I am a beginner in UE/cesium development, and I will tell you my operating steps. Can you help me check if they are correct？
1.download https://github.com/CesiumGS/cesium-unreal-samples from https://github.com/CesiumGS/cesium-unreal-samples, create dir Plugins in sample project root dir.
2.download cesium for unreal plugin package:[CesiumForUnreal-53-ue_5.4_support](https://github.com/CesiumGS/cesium-unreal/actions/runs/8853511275/artifacts/1453015897)

**Comment by wuwei416** [comment]
> @wuwei416 you need to put the plugin in your project's `Plugins` directory in this case, not in the Engine plugins directory. This is required because the plugin must be built for UE 5.4 (since it doesn't already include 5.4 binaries), and UE will not build a plugin in the Engine/Plugins directory.

Hi Kring,
Thanks for your information.
I am a beginner in UE/cesium development, and I will tell you my operating steps. Can you help me check if they are correct？
1.download https://github.com/CesiumGS/cesium-unreal-samples from https://github.com/CesiumGS/cesium-unreal-samples, create dir Plugins in sample project root dir.
2.download cesium for unreal plugin package:[CesiumForUnreal-53-ue_5.4_support](https://github.com/CesiumGS/cesium-unreal/actions/runs/8853511275/artifacts/1453015897)
3.unzip CesiumForUnreal-53-ue_5.4_support and copy "CesiumForUnreal" to sample project Plugins directory
4.open CesiumForUnrealSamples.uproject by UnrealEditor5.4

**Comment by csciguy8** [comment]
Hi @wuwei416, can we continue this thread on the forum? Either a new post or [this related one](https://community.cesium.com/t/upgrading-cesium-to-run-in-ue5-4/31274).

(Btw, your steps look good to me. Also, if you're able to wait a bit, we are planning to release official 5.4 support soon)

**Comment by wuwei416** [comment]
> Hi @wuwei416, can we continue this thread on the forum? Either a new post or [this related one](https://community.cesium.com/t/upgrading-cesium-to-run-in-ue5-4/31274).
> 
> (Btw, your steps look good to me. Also, if you're able to wait a bit, we are planning to release official 5.4 support soon)

Hi csciguy8,
This is good to me. 
And can you please tell me the specific schedule， one month later，or two month later：）

**Comment by csciguy8** [comment]
> And can you please tell me the specific schedule， one month later，or two month later：）

@wuwei416 , how about now? :)

Support for UE 5.4 is now official...
https://github.com/CesiumGS/cesium-unreal/releases/tag/v2.5.0

**Comment by wuwei416** [comment]
> > And can you please tell me the specific schedule， one month later，or two month later：）
> 
> @wuwei416 , how about now? :)
> 
> Support for UE 5.4 is now official... https://github.com/CesiumGS/cesium-unreal/releases/tag/v2.5.0

Hi csciguy8，
I am working on Unreal5.3.2 now, i am not sure when we will switch to Unreal5.4, anyway, thank you for the reply.
