### ISSUE TITLE
Collision mesh doesn't get culled at low LODs

### ISSUE THREAD

**Issue by KieranCoppins** [CesiumGS/cesium-unreal#1395]
When using the cartographic polygon to cut out a section of the 3d tiles, at low levels of detail (being zoomed out) the collision mesh is still apparent over the cut out area. However, the visual mesh remains to be cut out. I have tried to depict what is happening in the images below:

Visually Cut out section close up:
![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/90654e81-e1d2-4b59-8df4-0158e318857b)

Visually Cut out section zoomed out:
![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/f779600c-dabd-4994-aabe-a89fc7ecc9ba)

Player collision close up (You can see the grids spilling into the polygon already):
![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/8d0b51fd-385c-4e5e-bdb7-25a7f3eeadaf)

Player collision zoomed out (the entire area is now filled)
![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/f673560a-65f9-420f-94df-fceccc5e82cf)

System Details:
Unreal Engine 5.3.2
Cesium For Unreal 2.3
Using Googles's 3d tiles API to stream google 3d tiles

**Comment by csciguy8** [comment]
Hi @KieranCoppins , thanks for the screenshots.

From what I'm reading, are you expecting the Cartographic polygon to have an effect on the collision mesh?

Cartographic polygons currently only affect the visual aspect of geometry, not any of the physics geometry.

This [tutorial ](https://cesium.com/learn/unreal/unreal-clipping/) mentions it briefly...
![image](https://github.com/CesiumGS/cesium-unreal/assets/130494071/be552af3-7a13-4b89-9202-4a8df7a5806e)

**Comment by KieranCoppins** [comment]
Hi @csciguy8, thanks for your response, sorry I took so long to get back to you!

I see, well it appears that the cartographic polygon does cull out the physics mesh but it doesn't do so accurately at high zoom levels. Is there a plan in the future to make the physics mesh match the graphical mesh we are seeing?

Our use case is using google 3d tiles but replacing some buildings with 3d models by cutting out the 3d tiles and placing a static mesh actor in the level.
