### ISSUE TITLE
Can you add support for shp/kml/geojson [including vertex lines and surfaces]/tif images

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#1424]
Can you add support for shp/kml/geojson [including vertex lines and surfaces]/tif images

**Comment by csciguy8** [comment]
This isn't currently supported, but please follow our support link for discussion and updates...
https://community.cesium.com/t/how-to-use-vector-data-kml-shp/13041/3

**Comment by j9liu** [comment]
This is a duplicate of #628, which you can track instead. You're welcome to +1 or otherwise comment on the issue there.
