### ISSUE TITLE
CI failing for macOS / iOS builds

### ISSUE THREAD

**Issue by csciguy8** [CesiumGS/cesium-unreal#1426]
The last 3 runs failed due to macOS and iOS failures...

https://github.com/CesiumGS/cesium-unreal/actions/runs/9179032103
https://github.com/CesiumGS/cesium-unreal/actions/runs/9158518614
https://github.com/CesiumGS/cesium-unreal/actions/runs/9118270660

Seeing some space related errors, hopefully that's all it is...
`No space left on device : '/Users/runner/runners/2.316.1/_diag/pages/489f42eb-07f5-4d6d-a2c6-58e3fd7262b3_9b070b38-896b-5cd`

Might need a similar space fix as we did on Linux...
https://github.com/CesiumGS/cesium-unreal/blob/3f830c5fadb765a66e85e782dc7d56f52ffc9141/.github/actions/install-unreal-linux/action.yml#L30

**Comment by kring** [comment]
Disk space available on various GitHub macOS runners:

| *Runner* | *Disk Space Free* |
|------------|--------------------|
| macos-12 | 63 GiB |
| macos-13 | 155 GiB |
| macos-14 | 97 GiB |
| macos-latest | 97 GiB |

We're currently running on macos-12, and 63 GiB is really tight for the UE ZIP plus extracting it, and getting under the limit by excluding things from extraction is going to be tedious and error prone (I tried and have failed so far). I think the best move is to switch to the macos-13 or macos-14 runner instead.
