### ISSUE TITLE
Occlusion culling is stuck on waiting for results?

### ISSUE THREAD

**Issue by KieranCoppins** [CesiumGS/cesium-unreal#1429]
Hi there,

I decided to look into occlusion culling to help performance in my application as mentioned in [this blog article](https://cesium.com/blog/2022/08/18/occlusion-culling-cesium-for-unreal/) but I am having some issues with it. Having occlusion culling enabled on my 3d tileset causes no tiles to load. It appears to be stuck waiting for the occlusion results as the latest entry in my output log shows:
```
LogCesium: Display: Cesium3DTileset_0: 156 ms, Visited 2, Culled Visited 0, Rendered 1, Culled 0, Occluded 0, Waiting For Occlusion Results 1, Max Depth Visited: 1, Loading-Worker 0, Loading-Main 0, Loaded tiles 0%
```

I have enabled the `Enable Experimental Occlusion Culling Feature` in the plugin settings inside the project settings and if I disable occlusion culling on the 3D tile, it renders all my tiles (without culling of course).

I have done some investigation into what might be causing this and have looked at some unreal engine visualizations. I have disabled occlusion culling to render the tiles for these screenshots:

![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/a475cf8d-38db-4571-9487-a2d87c2edcb6)
*Bounds appear to be set correctly for the google 3d tiles*

![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/4b0d4d05-e903-4d99-b5a5-8527939ab426)
*I have a platform with some normal actors and have enabled `r.VisualizeOccludedPrimitives 1` in the console to see that normal occlusion culling appears to work*

![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/8b97799a-af09-40d0-9c6b-689bfb59396e)
*Interestingly it appears that the depth buffer has this staggered effect from the camera, I am visualizing this by Buffer Visualisation -> Scene Depth. I would assume that this is not correct and could be the cause of my occlusion culling to not work?*

![image](https://github.com/CesiumGS/cesium-unreal/assets/39103989/95f3b0d6-04eb-4466-87b5-016ba164b470)
*Here is a screenshot of my 3d tile settings incase this might have caused some issues, however a lot of them are defaults.*

Some more information on my versions:
 - CesiumForUnreal v2.3.0 downloaded from the release page and placed in the plugins folder of the project
 - Unreal Engine 5.3.2
 - Google 3D tiles using googles API (tile.googleapis.com)

Thanks for any help with this and let me know if you'd like any more details!

**Comment by kring** [comment]
Thanks for the detailed report @KieranCoppins. I just opened a PR to fix this (linked above).
