### ISSUE TITLE
`CesiumSunSky` will cause crash when no viewport activated in Editor

### ISSUE THREAD

**Issue by yuziqii** [CesiumGS/cesium-unreal#1459]
When I switch the Editor layout between viewport tab and CeiumPanel tab, `CesiumSunSky` causes a crash if no viewport activated in the Editor. BTW, I'm using CesiumForUnreal v2.6.0 and UE 5.4.

![image](https://github.com/CesiumGS/cesium-unreal/assets/49984832/f9182154-a920-42c7-8a36-62763a4df9a2)

`pViewport` will be nullptr if no viewport activated.

![image](https://github.com/CesiumGS/cesium-unreal/assets/49984832/fb279585-6308-4bda-981c-b131dc2d03ca)

**Comment by j9liu** [comment]
Hi @yuziqii,

Thanks for the catch! We should definitely check if `pViewport` is valid before dereferencing it. Would you be able to open a PR with the change?

**Comment by yuziqii** [comment]
Of course! Here is the [PR](https://github.com/CesiumGS/cesium-unreal/pull/1460). Let me know if you need any further adjustments.

**Comment by j9liu** [comment]
Closed by #1460 !
