### ISSUE TITLE
Can't build CesiumGltf.lib when I cmake for cesium-native

### ISSUE THREAD

**Issue by Giannuo** [CesiumGS/cesium-unreal#1470]
when I exec "cmake --build build --config Release --target install" , No 'CesiumGltf.lib' build under 'extern\build\cesium-native\CesiumGltf\Release'
![捕获111](https://github.com/CesiumGS/cesium-unreal/assets/29396369/5fcb50d7-58e7-4836-ae8a-3ee5cd0d5e41)

And No 'cesium-unreal-samples\plugins\cesium-unreal\Source\ThirdParty' was created，that means it build failed ?

because of above， I can't  BuildPlugin with UE 'RunUAT.bat'
![捕获222](https://github.com/CesiumGS/cesium-unreal/assets/29396369/082b3f14-559e-474e-89f1-658c8b621e2d)

what am i supposed to do ?

ENV:
Unreal Engine 5.2.1
cesium-unreal   main branch
cesium-native   main branch
cmake version 3.20.21032501-MSVC_2
visual studio 2019

**Comment by kring** [comment]
Sounds like it must have failed. I'd have to see the entirety of the cmake output to take a guess what might have gone wrong.

**Comment by kring** [comment]
Oh I just noticed you're using VS 2019 and cmake 3.20. I'd recommend upgrading both (to VS2022 and cmake 3.30).

**Comment by Giannuo** [comment]
thanks!
I just change the files to utf-8 bom which were got error above ,such as 'cesium-native\CesiumGltf\ClassProperty.h' and other several files
redo build ,and it works for me

**Comment by Giannuo** [comment]
similar to "https://github.com/CesiumGS/cesium-unreal/issues/997"

**Comment by kring** [comment]
I think that telling MSVC that the files are UTF-8 should work as well:
https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170

MSVC's default seems crazy here:

> By default, Visual Studio detects a byte-order mark to determine if the source file is in an encoded Unicode format, for example, UTF-16 or UTF-8. If no byte-order mark is found, it assumes that the source file is encoded in the current user code page, unless you've specified a code page by using /utf-8 or the /source-charset option.

In any case, I don't think there's any action for cesium-unreal here, so I'm going to close this.
