### ISSUE TITLE
Use  custom non-WGS84 ellipsoids ,The edge of the map is stretched

### ISSUE THREAD

**Issue by asdf1966** [CesiumGS/cesium-unreal#1474]
![Uploading st.png…]()

**Comment by asdf1966** [comment]
<img width="428" alt="st" src="https://github.com/CesiumGS/cesium-unreal/assets/35184651/be84b1f6-4fba-4557-86d5-f847903f9822">

**Comment by azrogers** [comment]
Thanks for the report @asdf1966! It would help a lot if you could provide some more information to help me understand what's going on here:

1. What tileset were you testing with?
2. What raster overlay were you testing with?
3. How do you have the ellipsoid set up in Unreal? What are the radii you used?
4. Is it happening at a specific location on the tileset, or just kind of all over the place?

**Comment by asdf1966** [comment]
I used the TMS raster overlay, set the ellipsoid radius x,y,z=1737400, and happened everywhere; At the same time, I tested in Cesium.js using the same data source and did not experience similar problems.

**Comment by azrogers** [comment]
Which TMS overlay in specific? Sorry to keep asking for clarification, but it'll be hard to track this down without the info needed to reproduce it on my end. Alternatively, if you want to send a [Sandcastle](https://sandcastle.cesium.com/) of your test in CesiumJS using the same data source, that would also give the necessary information.

**Comment by j9liu** [comment]
Hi @asdf1966, is this still a problem for you? Please respond so we can keep this issue open. Otherwise, we'll close it due to inactivity.

**Comment by PF-BAO** [comment]
> <img alt="英石" width="428" src="https://private-user-images.githubusercontent.com/35184651/346460233-be84b1f6-4fba-4557-86d5-f847903f9822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODIzNjUsIm5iZiI6MTczMTQ4MjA2NSwicGF0aCI6Ii8zNTE4NDY1MS8zNDY0NjAyMzMtYmU4NGIxZjYtNGZiYS00NTU3LTg2ZDUtZjg0NzkwM2Y5ODIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMTA4YmYxZWRjMDdlNTRhNjhhZTFlODYwZmRkZDE4ODg1MTM4MGZlMmUyZDU5ZjFjZWIzYjJmZjg1MGZkNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a3_34jcG0fvcntKlLz0IrV3dP-J7pVTu3-1-SPXSupQ">

Have you solved this problem? I also encountered the same lifting problem, is there a solution? Thank you
