### ISSUE TITLE
Unable to Install 

### ISSUE THREAD

**Issue by syaifulnizamyahya** [CesiumGS/cesium-unreal#1475]
In this documentation, 
**https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/developer-setup-windows.md**

during setup in **Visual Studio 2019**,

At this step : 
**Right-click on the root CMakeLists.txt and select "Install".**

I got 4 error messages.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	the following warning is treated as an error	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\CMakeLists.txt	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\cesium-native\extern\stb\stb_image_write.h	776	
Error	C2220	the following warning is treated as an error	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\CMakeLists.txt	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\cesium-native\Cesium3DTilesContent\include\Cesium3DTilesContent\GltfConverterUtility.h	18	
Error	C2220	the following warning is treated as an error	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\CMakeLists.txt	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\cesium-native\Cesium3DTilesContent\include\Cesium3DTilesContent\GltfConverterUtility.h	18	
Error	C2220	the following warning is treated as an error	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\CMakeLists.txt	D:\Dev\cesium-unreal-samples\Plugins\cesium-unreal\extern\cesium-native\extern\stb\stb_image.h	1096	
```

Anyone manage to even setup the dev environments?

**Comment by syaifulnizamyahya** [comment]
Got it working for now. 
Instead of using steps for Visual Studio 2019, I use steps for CMake GUI. Make sure to explicitly choose Visual Studio 2019 as the compiler. 
Able to make progress for now.

**Comment by syaifulnizamyahya** [comment]
Spoke too soon. 

At the step
Select "Generate Visual Studio project files"

The build window closed without any notification. Not sure if it successful or not.
I open CesiumForUnrealSamples.sln using Visual Studio 2019, and noticed that all project failed to load/unloaded.
Right click to reload does not fix it.
![image](https://github.com/CesiumGS/cesium-unreal/assets/10744241/dd11f3e4-3341-443d-ab61-ef4b9709817f)

Any tips?

**Comment by csciguy8** [comment]
When you right click and choose "Generate Visual Studio Project Files", you should see a button that says "Show Log". That might tell you something.

And if you don't see anything there, you can also check in `/Saved/Logs/CesiumForUnrealSamples.log`.

You could also try using Visual Studio Community 2022 instead. That's what I use lately.

**Comment by syaifulnizamyahya** [comment]
[CesiumForUnrealSamples.log](https://github.com/user-attachments/files/16136023/CesiumForUnrealSamples.log)
Attached my logs.
I did try with Visual Studio Community 2022, doesn't work. That's why I tried with Visual Studio 2019.
I have tried with Unreal 5.2, 5.3, 5.4 (Switch engine version when right click *.uproject)

Any ideas?

**Comment by syaifulnizamyahya** [comment]
I get this error when tyring to launch game from CesiumForUnrealSamples.uproject

![image](https://github.com/CesiumGS/cesium-unreal/assets/10744241/e66e216b-d24d-43d4-b67a-6647a841afb2)

**Comment by csciguy8** [comment]
You shouldn't be seeing that dialog if building the plugin yourself.

Are you just opening the .uproject? You should be building / launching the game from `CesiumForUnrealSamples.sln`

Closing this, as it sounds like a set up issue, rather than a repo issue.

We an still discuss though.
