### ISSUE TITLE
How to flatten in Cesium for Unreal

### ISSUE THREAD

**Issue by qwork2010** [CesiumGS/cesium-unreal#1477]
Hello!
I used the Cesium for Unreal plugin in Ureal Engine 5.2 to load a 3D road model (in 3dtiles format) and a tilted photography terrain model (also in 3dtiles format). When the road model and terrain model are combined, some areas of the road 3dtiles may be covered by the terrain 3dtiles, so it is necessary to flatten the terrain 3dtiles with polygons. Note: We can draw  polygons  by hand or provide polygons in GeoJSON format.
/
![A](https://github.com/CesiumGS/cesium-unreal/assets/175273890/e10694d3-2aaf-48e6-bb1c-551dc1355eeb)
A, road model
![B](https://github.com/CesiumGS/cesium-unreal/assets/175273890/475f0d4a-99b3-4dcf-a6bd-d7e006f1bad0)
B ,road model is combined with the terrain model
![C](https://github.com/CesiumGS/cesium-unreal/assets/175273890/34aeef25-cdd6-482e-be29-ff7c4795e30d)
C,after flattening the terrain model with  polygons

如何在Cesium for Unreal中压平
老师，您好！
我在Ureal Engine5.2中使用Cesium for Unreal插件，加载了道路三维模型（3dtiles格式）和倾斜摄影地形模型（3dtiles格式）。道路模型与地形模型组合在一起时，道路3dtiles有的地方会被地形3dtiles盖住，因此需要用多边形对地形3dtiles进行压平。备注：可以手画多个多边形面，也可以提供GeoJSON格式的多边形面。
A道路模型
B道路模型与地形模型组合在一起
C多边形压平地形模型

**Comment by csciguy8** [comment]
Hi @qwork2010, thanks for the detailed write up, but please ask question like this in our community forum. 

Issue in this repository are typically used for defects and feature requests.

https://community.cesium.com/c/cesium-for-unreal/10
