### ISSUE TITLE
Demo crashed once after running in editor was stopped; Demo crashes always after Editor is closed.

### ISSUE THREAD

**Issue by Lildreas** [CesiumGS/cesium-unreal#148]
Hello,

awesome plugin! But I have some crashes, see attached ZIP with the crash logs. 

The first crash “UE4CC-Windows-D6CEB0DC45D6A3769183C8A24A1404BB_0000” happened when I stopped playing the demo in the editor.

The next crashes happened (and continue to happen) when I run the demo in the Editor, the stop running (and it didn’t crash), and then when I close the Editor the crashes happen.

For the later case (when I close the Editor) I get this error message on crash:
Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Engine/Private/Materials/MaterialShared.cpp] [Line: 2586] Cannot queue the Expression Cache when it is about to be deleted

I’m using the standard Unreal Engine 4.26.1 and did not change the CESIUM demo at all, just built it and ran it.

Best
Andreas

[Crashes.zip](https://github.com/CesiumGS/cesium-unreal/files/6022833/Crashes.zip)

**Comment by kring** [comment]
CC #348 in case it's related.
But the original problem reported in this issue has likely already been fixed.
