### ISSUE TITLE
getProjectionEllipsoid crash

### ISSUE THREAD

**Issue by spikhoff** [CesiumGS/cesium-unreal#1490]
libUnrealEditor-CesiumRuntime.so!CesiumGeospatial::getProjectionEllipsoid(std::__1::variant<CesiumGeospatial::GeographicProjection, CesiumGeospatial::WebMercatorProjection> const&)()
libUnrealEditor-CesiumRuntime.so!Cesium3DTilesSelection::RasterOverlayUpsampler::loadTileContent(Cesium3DTilesSelection::TileLoadInput const&)()
libUnrealEditor-CesiumRuntime.so!Cesium3DTilesSelection::TilesetContentManager::loadTileContent(Cesium3DTilesSelection::Tile&, Cesium3DTilesSelection::TilesetOptions const&)()
libUnrealEditor-CesiumRuntime.so!Cesium3DTilesSelection::Tileset::_processWorkerThreadLoadQueue()()
libUnrealEditor-CesiumRuntime.so!Cesium3DTilesSelection::Tileset::updateView(std::__1::vector<Cesium3DTilesSelection::ViewState, std::__1::allocator<Cesium3DTilesSelection::ViewState> > const&, float)()
libUnrealEditor-CesiumRuntime.so!ACesium3DTileset::Tick(float) [/var/home/sander-pikhoff/Documents/Unreal Projects/BlakeSurvives/Plugins/CesiumForUnreal/Source/CesiumRuntime/Private/Cesium3DTileset.cpp:2094]
libUnrealEditor-Engine.so!FActorTickFunction::ExecuteTick(float, ELevelTick, ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Engine/Private/Actor.cpp:238]
libUnrealEditor-Engine.so!FTickFunctionTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Engine/Private/TickTaskManager.cpp:275]
libUnrealEditor-Engine.so!TGraphTask<FTickFunctionTask>::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type, bool) [/mnt/horde/++UE5/Sync/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:1235]
libUnrealEditor-Core.so!FNamedTaskThread::ProcessTasksNamedThread(int, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Core/Private/Async/TaskGraph.cpp:760]
libUnrealEditor-Core.so!FNamedTaskThread::ProcessTasksUntilQuit(int) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Core/Private/Async/TaskGraph.cpp:650]
libUnrealEditor-Core.so!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete(TArray<TRefCountPtr<FGraphEvent>, TSizedInlineAllocator<4u, 32, TSizedDefaultAllocator<32> > > const&, ENamedThreads::Type) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Core/Private/Async/TaskGraph.cpp:2122]
libUnrealEditor-Engine.so!FTickTaskSequencer::ReleaseTickGroup(ETickingGroup, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Engine/Private/TickTaskManager.cpp:555]
libUnrealEditor-Engine.so!FTickTaskManager::RunTickGroup(ETickingGroup, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Engine/Private/TickTaskManager.cpp:1582]
libUnrealEditor-Engine.so!UWorld::Tick(ELevelTick, float) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Engine/Private/LevelTick.cpp:1610]
libUnrealEditor-UnrealEd.so!UEditorEngine::Tick(float, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Editor/UnrealEd/Private/EditorEngine.cpp:1804]
libUnrealEditor-UnrealEd.so!UUnrealEdEngine::Tick(float, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Editor/UnrealEd/Private/UnrealEdEngine.cpp:547]
UnrealEditor!FEngineLoop::Tick() [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:5915]
UnrealEditor!GuardedMain(char16_t const*) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Launch/Private/Launch.cpp:182]
libUnrealEditor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:269]
libc.so.6!UnknownFunction(0x28089)
libc.so.6!__libc_start_main(+0x8a)
UnrealEditor!_start()

**Comment by kring** [comment]
@spikhoff can you please tell us more about what you were doing when this crash happened? If you are able to provide detailed step-by-step instructions to reproduce it, that will greatly increase the chances we are able to fix it.

**Comment by j9liu** [comment]
@spikhoff I'm going to close this due to inactivity. Please feel free to respond with more information, and we can re-open the issue and investigate.
