### ISSUE TITLE
Cannot download release zip

### ISSUE THREAD

**Issue by zuihuifeideyu** [CesiumGS/cesium-unreal#1493]
Hi, I try to download Cesium for unreal-53-v2.6.0.zip，when its 99%,  it will prompt "Cannot download, authorization is required", why? Thank you.

**Comment by ZhengzhongSun** [comment]
Seems the network problem in China, try a new VPN.

**Comment by zuihuifeideyu** [comment]
> Seems the network problem in China, try a new VPN.

yes, its effective, thank you!
