### ISSUE TITLE
Gltf load from URL

### ISSUE THREAD

**Issue by zuihuifeideyu** [CesiumGS/cesium-unreal#1511]
Hi, in the documents of cesium for unreal, I saw that the Cesium for Unreal support load gltf, how to do it? And, if I want to load gltfs at runtime? Thank you!

**Comment by zuihuifeideyu** [comment]
> Hi @zuihuifeideyu,
> 
> What documentation are you viewing? We do not support loading glTFs directly from Cesium for Unreal, so I'm not sure where this was communicated.
> 
> But anyways, Unreal itself has the ability to import glTF models, so you're welcome to drag and drop assets into the project.

https://cesium.com/learn/unreal/unreal-faq/, in the "What file formats can I load with Cesium for Unreal?", 3D tiles payloads.

**Comment by kring** [comment]
glTF is currently supported as payload inside a 3D Tiles tileset, but it is not supported as a standalone model outside of 3D Tiles. Although, as a @j9liu mentioned, Unreal itself can import glTFs at Editor time. It might help to explain a little more about your use-case.

**Comment by j9liu** [comment]
@zuihuifeideyu I'm going to close this issue due to inactivity. Please feel free to add more information if you're still running into trouble.
