### ISSUE TITLE
CesiumGeoreference's "Show Load Radii" drastically reduces frame rate

### ISSUE THREAD

**Issue by tangerren** [CesiumGS/cesium-unreal#1512]
I have lots of SubLevel，when i check the CesiumGeoreference's "Show Load Radii"，the editer‘s FPS will very low，and editor is lagging 。If uncheck it，all going well。

![image](https://github.com/user-attachments/assets/5a791d0e-a6ee-4ce1-87e7-835fda00ff2c)

![image](https://github.com/user-attachments/assets/c18c2b53-0292-4f75-b4e8-d026ed04336a)

**Comment by kring** [comment]
The wireframe spheres are rendered with an Unreal "debug" feature, which is very slow, so this isn't too surpring if you have many sublevels.

Related to #1230
