### ISSUE TITLE
How to obtain the terrain height of the corresponding position based on latitude and longitude

### ISSUE THREAD

**Issue by zuihuifeideyu** [CesiumGS/cesium-unreal#1514]
When I use 3dtile-actors in cesium for Unreal to load terrain datasr, is it possible to obtain the terrain height of the loading terrain datas according to the longitude and latitude? Thank you!

**Comment by kring** [comment]
Please post questions to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). We use GitHub issues for confirmed bug reports and clear feature requests.

Currently, the only way query heights in by using Unreal Line Trace function after the appropriate tiles have been loaded for visualization. We want to make this easier and are actively working on it right now.
