### ISSUE TITLE
Issue displaying a 3D Tiles, tileset with a gltf that have two sided material 

### ISSUE THREAD

**Issue by HouleAdrien** [CesiumGS/cesium-unreal#1532]
Hi! I’m working on a project with Cesium for Unreal (tag 2.7.0), where I’m trying to load a tileset containing a glTF model with double-sided materials.

Since double-sided materials aren’t enabled by default in the glTF layer material (ML_CesiumGltf) within the plugin, I created a custom material. This material takes all output from the "CesiumGlTFFunction" material function, and just have two-sided rendering enabled. I then applied this custom material to my tileset.

However, now I’m seeing an issue where one side appears very dark, and I’m not sure what’s causing it.

If anyone has suggestions on how to resolve this, I’d greatly appreciate the help!

Here’s a screenshot of what it looks like in CesiumJS:
![frontjs](https://github.com/user-attachments/assets/29e17183-7baa-48b6-bfe6-2040fedebbf8)
![backjs](https://github.com/user-attachments/assets/99a7b116-9780-4aec-8455-fb9bbd29f77c)

And here’s how it looks in Unreal:

![front](https://github.com/user-attachments/assets/d2884a7d-7141-4e62-8a50-d756ecf3ad38)
![back](https://github.com/user-attachments/assets/3e882fdf-180b-4bf3-8241-87ee35a4b802)

I’ve also attached one of the tilesets exhibiting this issue: 

[testtileset.zip](https://github.com/user-attachments/files/17523056/testtileset.zip)

Thanks in advance!

**Comment by HouleAdrien** [comment]
Okay I figured a fix, if I make my material  unlit, and use color as emissive it works, but I think there might be an issues on how the shadow of the gltf is computed, cause this is really weird and haven't got this issues with other models.

**Comment by kring** [comment]
@HouleAdrien see this bit in the glTF spec:

> When this value is true, back-face culling is disabled and double sided lighting is enabled. The back-face MUST have its normals reversed before the lighting equation is evaluated.

I think this is most likely what your custom material is missing.

**Comment by HouleAdrien** [comment]
Thanks this is indeed what I was missing in my case, so i'm closing this issue on that :)
