### ISSUE TITLE
Cesium3DTilesetCrash，I don't konw why?

### ISSUE THREAD

**Issue by sd63534790** [CesiumGS/cesium-unreal#1533]
ErrorMessage:Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000001f4ba670660
CallStack: 
LJEPS3DSystem!Cesium3DTilesSelection::Tile::getState()
LJEPS3DSystem!ACesium3DTileset::Tick() [F:\UE5\product\lianjiangdpv52cplus\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:2054]
LJEPS3DSystem!AActor::TickActor()
LJEPS3DSystem!FActorTickFunction::ExecuteTick()
LJEPS3DSystem!FTickFunctionTask::DoTask()
LJEPS3DSystem!TGraphTask&lt;FTickFunctionTask&gt;::ExecuteTask()
LJEPS3DSystem!FNamedTaskThread::ProcessTasksNamedThread()
LJEPS3DSystem!FNamedTaskThread::ProcessTasksUntilQuit()
LJEPS3DSystem!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete()
LJEPS3DSystem!FTickTaskSequencer::ReleaseTickGroup()
LJEPS3DSystem!FTickTaskManager::RunTickGroup()
LJEPS3DSystem!UWorld::RunTickGroup()
LJEPS3DSystem!UWorld::Tick()
LJEPS3DSystem!UGameEngine::Tick()
LJEPS3DSystem!FEngineLoop::Tick()
LJEPS3DSystem!GuardedMain()
LJEPS3DSystem!GuardedMainWrapper()
LJEPS3DSystem!LaunchWindowsStartup()
LJEPS3DSystem!WinMain()
LJEPS3DSystem!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32

**Comment by kring** [comment]
Please tell us more about what you were doing when this happened. It would also be helpful to know what versions of Unreal Engine and Cesium for Unreal you're using.

**Comment by j9liu** [comment]
Hi @sd63534790,

Is this still an issue for you? If so, please get back to us with the information that @kring requested above. Otherwise, we'll have to close this issue due to inactivity. Thank you!
