### ISSUE TITLE
Preview Release: Cesium for Unreal v2.10.0 for Unreal Engine 5.5  Crashs!

### ISSUE THREAD

**Issue by yuxueliyuxl** [CesiumGS/cesium-unreal#1546]
Cesium for Unreal v2.10.0 for Unreal Engine 5.5 crashes with Hardware Ray Tracing

**Comment by MoralesSan** [comment]
Confirming that v2.10.0 for UE5.5 crashes consistently unless Hardware Ray Tracing is off.

**Comment by kring** [comment]
Can you provide more details of the crash? If you have UE debug symbols installed, a full call stack would be very useful.

**Comment by yuxueliyuxl** [comment]
![微信图片_20241116141030](https://github.com/user-attachments/assets/1570aaa7-0aa0-4517-a4e8-66a02bed5b59)
![微信图片_20241116141058](https://github.com/user-attachments/assets/94fe833e-1f0a-4e24-ada1-106762e9907c)
Solution：
![微信图片_20241116141139](https://github.com/user-attachments/assets/92b50668-e455-4b9b-8fae-5ab2f6b227ce)

**Comment by kring** [comment]
Thanks for the info! I fixed this in #1550. If you want to try it out, see here for instructions for how to download and install a build from a pull request:
https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/using-prerelease-packages.md

**Comment by TrueNorthTrent** [comment]
![image](https://github.com/user-attachments/assets/0796a0f0-1853-4acd-90c9-8cf5b253a5b0)
Same bug for me after rebuilding engine with your new build.
