### ISSUE TITLE
SampleHeightMostDetailed crashes when called on a tileset with a raster overlay before its first Tick

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#1549]
Reported here:
https://community.cesium.com/t/sampleheightmostdetailed-causes-crash-when-called-in-beginplay/36439

When a user calls `SampleHeightMostDetailed` on a `Cesium3DTileset` that does not yet have any underlying cesium-native `Tileset`, the system automatically calls `LoadTileset` in order to create it. But it doesn't also do the three "Resolve" operations that a normal Tick would do first:

https://github.com/CesiumGS/cesium-unreal/blob/v2.10.0/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L2124

```
this->ResolveGeoreference();
this->ResolveCameraManager();
this->ResolveCreditSystem();
```

This is fine for a tileset without any raster overlays. Sampling heights doesn't require any of these three systems. However, the raster overlay system assumes the presence of a CreditSystem. So if the tileset happens to have a raster overlay, then we'll crash.

We should:
1. Change `SampleHeightMostDetailed` to call these three Resolves before calling `LoadTileset`.
2. Fix the raster overlay crash when the credit system is missing.

Either of these changes would fix the immediate problem, but it's worth doing both.

For users experiencing this crash, an easy workaround is to manually call those three Resolve methods on the `Cesium3DTileset` before calling `SampleHeightMostDetailed`.

**Comment by j9liu** [comment]
> Fix the raster overlay crash when the credit system is missing.

Just want to check the extent of this fix should be. If the credit system is `nullptr`, should we go ahead and show the raster overlay anyways?

**Comment by kring** [comment]
> If the credit system is nullptr, should we go ahead and show the raster overlay anyways?

Yes. A CreditSystem is meant to be optional within cesium-native. But it should always be supplied in Unreal and Unity (if it weren't for this bug).
