### ISSUE TITLE
If no image is requested, a white image will be given by default

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#1556]
When loading tiles, if the image of layer 0 is lost or the image request is unsuccessful, the entire Earth will be lost. Can this issue be fixed? If no image is requested, a white image will be given by default

**Comment by j9liu** [comment]
Hi @kak0na,

Sorry, but I'm a bit confused about what you're describing. Can you share more information?

- What version of Unreal Engine & Cesium for Unreal are you using?
- Please post a screenshot or video of the behavior that you're seeing.
- Please post step-by-step instructions for how to reproduce that behavior.

Thank you!

**Comment by kak0na** [comment]
I am using version V2.3.0.
I am using the WMTS url, which only has layer data 6-12. It does not have layer 0 data, which results in the default, the viewing angle is far, so there is no earth. I hope that if there is no img, it will also display a white image, is it ok?

**Comment by j9liu** [comment]
Hi @kak0na,

As @kring mentioned, this bug was addressed in Cesium for Unreal v2.9.0. We recommend upgrading your version so you can get access to the latest features and bugfixes :smile:

**Comment by j9liu** [comment]
I'm closing this issue since there's nothing actionable for us. If you experience this issue on a later version of the plugin, please let us know and we'll be happy to help. ☺️
