### ISSUE TITLE
Pawn falls through cesium tileset

### ISSUE THREAD

**Issue by TrueNorthTrent** [CesiumGS/cesium-unreal#1558]
Hi team,

I've been having trouble getting collision working for players in Unreal Engine when using Cesium tilesets. I initially thought upgrading to UE 5.5 might fix the issue due to the Chaos Engine changes, but unfortunately, the problem persists. My characters consistently fall through the tileset floor, and it seems like the collision isn't recognized.

Here's what I've observed so far:

Behavior:

When the game is running in standalone mode, or as a client in multiplayer mode, the pawn falls through the Cesium tileset floor.
In Listen Server mode, the collision works as expected, and the character doesn't fall through the tileset.
Debugging Steps:

I've tried increasing the character capsule's collision size to ensure it interacts with the tileset properly.
Verified that the Cesium tileset is loaded in the world when the issue occurs.
Enabled collision settings on both the Cesium3DTileset and the CesiumGltfPrimitiveComponent with no success.
Observed no noticeable collision response even though the tiles are visible and rendered correctly.
Environment:

Unreal Engine versions 5.3, 5.4, and 5.5 all exhibit this behavior.
Issue primarily occurs in rural tilesets (possibly related to tile streaming or dynamic loading).

**Comment by TrueNorthTrent** [comment]
Findings:
After additional debugging, I noticed:

The collision issue seems to be tied to NetMode settings:
In Listen Server mode, collision behaves correctly, possibly because the server has full authority.
In Standalone mode, the tileset or its collision may not be initialized or handled properly, leading to the character falling through.
I suspect this could be related to:

Improper initialization of collision volumes for Cesium tiles in certain net modes.
Components like CesiumGltfPrimitiveComponent not being supported for collision in non-replicated contexts.
Request for Help:
Has anyone encountered similar issues with Cesium tileset collisions in Unreal Engine? Here are some specific questions:

What configurations or workflows have you used to ensure Cesium tilesets properly support collision in both standalone and multiplayer modes?
Are there known limitations or workarounds for collision in dynamically loaded tiles?
Could this issue be related to how Cesium integrates with Unreal's Chaos Engine for collision?
Any insights, suggestions, or advice would be greatly appreciated! Let me know if more logs or project details would help debug further.

**Comment by kring** [comment]
@TrueNorthTrent you should post this to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10), where it's likely to be seen by more people.

The fundamental problem you're running into is probably the one described here:
https://cesium.com/learn/unreal/unreal-placing-objects/#what-you-dont-see-is-what-you-dont-get

I don't have much experience with networked games, but I suspect that whatever is doing the collision checks in your case (the server?) doesn't have cameras (even virtual ones) in the correct locations in order to make the necessary tiles load in those areas.

**Comment by TrueNorthTrent** [comment]
So does this mean Cesium doesn't support Multiplayer builds?
