### ISSUE TITLE
Developer Guide for Setup, Build, Testing

### ISSUE THREAD

**Issue by shehzan10** [CesiumGS/cesium-unreal#164]
As the title says - this guide should be focused on users who want to setup, build, test, and contribute using the source code.

**Comment by javagl** [comment]
This is at least related: https://github.com/CesiumGS/cesium-unreal/issues/296#issuecomment-822605698 
What I wrote there goes a bit beyond the `cesium-native` part. I assume that this will not be on the website, but a markdown file in the `Documentation` folder.

**Comment by kring** [comment]
Addressed in #384.
