### ISSUE TITLE
Consider on-screen statistics for tileset traversal

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#170]
This is not "important" or "critical" right now, but maybe something to consider for the future.

During my attempts to get started with the actual Unreal parts and Blueprints, I thought that it might be useful to have some sort of on-screen statistics for the traversal process. Right now, this information is logged as `WARNING` to the console, and will likely be removed/disabled before the release.

My initial experiments are in the branches

https://github.com/CesiumGS/cesium-unreal-demo/tree/stats-widget
https://github.com/CesiumGS/cesium-unreal/tree/stats-widget

These are **not** really a "starting point" for actually implementing that, but just added here for the record. They are just first shots, and certainly "bad" along multiple dimensions of this term...

It is implemented as a Blueprint for the actual widget, and one for filling that widget with an "actor component". This means that it is *attached* to *one* tileset. In a proper implementation, this widget could/should offer the options for showing the stats for each tileset individually, and for all tilesets summarized. Which - to my understanding - means that it could not be an "actor component" any more. It probably would have to be integrated in the "level blueprint". I still have to wrap my head around these concepts. 

But in any case, the basic idea was to show something like this...

![TilesetStats](https://user-images.githubusercontent.com/5597569/109395581-5e72c080-792d-11eb-9a17-f1058b0e0488.png)

Some cruicial questions here will revolve aroung "Which statistics will be displayed?", "How to aggregate the stats for *multiple* tilesets sensibly?", and "What is the structure with which this information is exported?". There currently is a [`FTilesetsStats`](https://github.com/CesiumGS/cesium-unreal/compare/stats-widget#diff-468b9ea6c44edfd8e4910b96849ca9191065abe1906d98a3593589d9640354f7R26) structure, which likely would be in no way sufficient, and of which I'm not sure whether it's the right approach for that in general.

**Comment by kring** [comment]
> Right now, this information is logged as WARNING to the console, and will likely be removed/disabled before the release.

We no longer log by default, but there's a Tileset option to turn on logging. So I think that meets the need pretty well and I'm going to close this.
