### ISSUE TITLE
Plugin packaging notes

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#179]
Notes related to packaging the Cesium for Unreal plugin for the Epic marketplace. Eventually we'll write issues for specific actions and close this issue, but for now these are just notes.

Plugin docs:
https://docs.unrealengine.com/en-US/ProductionPipelines/Plugins/index.html

Epic's Marketplace guidelines:
https://www.unrealengine.com/en-US/marketplace-guidelines

From https://www.unrealengine.com/en-US/marketplace-guidelines#262a:
> Code plugins must not be ‘closed-source’ with regard to any code the publisher created which requires Unreal Engine source code to compile; that code must be included in the zipped up plugin folder.

But what about cesium-native and its third-party dependencies? Ideally we would ship:
1. Public header files for cesium-native as well as any third-party headers included directly or indirectly by these.
2. Pre-built .lib files for cesium-native and third-party dependencies.

A major concern with point (2) is ABI compatibility, especially given that cesium-native has plenty of STL in its public interface. Do end-users have to use exactly the compiler version that we built cesium-native et al with? Or do we have to provide cesium-native built against a bunch of different compiler versions?

On Windows, at least, the answer appears to be no:
https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160

Microsoft guarantees ABI compatibility of VS2015-2019 so long as the version used to link is greater than or equal to the newest version used to compile. Which means that we'll get the best compatibility if we use the oldest compiler that is supported by UE and that can compile our code. [This page](https://docs.unrealengine.com/en-US/WhatsNew/Builds/ReleaseNotes/4_26/index.html#new:platformsdkupgrades) indicates that for UE 4.26 the oldest supported is VS2017 v16.5. Given that our code probably doesn't compile with VS2017, and VS2019 has been out nearly two years now, I'm inclined to just set the minimum requirement at VS2019 until that causes a major problem for someone.

On Linux, binary builds of the engine aren't available. Users will likely have to build our plugin and its dependencies using whatever toolchain they use to build the engine.

On other operating systems, I don't know.

**Comment by shehzan10** [comment]
Plugin packaging has been added to Travis.
