### ISSUE TITLE
Improve appearance of OSM buildings

### ISSUE THREAD

**Issue by apuzinio** [CesiumGS/cesium-unreal#184]
OSM buildings currently appear as grey boxes. Would it be possible to add some modeling and shading detail to get them closer in appearance to the fidelity of the satellite image maps used on the terrain? Could we consider Unreal Blueprints to specify procedural rules that allow further control on appearance and variations? Thanks!

**Comment by kring** [comment]
I wrote #389 to cover "somehow" styling by feature attribute, but I'm closing this issue because it's not actionable.
