### ISSUE TITLE
Learning Content: Pre-launch content master issue

### ISSUE THREAD

**Issue by dzungpng** [CesiumGS/cesium-unreal#227]
This is a master issue used to keep track of discussions regarding learning content mentioned on the [Cesium for Unreal T-30](https://github.com/CesiumGS/engineering/issues/65#issuecomment-794531802) issue. To reiterate, the learning content includes:

🟢 Done (Published!)
🟡 In Progress (make sure to include stage i.e. _write-up needed_, _review needed_, etc)
🔴 Not started

### Primary Tutorial Path
* 🟢 **Quick Start Guide** Issue: https://github.com/CesiumGS/cesium-unreal/issues/153 | [Pull Request](https://github.com/CesiumGS/cesium.com/pull/1921)
    * Assigned to @dzungpng
    * Walkthrough of Level 1 (01_CesiumWorld) scene
    * Needs updating after Feature Freeze
* 🟢 **Importing Photogrammetry** Issue: https://github.com/CesiumGS/cesium-unreal/issues/260 | [Pull Request](url)
    * Assigned to @kring
    * Walkthrough of Level 2 (02_CesiumMelbourne) scene
* 🟢 **Utilizing Custom Controllers** Issue: https://github.com/CesiumGS/cesium-unreal/issues/261 | [Pull Request](https://github.com/CesiumGS/cesium.com/pull/1970)
    * Assigned to @argallegos 
    * Walkthrough of Level 3 (03_CesiumDenver) scene
* 🟢 **Guides - Rebasing with Unreal Engine and Placing your objects on the globe** (2 days) https://github.com/CesiumGS/cesium-unreal/issues/160  | [Pull Request](url)
    * Assigned to @nithinp7 
    * This asks for diagrams and explanations of rebasing conceptually. Should also include info on georeference component.
* 🟢 **Building Global Scenes with Sublevels** Issue: https://github.com/CesiumGS/cesium-unreal/issues/262 | [Pull Request](url)
    * Assigned to @argallegos and @nithinp7 
    * Walkthrough of Level 4 (04_CesiumSublevels) scenes
* 🟡 [Barebones] **Lighting and Rendering Scenes** Issue: https://github.com/CesiumGS/cesium-unreal/issues/263 | [Pull Request](url)
    * Assigned to @argallegos 
    * Pushed to post-launch to prioritize others
    * Walkthrough of Level 5 (05_CesiumPostProcessing) scene
    * Configuring SunSky, Atmosphere, Lighting, etc

### Additional Core Tutorials
* 🟢 **Level 2 - Flight tracking tutorial** (in-progress, 3 days) https://github.com/CesiumGS/cesium-unreal/issues/158  | [Pull Request](url)
    * Assigned to @dzungpng
* 🔴[Not started] **Guides - Introduction to 3D Tiles and Geospatial Concepts for Unreal Engine** (2 days) https://github.com/CesiumGS/cesium-unreal/issues/159  | [Pull Request](url) 
    * Assigned to @kring 
    * Neither of Dzung or Alex thought we were in the best position to write this one, but we could both format it if someone else wrote it.
* 🟢 **Fly tos** (in-progress) https://github.com/CesiumGS/cesium-unreal/issues/156  | [Pull Request](url)
    * Assigned to @dzungpng 
    * Used to include saving camera views, not anymore

### Pushed to post-launch/Stretch Core Tutorials:
* 🔴 Level 1 - AEC Tutorial (3 days) https://github.com/CesiumGS/cesium-unreal/issues/155 --> @shehzan10 mentioned in one-on-one with @dzungpng that this tutorial can be pushed back to after March 30th initial launch
    * Assigned to @dzungpng 
* 🔴 Recording videos with Sequencer (2 days) https://github.com/CesiumGS/cesium-unreal/issues/162 --> let's push until after launch
    * Assigned to @argallegos
* 🔴 [Needs migrate to website] **Using local storage data** (1 day) https://github.com/CesiumGS/cesium-unreal/issues/154 -->  
    * Assigned to @dzungpng
    * Has been separated from connecting to cesium ion/ getting started
* 🔴 **Best Practices for mouse/keyboard/gamepad interactivity** (2 days) https://github.com/CesiumGS/cesium-unreal/issues/161 -->
    * Assigned to @argallegos
    * need to do more research into this but Alex can do it
    * Kind of included in Using Custom Controllers

### Unsure About Status
 * ⚪[Unsure about status] **Add tooltips documentation** https://github.com/CesiumGS/cesium-unreal/issues/138 --> Not sure if this is something @javagl is up for/already working on
 * ⚪[Unsure about status] **Documentation on all blueprint-exposed cesium functions** (No issue yet!)
    * (Marco is working on this?)

### On the Chopping Block
* 🔴[On the chopping block] **Level 1 - Creating Levels and Scenes + Best Practices** (1 week) https://github.com/CesiumGS/cesium-unreal/issues/157 --> 
    * Assigned to @argallegos
    *  To be removed - split between Lighting and Rendering Scenes and Troubleshooting/Best Practices - note that most of the Best Practices content is divided between the previous tutorials
* 🔴[Not started] **Troubleshooting/ Best Practices** (1 week) NO ISSUE YET --> 
    * Assigned to @argallegos
    * This page would cover lots of small issues users might encounter and how to resolve them
    * May not be needed based on how much of alex's notes on this get integrated into other tutorials

### Additional material:
* 🟢 [Needs review + writeup] **Setup cookie-cutter started project templates + documentation** (2-3 days) --> 
    * Assigned to @argallegos
    * Create a new project that can serve as the starting point of all future demos and tutorials. The current cesium-unreal-demo was setup by C++ developers who tried Unreal. We would like to have a project created that can serve as the template going forward.

**Comment by argallegos** [comment]
Closing this, as it's been migrated to https://github.com/CesiumGS/cesium-unreal/issues/352.
