### ISSUE TITLE
Do we need to include a Copyright on Apache License?

### ISSUE THREAD

**Issue by shehzan10** [CesiumGS/cesium-unreal#229]
See https://github.com/CesiumGS/cesium/blob/master/LICENSE.md

**Comment by kring** [comment]
@shehzan10 do we need any action here?

**Comment by shehzan10** [comment]
@kring IANAL - I had opened this as there was a difference between what we did with CesiumJS (and other OSS project like glTF-pipeline) and Cesium for Unreal with respect to a copyright header in the license file.

I've seen Apache licenses done both ways, so no solid preference from me on this.

**Comment by kring** [comment]
We shouldn't add extra copyright text to the top of the LICENSE file. That would imply we're claiming copyright on the license itself, which we aren't and can't. IMO CesiumJS has this wrong.

As for source files, the authors of a source file own the copyright on that source file. When the author isn't Cesium, our CLA guarantees we have the right to use any outside contributions under the Apache 2.0 license. None of this is changed by adding special text to the top of a source file (or not). Users might find it helpful to have the license / copyright stated clearly at the top of the source file, but I don't see any way in which it is legally necessary. And we can always add it in the future if we have a reason to do so.

I'm not a lawyer, but I think that's all pretty uncontroversial. So I'm going to close this. Reopen if we want to do a proper legal review.
