### ISSUE TITLE
Determine if ComputeEastNorthUpToUnreal has a bug

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#265]
I must have introduced this in #222 when originally implementing `CesiumGeoreference::ComputeEastNorthUpToUnreal` based on a previous version of the function in `GlobeAwareDefaultPawn`. I ran into the issue that `GlobeAwareDefaultPawn::MoveUp_World` wasn't working when far from the origin. This is fixed in #264 but the underlying issue that originally caused it is unclear to me, but it seems to have something to do with `ComputeEastNorthUpToUnreal`.

**Comment by nithinp7** [comment]
The commented out code that mysteriously didn't seem to work:
https://github.com/CesiumGS/cesium-unreal/blob/000b33741d25ad50733b5896a3b4aab05bdb2273/Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp#L63-L69

**Comment by kring** [comment]
@nithinp7 do you think this could have been fixed by #371?
If not, is it worth spending a bit of time to confirm that it's really a bug, and then we can prioritize a fix accordingly?

**Comment by nithinp7** [comment]
I remember this giving wildly wrong results so I'm not sure if it would have been fixed there. I will try to investigate the problem again this week so that at least we can prioritize.

**Comment by kring** [comment]
It's a year later and we're still not sure if this is a bug. Let's say it's not and close this. :)
