### ISSUE TITLE
Zooming out indefinitely causes flickering of position

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#284]
Looking down and then moving backwards quickly brings the whole world into the viewport. However, it glitches out at some point (*Edit: apparently, only in 'Play' mode*). It *looks* like the camera position is switching between "-large value" and "+large value", causing the globe to flicker and the navigation to behave erratically. 

This is accompanied by log messages
```
LogLevel: WORLD TRANSLATION BEGIN {2117412412, 2140242875, 2108424402} -> {2131858716, 2117999429, 2126970786}
LogLevel: WORLD TRANSLATION END {2131858716, 2117999429, 2126970786} took 0.3395 ms
...
LogLevel: WORLD TRANSLATION BEGIN {2131858716, 2117999429, 2126970786} -> {-2145834550, 2129722430, -2143266186}
LogLevel: WORLD TRANSLATION END {-2145834550, 2129722430, -2143266186} took 0.3437 ms
```
A wild guess is that the casts to `int` around https://github.com/CesiumGS/cesium-unreal/blob/c0d01255a669143e281337516ec9afae0e65d62f/Source/CesiumRuntime/Private/CesiumGeoreference.cpp#L522 are not the right thing to do, but that has to be analyzed further.

(An aside: Of course, there *is* a limit for zooming out. But for a "normal" unreal level, this seems to be orders of magnitude later, and in the case of Cesium, the observed behavior happens at a point where one could reasonably expect a "view of the full globe" to still work)

**Comment by kring** [comment]
Yep @javagl's diagnosis is spot-on. The origin can only be rebased out to a distance of about 21 million meters. Once we hit that limit, we should just stop rebasing (and let the local coordinates grow) rather than letting the coordinates wrap around.

**Comment by javagl** [comment]
This is one case of an issue that *might* possible to fix with reasonable effort, but that might have some conflict with https://github.com/CesiumGS/cesium-unreal/issues/330 (depending on when/how the latter is tackled). I can have a look at that later (and assign this issue to me **prelimiarily** (as a reminder)). **Iff** this is really fixable by adding some

    if (value < limit) rebase();
    else dont();

then I'd do that (usually, it's not that easy, but as such, "triaging" and estimating the effort is the first step here)

**Comment by javagl** [comment]
> usually, it's not that easy

Indeed. After adding some debug output...
```
      int32 newX = static_cast<int32>(cameraLocation.X) +
              static_cast<int32>(originLocation.X);
      int32 newY = static_cast<int32>(cameraLocation.Y) +
              static_cast<int32>(originLocation.Y);
      int32 newZ = static_cast<int32>(cameraLocation.Z) +
              static_cast<int32>(originLocation.Z);

      UE_LOG(
          LogCesium,
          Warning,
          TEXT("Camera at %f %f %f origin at %f %f %f move to %d %d %d"),
          cameraLocation.X, cameraLocation.Y, cameraLocation.Z,
          originLocation.X, originLocation.Y, originLocation.Z,
          newX, newY, newZ
        );

      this->GetWorld()->SetNewWorldOrigin(FIntVector(newX, newY, newZ));
```
it prints
```
LogCesium: Warning: Camera at 16580.853516 -2146.444336 50646.480469 origin at 0.000000 0.000000 0.000000 move to 10425604 -1390973 38126074
LogCesium: Warning: Camera at 16582.183594 -2146.467285 50646.433594 origin at 0.000000 0.000000 0.000000 move to 10442186 -1393119 38176720
LogCesium: Warning: Camera at 16582.605469 -2146.933105 50645.988281 origin at 0.000000 0.000000 0.000000 move to 10458768 -1395265 38227365
LogCesium: Warning: Camera at 16663.378906 -2158.106689 50888.050781 origin at 0.000000 0.000000 0.000000 move to 10475431 -1397423 38278253
LogCesium: Warning: Camera at 16584.863281 -2147.450684 50644.238281 origin at 0.000000 0.000000 0.000000 move to 10492015 -1399570 38328897
LogCesium: Warning: Camera at 16586.517578 -2148.251465 50644.019531 origin at 0.000000 0.000000 0.000000 move to 10508601 -1401718 38379541
```

The origin location is always (0,0,0). Certainly something trivial (but confusing nevertheless), investigating that further...
