### ISSUE TITLE
Double-precision wrapper types for blueprint

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#286]
Currently we have a suite of blueprint functions prefixed with "Inaccurate...". While these functions are still very useful (they take/return convenient FVectors), they are single-precision representations of cartographic and cartesian global coordinates and so they can be off by up to several meters. For some use cases this might be fine, but we should be able to support full double-precision on top of having convenient FVector-functions.

I imagine these wrapper types could be USTRUCTs called something like `DoubleCartographic`, `DoubleEllipsoidCentered`, and `DoubeUnrealCoordinates`. The structs each have their respective double-typed members within them, but as long as those members themselves are not exposed to blueprint, the struct itself could still be a valid blueprint type. The remaining work will be to add these types to the conversions interface, allow for casting to/from FVector, and define convenient double precision vector operations where appropriate. Probably conversions to/from strings might be necessary for completion, although their over-use should be discouraged.

We should think about and be clear on what this might improve and what it won't. For instance, there's not so much we can do about Unreal objects that are far from the origin. We could try saving/restoring the ECEF transform or otherwise transform the object _solely_ in internal double precision coordinates ourselves (not allow Unreal to move the object on its own accord). Both of these options will make the object hard to integrate with Unreal systems like physics. What we _can_ clearly improve on though is getting rid of intermediary ECEF and cartographic coordinates stored in single-precision.

**Comment by kring** [comment]
Cool idea, but with UE5 supporting real double precision types in Blueprints, and UE4's days being numbered, I don't think we'll ever do this. So I'm closing it.
