### ISSUE TITLE
Override raster imagery by tile-id

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#291]
Would it be possible to add some sort of plugin point into the raster-imagery pipeline which allows cesium-unreal to specify "override" textures for specific tile-ids? So cesium-native could prioritize the texture given from cesium-unreal over the current base-imagery from ion on a per-tile basis. The use-case for this would be to allow users to generate procedural textures for terrain when satellite imagery is not detailed enough.

Edit: Maybe this plugin point could be more of a post-processing step on streamed raster imagery to super-sample it procedurally before it is used.

Inspired by this question:
>Surface
By LoafMan on March 30, 2021 3:07 PM
How would I go about adding foliage and textures to ground level renders as seen in screenshot 11? Is there a way to transition to procedural textures when you get close and the satellite imagery is too blurry? Thanks!

on the Cesium for Unreal UE marketplace page.

**Comment by kring** [comment]
@nithinp7 do you think the above is sufficient? If so, we can close this issue.
