### ISSUE TITLE
Can I use self-published data?

### ISSUE THREAD

**Issue by DeZhao-Zhang** [CesiumGS/cesium-unreal#292]
Can I use the data of myself, such as wms layer from geoserver; 3d tiles of building from my tomcat server.

**Comment by kring** [comment]
Hi @DeZhao-Zhang, loading 3D Tiles from a local server is supported. You just need to populate the `url` property on the `Cesium3DTileset` Actor instead of the ion Asset ID and token.

We have support for Tile Map Service (TMS) and Bing Maps imagery servers, but not yet for WMS servers. You could probably implement a `RasterOverlay` (https://github.com/CesiumGS/cesium-native/blob/main/Cesium3DTiles/include/Cesium3DTiles/RasterOverlay.h) to support your particular server fairly easily, and a more general-purpose WMS implementation with a bit more effort.

**Comment by DeZhao-Zhang** [comment]
> Hi @DeZhao-Zhang, loading 3D Tiles from a local server is supported. You just need to populate the `url` property on the `Cesium3DTileset` Actor instead of the ion Asset ID and token.
> 
> We have support for Tile Map Service (TMS) and Bing Maps imagery servers, but not yet for WMS servers. You could probably implement a `RasterOverlay` (https://github.com/CesiumGS/cesium-native/blob/main/Cesium3DTiles/include/Cesium3DTiles/RasterOverlay.h) to support your particular server fairly easily, and a more general-purpose WMS implementation with a bit more effort.

thanks!

**Comment by baothientran** [comment]
this seems to be resolved. I close it for now, but feel free to re-open if anyone has any question or problem

**Comment by Thomson666** [comment]
Hello, how do I add GeoServer TMS services to the cesium is unreal through TileMapServiceRasterOverlay

**Comment by Thomson666** [comment]
Hello, how do I add GeoServer TMS services to the cesium is unreal through TileMapServiceRasterOverlay

**Comment by pratyush1611** [comment]
> 

The link you have posted doesn't seem to be working, is there a new version of this now?

**Comment by UnrealVistas** [comment]
We would also be very interested to import WMS data from https://www.bgs.ac.uk/technologies/web-map-services-wms/web-map-services-geology-50k/ into Cesium for Unreal but have no idea where to start.. Is this on some 'todo' list yet ?

**Comment by kring** [comment]
@UnrealVistas as of Cesium for Unreal v1.12.0, you can drape WMS layers over the top of other tilesets, such as Cesium World Terrain. Here's what it looks like with the server you mentioned:

![image](https://user-images.githubusercontent.com/924374/162338516-419d41dd-626c-431a-87e9-7468a0a24973.png)

To get this screenshot, I started with Cesium World Terrain + Bing Maps Aerial and added a new CesiumWebMapServiceRasterOverlay component to the CesiumWorldTerrain Actor. Then I set the component's "Base URL" property to `https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer`, its "Layers" property to `BGS.50k.Superficial.deposits`, and its "Material Layer Key" to `Overlay1`. I also increased the maximum level from 14 to 18.

**Comment by pratyush1611** [comment]
> @UnrealVistas as of Cesium for Unreal v1.12.0, you can drape WMS layers over the top of other tilesets, such as Cesium World Terrain. Here's what it looks like with the server you mentioned:
> 
> ![image](https://user-images.githubusercontent.com/924374/162338516-419d41dd-626c-431a-87e9-7468a0a24973.png)
> 
> To get this screenshot, I started with Cesium World Terrain + Bing Maps Aerial and added a new CesiumWebMapServiceRasterOverlay component to the CesiumWorldTerrain Actor. Then I set the component's "Base URL" property to `https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer`, its "Layers" property to `BGS.50k.Superficial.deposits`, and its "Material Layer Key" to `Overlay1`. I also increased the maximum level from 14 to 18.

Could we have a tutorial for this somewhere, even as a markdown file would work. I have tried to use the same procedure as you with these WMS services: [TU Delft 3D BAG](https://data.3dbag.nl/api/BAG3D_v2/wms?request=getcapabilities&service=WMS) with layer `bag_tiles_3k` and [PDOK WMS](https://service.pdok.nl/lv/bag/wms/v2_0?request=getCapabilities&service=WMS ) with layer `pand`, to no avail. 

I keep getting an error: `[error] [RasterOverlay.cpp:145] Web map service XML document does not have a Service element.` whereas when parsed in a browser, it is clearly visible that both the URL provide with an XML that has a `<Service>` tag.

**Comment by RidhwanAziz** [comment]
Yeah, I agree with @pratyush1611. It would be great if you can make a tutorial on this. I tried using the method which @kring recommended but got the similar error.

**Comment by IndigoYun** [comment]
> @UnrealVistas as of Cesium for Unreal v1.12.0, you can drape WMS layers over the top of other tilesets, such as Cesium World Terrain. Here's what it looks like with the server you mentioned:
> 
> ![image](https://user-images.githubusercontent.com/924374/162338516-419d41dd-626c-431a-87e9-7468a0a24973.png)
> 
> To get this screenshot, I started with Cesium World Terrain + Bing Maps Aerial and added a new CesiumWebMapServiceRasterOverlay component to the CesiumWorldTerrain Actor. Then I set the component's "Base URL" property to `https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer`, its "Layers" property to `BGS.50k.Superficial.deposits`, and its "Material Layer Key" to `Overlay1`. I also increased the maximum level from 14 to 18.

**Comment by IndigoYun** [comment]
> @UnrealVistas as of Cesium for Unreal v1.12.0, you can drape WMS layers over the top of other tilesets, such as Cesium World Terrain. Here's what it looks like with the server you mentioned:
> 
> ![image](https://user-images.githubusercontent.com/924374/162338516-419d41dd-626c-431a-87e9-7468a0a24973.png)
> 
> To get this screenshot, I started with Cesium World Terrain + Bing Maps Aerial and added a new CesiumWebMapServiceRasterOverlay component to the CesiumWorldTerrain Actor. Then I set the component's "Base URL" property to `https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer`, its "Layers" property to `BGS.50k.Superficial.deposits`, and its "Material Layer Key" to `Overlay1`. I also increased the maximum level from 14 to 18.

i follow your ways , but i getting an error: [error] [RasterOverlay.cpp:145] Web map service XML document does not have a Service element. too!

**Comment by kring** [comment]
That most likely means your URL is invalid. Are you sure it's a valid WMS URL?
