### ISSUE TITLE
Learning Content: Using CesiumSunSky

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#305]
Create a tutorial that explains how CesiumSunSky differs from Unreal's SunSky actor, how it interacts with the georeference, and how to modify it. 
This page should emphasize how the sunsky actor ensures **geographically accurate sun position**. If possible, include examples of situations where this is important.

This tutorial should additionally cover:

- Info on all parts of the SunSky blueprint, but especially:
   - Shadow draw distance
   - Light intensity
   - SkyAtmosphere - why it's important, the settings on it that we changed, how to troubleshoot common issues like black lines on horizon, patchy artefacts from space
- Setting the time zone to make sure the time slider matches up, explain how time zone must be set manually

**Comment by robhawkes** [comment]
> How to troubleshoot common issues like black lines on horizon

Is there a short-term resolution for this before the documentation gets updated? I've noticed this happening a couple times when I start a new level and not sure how to fix it yet. Any insight would be helpful.

**Comment by argallegos** [comment]
Hi @robhawkes,

I haven't been seeing the black lines lately on my end, but if you are I would love to know more so I can properly address it. Could you give me a little more information or steps to reproduce the black lines? Is it right at the start of a new level when you add the CesiumSunSky actor? Do they persist after connecting the CesiumSunSky actor to the georeference?

**Comment by robhawkes** [comment]
> Do they persist after connecting the CesiumSunSky actor to the georeference?

That was it — I hadn't set the reference to the sky actor! I must have previously been using a level that already had that connected, and didn't realise I needed to manually connect them together when I was creating my own levels from scratch.

**Comment by argallegos** [comment]
Great to hear! There is now a live [tutorial](https://cesium.com/docs/tutorials/cesium-unreal-sun-sky/) on CesiumSunSky on the site - I should actually close this issue now. If you have any other questions regarding CesiumSunSky, though, please let me know and I can address them here or as an update to the tutorial page.
