### ISSUE TITLE
Learning Content: Importing local 3D Tilesets

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#306]
This is a very simple set of steps, but we currently do not have explicit instructions online for this. We have been getting a lot of questions on this and have been repeating ourselves quite a bit, so I think we should get this one up soon.

**Comment by zsunpl** [comment]
I found that there is a “loadTilesFromJson” function in Tileset class. Maybe it is the entrance to load local tileset. But I haven't test it yet.
