### ISSUE TITLE
Move helper transform functions to static function library

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#318]
There's an idea of a Blueprint Function Library, which is basically a collection of static BlueprintCallable functions, defined in C++, that can be used anywhere in the project in Blueprints and C++. Perhaps it may be useful to move some of the helper functions in `CesiumGeoreference` (like `TransformRotatorEnuToUe`) to this function library so actors won't necessarily need to get a reference to `CesiumGeoreference` in order to make use of them. What do you think?

The syntax looks something like this:
```
UCLASS()
class MYMODULE UMyFunctionLibrary : public UBlueprintFunctionLibrary
{
   GENERATED_BODY()
public:
   UFUNCTION(BlueprintPure, Category="My Function Library")
   static FVector MyConversionFunction(const FVector& InVector);
```

**Comment by nithinp7** [comment]
Great idea, I hacked those functions into place very last-second, it would make a lot more sense as static functionality. They still need the `CesiumGeoreference` reference, but it should be possible to get a static reference to CesiumGeoreference (or create one if it doesn't exist) by using `GetDefaultForActor(actor)`. I wrote another version called `GetDefaultForLevel(level)` but it's still in a branch, but both may be useful for implementing the function library.

**Comment by xuelongmu** [comment]
Great, I can get started on that tomorrow I think.

> `GetDefaultForActor(actor)`. I wrote another version called `GetDefaultForLevel(level)` 

Is there a reason not to use `GetActorOfClass` here?

There's also a neat trick with these types of functions. You can define it like this: 
```
UFUNCTION(BlueprintPure, meta=(WorldContext="WorldContextObject"))
static AActor* GetCustomActorFromWorld(const UObject* WorldContextObject);
```
and in Blueprints, it will automagically pass in the WorldContextObject without exposing a separate input pin. In C++ you would simply pass in `this`
