### ISSUE TITLE
Improve Georeferenceable interface and make it blueprint-friendly

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#321]
Currently the `ICesiumGeoreferenceable` interface does two somewhat unrelated things:
- One, it allows implementations to be notified when the georeference has been updated. 
- Two, in the case that the georeference origin placement mode is set to "bounding box" (average center between all sub-boxes), the interface allows implementations to return their own bounding volume to contribute to the origin placement. This is so far only used by tilesets and is completely ignored by all other "georeferenceable" objects. 
 
Maybe we should have two different interfaces for these two functionalities. Something like `GeoreferenceListener` that is sent notifications pre- and post- georeference change, and something like `WithBoundingVolume` (hahah not actually sure what to call this one actually). 

The main benefit that would come from this is that it would make the `GeoreferenceListener` functionality much easier to use. This would allow custom user actors/components (even ones in blueprint) to subscribe and be notified of when a georeference change is about to take place. This would allow for disabling physics, creating a last-ditch georeference that can be restored after the change, etc.

**Comment by kring** [comment]
This interface no longer exists.
