### ISSUE TITLE
Editor: Sublevels UI, automate sublevels workflow

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#326]
A straightforward UI for georeferenced sublevels will help make the workflow much less confusing. We should also automate the existing workflow and semantically restrict the georeference to prevent accidents when working on sublevels. Some ideas that might be useful:
- We should lock the georeference into one active sublevel at a time and not allow for it to change unless switching to another sublevel or entering into a "roaming mode". 
- In the roaming mode the georeference should be free to move but none of the sublevels are allowed to be loaded.
- There should be a more convenient menu of sublevels, any of which can be double-clicked to switch to that one (we should check if current sublevel is saved first). 
- When jumping to another sublevel we should automatically unload the old one, load the new one, lock the georeference to the new one, and move the camera there. 
- When creating a new sublevel, we should have some UI that can nicely place the georeference to initialize it. New sublevels should also automatically be added to a world composition layer where Unreal distance streaming is disabled.

**Comment by kring** [comment]
A lot of the goals here were achieved with the sublevel refactoring awhile back. The rest we're not likely to implement any time soon because sublevels are deprecated in UE5. Closing.
