### ISSUE TITLE
Generate navigation mesh on Cesium3DTileset

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#327]
Navigation meshes can be generated in Unreal for movable static meshes. However, navigation meshes currently cannot be generated on the Cesium World Terrain, which is a `Cesium3DTileset` actor. I have experimented with adding a `UNavLinkComponent` to `Cesium3DTileset` in the [navmesh-generation](../tree/navmesh-generation) branch with [Navigation Invokers](https://www.youtube.com/watch?v=QNHInJJ1vUk&list=WL&index=58) and dynamic navmesh generation turned on, but haven't gotten it working yet.

As this is not a priority feature for the upcoming update, I will revisit this issue in the future.

**Comment by argallegos** [comment]
Forum requests for this feature: 
https://community.cesium.com/t/cant-use-nav-mesh-on-cesium-terrain/18465
https://community.cesium.com/t/adjusting-nav-mesh-bound-volume-according-to-the-terrain/17833/4
https://community.cesium.com/t/generating-navmeshes/12998

**Comment by j9liu** [comment]
Closed by #1044.
