### ISSUE TITLE
Hardcoded source paths in released plugin on Marketplace

### ISSUE THREAD

**Issue by techdragon** [CesiumGS/cesium-unreal#328]
When trying to open the source for one of the blueprint functions, as used in the sample project and when creating a brand new project and just adding the project. The "double click to open function sources" capability is broken. It just results in the attached screenshot. Which looks like a hardcoded path issue because the plugin definitely has the sources included when I check the plugin folder in my engine install directory. 
![PackagedPluginIssueA](https://user-images.githubusercontent.com/2115079/114295064-72394700-9ad5-11eb-96fe-6b244b6b1541.png)

**Comment by xuelongmu** [comment]
Could you try converting your unreal engine project to a C++ project? (Just add a single C++ class)

I think I remember having had this error before, when trying to open the C++ definition for a blueprint node from a blueprint-only project.

**Comment by techdragon** [comment]
@xuelongmu I just did a quick test. I took my test project, added an empty C++ opened up CLion, made sure it had the cmake loaded and tried to open the source from the blueprint in the unreal engine editor and I get the same error.

**Comment by xuelongmu** [comment]
@techdragon Thank you for the test. I was able to replicate the issue (in my case using VS 2019 as the source code editor) and will look further into this.

![image](https://user-images.githubusercontent.com/10490807/114567277-14c20900-9c41-11eb-9264-bd09a23ecb1a.png)

**Comment by kring** [comment]
The way the marketplace plugin publish process works is we submit our source code, and then Epic builds it themselves and makes it available on the marketplace. So that path is from Epic's plugin build infrastructure and we probably can't change it. But maybe there's a way to make a double-click in the editor work anyway.

**Comment by kring** [comment]
On my system, double-clicking any Blueprint function, even one built into the editor, results in a similar error. And this is true even if the Cesium plugin is disabled. So I don't think this is something we can fix. Maybe report it to Epic?
