### ISSUE TITLE
Add macOS build to Travis CI

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#333]
Both to verify that they work and to produce official plugin builds.

**Comment by kring** [comment]
Strangely, the Travis [Build Environment Overview](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) doesn't indicate what cloud environment is used to run macOS builds. The only source I could find is [this blog post from 2017](https://blog.travis-ci.com/2017-09-22-macos-update), which says they run on "VMWare vCenter vSphere, hosted on MacStadium". If that's true, downloading 10GB of UE from Google Cloud Storage on each macOS build will get very expensive. We should:
1) confirm the cloud environment,
2) see if we can get a VMWare account and if it offers free in-cloud transfers like GCP and AWS do, and
3) failing that, at least host the UE files necessary for the build on AWS instead of GCP because AWS is cheaper.

**Comment by shehzan10** [comment]
@kring Travis support is generally very responsive.

**Comment by shehzan10** [comment]
xRef: GitHub Actions as an option https://github.com/CesiumGS/cesium-native/issues/204

**Comment by kring** [comment]
According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses, macOS builds on GitHub Actions are hosted in GitHub's own cloud. So it's not clear how we avoid the 90 cents per build it would cost to transfer the UE build files. I wonder if we can host them on GitHub itself?

**Comment by kring** [comment]
Added in #345

**Comment by kring** [comment]
If I'm calculating correctly, downloading the UE files from Google Cloud Storage will cost about $1.20 per macOS build right now. AWS would be about $0.90. Note huge but it adds up. The cheapest option I could find with a quick look was Backblaze, which would be about 10 cents per build: https://www.backblaze.com/b2/cloud-storage-pricing.html

**Comment by baothientran** [comment]
Do you know the size of UE binary for window? Maybe I can remove some unnecessary files on Mac to see if the size can be reduced
