### ISSUE TITLE
Allow Cesium3DTileset properties to be get/set in Blueprints

### ISSUE THREAD

**Issue by drawmindmap** [CesiumGS/cesium-unreal#342]
Can we add BlueprintReadWrite to url and other properties?

**Comment by xuelongmu** [comment]
@kring @baothientran @javagl Any caveats to exposing the `Url`, `IonAssetID`, and `IonAccessToken` as BlueprintReadWrite properties? I tested with changing the latter two at runtime with Cesium World Terrain and the tileset updated appropriately, just as it would in editor mode.

**Comment by kring** [comment]
That sounds reasonable to me!

**Comment by nithinp7** [comment]
@xuelongmu hm so `Cesium3DTileset::LoadTileset` is currently only called in `BeginPlay` and `OnConstruction`. I know `OnConstruction` runs when properties are changed in the editor, but is that also the case when a property is changed from blueprint during play?
