### ISSUE TITLE
Learning Content: Post-Launch Master Issue

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#352]
### Update: This is now deprecated, visit https://github.com/orgs/CesiumGS/projects/2 for an updated learning content project board.

This is a continuation of https://github.com/CesiumGS/cesium-unreal/issues/227, the pre-launch master issue. Figured it's better to make a fresh issue for learning content going forward. This issue will track the status of individual learning content pages, and also be a discussion board for the structure of tutorials going forward.

With that, I'm proposing a reorganization for learning content in the comment under this.

Please update this comment as tutorials are updated/completed.
Each entry should follow the following format: 
* 🟢/🟡/🔴 **Name of issue** Issue: Link to issue 
    * Assignee
    * Description and any relevant notes

Status symbols
🔵 Done (Published!)
🟢 Ready for Prismic migration
🟡 In Review
🔴 In Progress
⚪ Not started
Urgency symbols
❌ Blocked
❗ High priority, do this first

### Task Tracker
* Getting Started tutorials
    * Currently none, may be revisited after a major plugin update
* Create interactive experiences - For projects and apps that users can create
    * ⚪❌**AEC Tutorial/Visualize a Proposed Building** https://github.com/CesiumGS/cesium-unreal/issues/155
        * Currently blocked due to lack of clipping planes
    * 🟡 **[User-submitted] Procedural Foliage** 
        * @argallegos reviewing
        * Description and any relevant notes
    * ⚪❗  **Recording videos with Sequencer** https://github.com/CesiumGS/cesium-unreal/issues/162
        * Assigned to @argallegos 
        * Description and any relevant notes
    * ⚪❗ **Getting started with VR** https://github.com/CesiumGS/cesium-unreal/issues/530
        * @getinthedamnbox 
    * ⚪ **Programming with Cesium for Unreal (Series)** https://github.com/CesiumGS/cesium-unreal/issues/531
        * Assignee
* Build words - using plugins and Unreal tools to build out worlds 
    * ⚪ **Clipping regions/cartographic selections** https://github.com/CesiumGS/cesium-unreal/issues/528 
        * Assignee
        * Description and any relevant notes
    * ⚪ **Importing assets from Quixel** https://github.com/CesiumGS/cesium-unreal/issues/358
        * Assignee
        * Description and any relevant notes
    * ⚪ **Creating high quality water** https://github.com/CesiumGS/cesium-unreal/issues/357
        * Assignee
        * Covers watermask and water plugin
    * ⚪ **Working with landscapes** https://github.com/CesiumGS/cesium-unreal/issues/356
        * Assignee
        * Description and any relevant notes
    * 🔴❗ **Modifying a tileset's material** https://github.com/CesiumGS/cesium-unreal/issues/359
        * Assigned to @argallegos 
        * Description and any relevant notes
    * ⚪❌ **Painting materials over a tileset** https://github.com/CesiumGS/cesium-unreal/issues/360 
        * Assigned to @argallegos 
        * Currently blocked until we figure out how to save mesh painting
* Technical tutorials - these are pages that explain technical aspects of the plugin that don't necessarily have a specific set of steps to follow or a project to create
    * ⚪[Not started] **Guides - Introduction to 3D Tiles and Geospatial Concepts for Unreal Engine**  https://github.com/CesiumGS/cesium-unreal/issues/159  
        * Assigned to @kring 
        * A technical deep dive
    * ⚪[Not started] **Documentation on all blueprint-exposed cesium functions** https://github.com/CesiumGS/cesium-unreal/issues/361 
        * Assigned to nobody
        * We should have documentation on everything people can access from Blueprint
    * ⚪❗ **Frequently Asked Questions** https://github.com/CesiumGS/cesium-unreal/issues/550
        * @argallegos 

###Completed tutorials
* Primary Tutorial Path / Getting Started
    * 🔵 **Quickstart** https://github.com/CesiumGS/cesium-unreal/issues/153 | [Live Page](https://cesium.com/learn/unreal/unreal-quickstart/)
    * 🔵 **Adding Datasets** https://github.com/CesiumGS/cesium-unreal/issues/260 | [Live Page](https://cesium.com/learn/unreal/unreal-datasets/)
    * 🔵 **Placing Objects on the Globe** https://github.com/CesiumGS/cesium-unreal/issues/160 | [Live Page](https://cesium.com/learn/unreal/unreal-placing-objects/)
    * 🔵 **Building Global Scenes with Georeferenced Sublevels** https://github.com/CesiumGS/cesium-unreal/issues/262 | [Live Page](https://cesium.com/learn/unreal/unreal-sublevels/)
    * 🔵 **Transition Between Locations on the Globe** https://github.com/CesiumGS/cesium-unreal/issues/156 | [Live Page](https://cesium.com/learn/unreal/unreal-flyto/) 
* Create interactive experiences
    * 🔵 **Using Custom Controllers** https://github.com/CesiumGS/cesium-unreal/issues/261 | [Live Page](https://cesium.com/learn/unreal/unreal-custom-controllers/)
    * 🔵 **Build a Flight Tracker with Cesium for Unreal** https://github.com/CesiumGS/cesium-unreal/issues/158 | [Live Page](https://cesium.com/learn/unreal/unreal-flight-tracker/)
* Build worlds
    * 🔵 **Lighting and Rendering Scenes** https://github.com/CesiumGS/cesium-unreal/issues/263 | [Live Page](https://cesium.com/learn/unreal/unreal-post-processing/)
    * 🔵 **Placing Foliage on Cesium Tilesets** https://github.com/CesiumGS/cesium-unreal/issues/308 | [Live Page](https://cesium.com/learn/unreal/unreal-foliage/)
    * 🔵 **Using CesiumSunSky** https://github.com/CesiumGS/cesium-unreal/issues/305 | [Live Page](https://cesium.com/learn/unreal/unreal-geospatially-accurate-sun/)

**Comment by argallegos** [comment]
This comment is under construction - will contain organization thoughts

**Comment by LisaBosCesium** [comment]
@argallegos Thanks for pinging me on this. 

Agree, this fits nicely with the plans for the revised Learning Center navigation on the new website - and in fact is a great validation of why we need it. On the new site, the user will:

1. Go to the Learning Center (cesium.com/docs)
2. Click on "Cesium for Unreal" in a top subnav (officially called the "sibling nav" - example is the list of industries [here](https://cesium.com/industries/aec/))
3. Be shown a landing page for Cesium for Unreal, and be able to interact with a left nav that is specific to Cesium for Unreal - what you list above

And of course they can bookmark and we can link to the Unreal landing page as helpful. 

There are only two more headings in the Unreal nav above than on the current site, so I think we can implement this on the current site without negatively impacting users. I'm glad we're getting the new nav though - will be very crowded pretty soon on the current site, and the current (annoying) scroll behavior when left nav document headings are expanded could potentially get a little worse.

Whatever tutorial content is under development in May will be included in a piloting effort to make sure the nav and other Prismic/site components work as we want them to, so the timing of this work is great. Will also want your input on the Unreal landing page content.

**Comment by LisaBosCesium** [comment]
@argallegos (and all who have opinions)

1) It's time to decide on the first incarnation of the Cesium for Unreal left nav for the new site. We can easily expand it over time as more content is added. We don't have live content for these sections. Will we by June 11?

- Building Realistic Worlds
- Lighting and Rendering
- Technical Guides

2) As noted, in the revised Learning Center we will have an Unreal landing page. The general idea for these is to a) link to key tutorials/guides, b) highlight what's new, and c) link out to cool community content (eg user projects). For Unreal I assume we'll also link to the Unreal Marketplace. I'll draft a first pass and circulate it for review, but let me know if you have additional/different/specific ideas.

**Comment by argallegos** [comment]
@LisaBosCesium 

Thanks for checking in. Currently under review we have a single tutorial page each for Building Realistic World and Lighting and Rendering, and a second tutorial for Lighting and Rendering is in the works. The plan for those three is to merge them all in sometime this week, so they will definitely be live by June 11. 

We don't have anything yet for the Technical Guides section, so I think we should omit that category for now, but plan to add it later. 

I'm excited to see the new landing page, all the content that you have planned sounds good! I'll let you know if I think of anything specific that needs to be on it.

**Comment by LisaBosCesium** [comment]
Thanks, @argallegos!

**Comment by argallegos** [comment]
@LisaBosCesium The merge for the tutorials currently under review is pushed to early next week to align with the plugin update. I'll let you know when they're live!

**Comment by LisaBosCesium** [comment]
@argallegos Where does Transition Between Locations on the Globe fit in the new outline?

**Comment by LisaBosCesium** [comment]
@argallegos When the new tutorials are ready to go, let me know and I'll schedule some time for you and me to talk about getting them into Prismic. This is the week for doing a pilot of sorts to see whether you have feedback we want to react to in time for launch of the new Learn at the end of next week.

**Comment by argallegos** [comment]
@LisaBosCesium 

The Transition Between Locations tutorial belongs in the Example Projects section. I'm just doing final touches now, and the new tutorials should be ready to merge by EOD today. We can talk tomorrow if you're free!

**Comment by LisaBosCesium** [comment]
@argallegos Our schedules today only allowed for 30 minutes, but that should do it - more tomorrow if needed.

**Comment by argallegos** [comment]
This tracker has been updated to reflect the the new categorization of the learning content, and reorganize based on current status of individual pages. Note that it does not match the categories suggested in the second comment on this issue.

**Comment by argallegos** [comment]
Now that we have this public project board for tracking learning content, I'm retiring this issue. Visit the project board instead: https://github.com/orgs/CesiumGS/projects/2
