### ISSUE TITLE
Missing tiles or geometry when rendering base terrain or imagery

### ISSUE THREAD

**Issue by shehzan10** [CesiumGS/cesium-unreal#354]
See https://youtu.be/I2coPB0jJQI?t=1039 - The "M" on the mountains near the starting place in default georeference.

**Comment by kring** [comment]
The black areas are part of the Bing Maps imagery. Not something we can fix.
[This Sandcastle](https://sandcastle.cesium.com/#c=bZBRT8MgFIX/CulTl1TqbJxRu8ZkvphoNLroCy8M7iqRwnKhndP434Wixuh44tz7nXMvDBzJoGALSObEwJYswKm+o49jLWeZGPXCGs+VAWRZQd6ZIcQDYqjcoR2UBDz7NgoE7uHJopbLhOQTZj4m58x8EWlcElfGbUB4izfqNZCpFdl0o4J3gJw68HGhfJwswXlluFfW/Ey9DyHctBroGm13CS0CuPxgenhMj2YFqU7pSVWQpKukZ2mtrMhq53campgdz4XqNhY96VHnlJYeuo0OT3Llqhcv4KlwLm4Y0br8ba2lGoiS8z2fRoTmzoXOutf6Qb0By5q6DPw/q7ZcKtPeDoCa7yL2PG2uU5FSWpdB7nd6a/WK45/kTw) has the M on screen and then you an zoom toward it and see the black areas. 

![image](https://user-images.githubusercontent.com/924374/115180220-73432780-a118-11eb-9739-81ef68fee9da.png)
