### ISSUE TITLE
Unreal Marketplace Testing Failure on MacOS

### ISSUE THREAD

**Issue by shehzan10** [CesiumGS/cesium-unreal#365]
> Hello Cesium, 
> 
> This is a message to inform you of the result of the file update you recently submitted for your published product (Cesium for Unreal).
> 
> Status: Changes needed
> 
> While attempting to process your file update, we encountered the following errors:
> Mac
> 
> ```
> Undefined symbols for architecture x86_64:
>     "___darwin_check_fd_set_overflow", referenced from:
>     httplib::detail::SocketStream::is_readable() const in libCesiumIonClient.a(Connection.cpp.o)
>     httplib::detail::SocketStream::is_writable() const in libCesiumIonClient.a(Connection.cpp.o)
>     httplib::detail::keep_alive(int, long) in libCesiumIonClient.a(Connection.cpp.o)
>     httplib::Server::listen_internal() in libCesiumIonClient.a(Connection.cpp.o)
>     ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (
> ```
> 
> We ask that you resolve this issue and update your file link so that we can update your project to its newest version.
>  
> Thanks,
> Unreal Engine Marketplace Team

CC @kring @baothientran

**Comment by baothientran** [comment]
@shehzan10 do we know the MacOS and Xcode version they are using?

**Comment by shehzan10** [comment]
@baothientran I sent an email requesting the information and CC'ed you on it. Please copy any responses here for the record.

**Comment by shehzan10** [comment]
According to https://docs.unrealengine.com/en-US/WhatsNew/Builds/ReleaseNotes/4_26/index.html

> - macOS
> 	- Supported
> 		- macOS Big Sur 11.0.1, Latest Xcode 12
> 	- Recommended
> 		- macOS Catalina 10.15.7, Latest Xcode 12
> 	- Minimum
> 		- macOS Mojave 10.14.6, Xcode 11.3.1
> 	- Machine Architecture Note
> 		- Added preliminary support for native Apple Silicon for macOS targets*****
> 		- Some SDKs do not yet contain ARM64 slices (e.g. Steam, Vivox).

So we should probably use 11.3.1 on Travis (currently 11.4.1). @baothientran is testing whether it has the C++17 capabilities required for native and unreal.

According to [Xcode 11.3.1 has clang compiler 11.0.0](https://gist.github.com/yamaya/2924292#file-xcode-clang-vers-L322-L326), which supports [all C++17 features](https://en.cppreference.com/w/cpp/compiler_support#cpp17).
