### ISSUE TITLE
Allow users to choose a custom ellipsoid

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#366]
We should allow users to set a custom ellipsoid on the **CesiumGeoreference** instead of the default WGS84. I think the cesium-native calculations are agnostic of what ellipsoid is used, so this should be relatively easy. 

If someone from the community wants to give this a shot, look for all hard-coded references to `CesiumGeospatial::Ellipsoid::WGS84` in `CesiumGeoreference.cpp`. Each of these needs to be replaced with a reference to a custom `CesiumGeospatial::Ellipsoid` that should be configurable through a C++ setter. It should still default to using the `WGS84` ellipsoid if no other ellipsoid is set. You can have a look at the cesium-native source code ("CesiumGeospatial/Ellipsoid") to determine how to create the custom ellipsoid.

**Comment by javagl** [comment]
A crross-reference: This is related to (and, depending on the scope, might eventually be *part of*) the possible [Georeference refactoring](https://github.com/CesiumGS/cesium-unreal/issues/330)

**Comment by javagl** [comment]
Just stumbled over this, and to not overlook this:

> look for all hard-coded references to CesiumGeospatial::Ellipsoid::WGS84 in CesiumGeoreference.cpp.

There are also some functions in `cesium-native` that receive an `Ellipsoid` as their last parameter, with a *default* value of WGS84. These functions are currently called from `cesium-unreal`, *omitting* the last parameter. This has to be reviewed, to make sure that the configured ellipsoid is passed to these functions as well, to avoid accidentally using WGS84 at some point.

**Comment by aixinxindeyi** [comment]
u guys hava any approach to change the ellipsoid size?
