### ISSUE TITLE
Can't load from file:// URLs on Mac and Linux (or on any platform in UE 5.3!) because they are disabled in Unreal's libcurl

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#378]
According to a [question about loading tilesets from files under Linux](https://community.cesium.com/t/loading-tilesets-from-files-under-linux/13313) from the forum, there might be an issue with the current approach of loading tilesets using the standard `UnrealAssetAccessor`.

The `UnrealAssetAccessor` uses the `IHttpRequest` to resolve the requests. But under linux, it might be necessary to use an `IPlatformFile` for local file requests, because on Linux, the libcurl library that is used in Unreal Engine is compiled with the `file` protocol being disabled.

This behavior has to be verified. If this turns out to be a problem, then it might be easy to fix, by just checking the protocol of the URL, and either using an `IHttpRequest` or an `IPlatformFile`, roughly at https://github.com/CesiumGS/cesium-unreal/blob/3daac114185202a8ee28b058d1131b401bad37dd/Source/CesiumRuntime/Private/UnrealAssetAccessor.cpp#L131 

---

Edit: I think that it would be better in many ways to have the option to load local tilesets in `cesium-native` itself. This would essentially mean to move the https://github.com/CesiumGS/cesium-native/blob/main/Cesium3DTiles/test/SimpleAssetAccessor.h or the https://github.com/CesiumGS/cesium-native/pull/127/files#diff-43c4884466567e2f908defe62c8ba7921b5310694a2dcf3ec0501cbc5e520f9d from the "test" package into the actual `cesium-native` core. This would allow to create an `IAssetAccessor` that "dispatches" either to the current `UnrealAssetAccessor` or the `FileAssetAccessor`, depending on the protocol.

**Comment by kring** [comment]
Confirmed by looking at https://github.com/EpicGames/UnrealEngine/blob/c3caf7b6bf12ae4c8e09b606f10a09776b4d1f38/Engine/Source/ThirdParty/libcurl/BUILD.EPIC.sh#L694 that libcurl is built without support for files on Linux and Mac. 😩 Contrary to the claim at https://answers.unrealengine.com/questions/891666/libcurl-behavior-with-third-party-library.html, files _are_ supported on Windows.

I guess we probably won't have much luck convincing Epic to enable `file://` since they don't need it, so we'll need to implement our own file URL loading on these platforms, as Marco mentions above.

**Comment by javagl** [comment]
> so we'll need to implement our own file URL loading on these platforms,

One question is where this should take place. I.e. whether it is supposed to be implemented on Unreal side or native side (I'm strongly in favor of the latter, as already mentioned elsewhere). If there is some consensus about that, I could give it a try.

**Comment by kring** [comment]
It seems Epic has purposely made file URLs not work even on Windows in UE 5.3:
https://github.com/EpicGames/UnrealEngine/commit/8cf99a3ba95a6c79074825c7a7db4a572c5d8a16#diff-5af25202a26d69b795835d92dfec1588eb0c1aec18dcda4b01930c9075556d6dR30
(thanks for the reference @lolleko)

**Comment by javagl** [comment]
I don't have access to this repo (and might need a refresher for the relevant code in general 👴 ), but this sounds like it _could_ make a stronger case for being able to transparently do some 
```
if (isFile(url)) { use(new PlatformFile(url); }
else { use(new HttpRequest(url)); }
```
abstraction somewhere in the `*AssetAccessor` implementation. 


If a few lines of code in the implementation could simplify the life of developers who want to get started, that sounds like a sensible trade-off. I'm thinking about https://cesium.com/learn/unreal/unreal-datasets/#step-5-add-a-3d-tileset-from-a-local-directory , and the part after https://cesium.com/learn/unreal/unreal-datasets/#local-directory-filepath-formatting that are ... a nuisance for a **quick**start, and wouldn't even work on windows ans more *iff* support for files is dropped in UE5.3. entirely...

**Comment by lolleko** [comment]
Until this is resolved, I want to share my workaround for loading local tilesets. It's pretty simple. I just spin up a simple HTTP server in the tileset directory e.g. https://github.com/TheWaWaR/simple-http-server

This adds a tiny overhead because the files need to travel through the loopback interface on your network card after being loaded from the disk. However, it is still very fast, and in many cases, you probably can even measure the difference.

**Comment by javagl** [comment]
@lolleko That workaround is already described, but only as something that resembles a "footnote", in https://cesium.com/learn/unreal/unreal-datasets/#loading-assets-from-a-local-server . 

One could just move this section up (and maybe extend it a bit), to replace the instructions that are currently given in the section "Add a 3D Tileset from a local directory". (And this would probably not use the server that you linked to, but something with `npm install http-server` or ` python -m http.server`)

But ... 
- there are many good reasons why someone might want to load local files
- I think that it is important to make these first tutorial steps as easy as possible

<sub>Without diving into details: Everybody knows how important an ~"early feeling of success" can be, and how frustrating it can be to go thorugh a list of "Install this, install that, maybe you already have Node.js installed? Maybe you have Python? If so, which version?... 🙄"</sub>
