### ISSUE TITLE
Failed to load a tileset that loads in CesiumJS and has no obvious unsupported features

### ISSUE THREAD

**Issue by Llhai** [CesiumGS/cesium-unreal#386]
I am having trouble loading 3dtiles files using the cesium-unread plugin.

The error messages are as follows 
``
LogCesium: Error: [2021-04-27 11:13:40.730] [error] [GltfContent.cpp:32] Failed to load binary glTF from file:///C:/Users/hust/Desktop/cesium_data/MyTest/Tile_Osgb_0.b3dm: - JSON parsing error at byte offset 1283: Parsing was terminated
``

The data is converted from osgb, and the conversion tool is [https://github.com/fanvanzh/3dtiles](url)
It can be loaded successfully by cesium.js, But not on UE4 
![image](https://user-images.githubusercontent.com/26406508/116180990-6348ca80-a74c-11eb-85d3-a4accf9c6f2d.png)

**Comment by kring** [comment]
@Llhai is it possible for us to access the tileset to debug?

**Comment by Llhai** [comment]
Thanks, but sorry, I can't provide model files, I have solved the question，the problem is caused by my format conversion tool.

**Comment by MiratPH** [comment]
@Llhai 
Hello, I'm facing similar problems. Could you please tell me some detail about what's wrong with your format conversion tool? Thanks.

**Comment by Llhai** [comment]
@MiratPH You can try to use **cesiumlab2** to convert your model format
