### ISSUE TITLE
Credit screen sometimes shows the Cesium website

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#391]
When pressing "Play", and clicking the "Data Attribution" immediately after that, the credit screen sometimes shows `http://cesium.com`:

![CesiumUnreal Credits](https://user-images.githubusercontent.com/5597569/116473973-2f6ac380-a878-11eb-975d-4f6166a6614e.png)

(It's not sooo hard to reproduce, but may require 2 or 3 attempts. with race That's the conditions! problem)

From a quick look at the widget, `cesium.com` is used as a "default/dummy" URL for the webbrowser component, and this is only "overruled" by an update of the credits (i.e. by setting the actual HTML contents), which may not have happened yet when it is opened "immediately".

Approaches for solving could be 1. using a blank page as default instead, or 2. somehow making sure that the update of the credits is triggered always (at least once) after making the widget visible (or both...)

**Comment by kring** [comment]
This was fixed in the last round of credits improvements.
