### ISSUE TITLE
Fatal error on packaged game startup

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#399]
I am currently building an application with Cesium for Unreal. When loading from the main menu to the persistent level that contains the Cesium actors and 3DTiles, I am getting the following error:
```
---------------------------
The UE4-CesiumForUnreal_C2RDemo Game has crashed and will close
---------------------------
Assertion failed: EffectiveSize == (uint32)MipMap.BulkData.GetBulkDataSize() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Engine/Private/Rendering/Texture2DResource.cpp] [Line: 212] 
Texture 'Texture2D_2147482455', mip 1, has a BulkDataSize [65536] that doesn't match calculated size [16384]. Texture size 256x256, format 71
```
I am getting this error about half a second after entering the world, and the 3D tiles hadn't started showing up on my screen yet.

Does anyone have an idea of what's going on here?

**Comment by nithinp7** [comment]
Does this happen on `main` too or just `frankenwater`?

**Comment by xuelongmu** [comment]
I was seeing the issue on `frankenwater` branch. The issue was resolved with the following commits, thanks @nithinp7 
On `watermask` (will eventually be merged to master): https://github.com/CesiumGS/cesium-unreal/pull/338/commits/f6978fb440bb2de3d0c1ae6505db17f06b7f1a82

On `frankenwater` https://github.com/CesiumGS/cesium-unreal/commit/c9d8c5a9bd907e2c5bbe8715ed8d2967f1b2f975
