### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by b0b023** [CesiumGS/cesium-unreal#403]
System: Ubuntu 18.04 with manually upgraded cmake to version 3.20.2

Following the linux build instructions in README.md I get the following error:

```
-- The CXX compiler identification is Clang 10.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/ue4/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:18 (add_subdirectory):
  The source directory

    /home/ue4/cesium-unreal/extern/cesium-native

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:24 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  cesium-native-tests
```
Any ideas what went wrong here?

**Comment by kring** [comment]
It looks like you haven't cloned the cesium-native submodule. Did you clone cesium-unreal from github with `git clone --recursive git@github.com:CesiumGS/cesium-unreal.git`? That `--recursive` is very important.

If that doesn't fix it, can you please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10)? We try to use GitHub exclusively for bug reports and feature requests.

**Comment by b0b023** [comment]
oops - you were right. Sorry about that and thanks for the quick reply!
