### ISSUE TITLE
Fix water mask vs only-land rendering discrepancy 

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#406]
When a tile only has land, the `GltfMaterialWithRasterOverlay` material, that uses the "default lit" shading model, is used. When the tile only has water or has partial water and partial land, the `GltfMaterialWithRasterOverlayAndWater` material, that uses the "single-layer water" shading model, is used. As seen in the below picture, currently the land part of water mask tiles do not render the same as the only-land tiles. I think this is due to the differences in shading models, but there may be a way to tweak settings in the water material to get rid of this difference. If such a setting is not possible, it will probably be best to do two render passes on partial-land, partial-water tiles so that both the land and water get rendered correctly.

![image](https://user-images.githubusercontent.com/924374/116856338-5b9e8f80-ac3e-11eb-8a36-1bfca0633126.png)

**Comment by kring** [comment]
@nithinp7 is this fixed? I don't see it anymore.

**Comment by nithinp7** [comment]
I think this was fixed by the new water material that @argallegos made since it no longer used the "single layer water" shader model.
