### ISSUE TITLE
Cesium New Update closes the editor 

### ISSUE THREAD

**Issue by Humbertlsk** [CesiumGS/cesium-unreal#407]
Cesium New Update closes the editor after opening a project, I deleted the plugin and the projects loads fine.

**Comment by baothientran** [comment]
@Humbertlsk, do you have the log for the crash? is it still happening

**Comment by Humbertlsk** [comment]
It just closes, no crash window pops up u.u

**Comment by baothientran** [comment]
Hi @Humbertlsk, can you also check in your project directory, if there is a directory `C:\Users\bao\Documents\Projects\cesium-unreal-samples\Saved\Logs`, it may have a log for the latest run?

**Comment by baothientran** [comment]
Also is it happening on Window platform currently?

**Comment by Humbertlsk** [comment]
Yea it is windows, but I used to have no problem with the plugin. I attached log file 
[WorldComp_4_26-backup-2021.05.04-17.59.15.log](https://github.com/CesiumGS/cesium-unreal/files/6423409/WorldComp_4_26-backup-2021.05.04-17.59.15.log)

**Comment by kring** [comment]
@Humbertlsk can you confirm that `C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\CesiumForUnreal` (or equivalent) exists and has files, including a `CesiumForUnreal.uplugin` file? It might be worthwhile to try uninstalling and reinstalling the Cesium for Unreal plugin, just to see if that helps.

**Comment by jamietelford** [comment]
[NPW2A_509588.log](https://github.com/CesiumGS/cesium-unreal/files/6424736/NPW2A_509588.log)

@kring attached is the log from my editor session..  as per my comment back in the forum..  when i ran a insights session with cmd line -game switch it ran without issue.. only occurs on a pure editor session... after everything is loaded.   I've rolled back to 1.1.1 which is working..

**Comment by javagl** [comment]
The common element between the `utrace` and the log file seems to be the part
``` 
[2021.05.04-17.57.37:510][  0]LogPackageName: Error: DoesPackageExist: DoesPackageExist FAILED: '/CesiumForUnreal/CesiumCreditSystemBP' is not a standard unreal filename or a long path name. Reason: La ruta no comienza con una raíz válida. La ruta debe comenzar por: '/Engine/', '/Game/', '/MegascansPlugin/', '/Paper2D/', '/RigLogic/', '/OpenColorIO/', '/AnimationSharing/', '/Niagara/', '/AxFImporter/', '/DataprepEditor/', '/DatasmithContent/', '/StaticMeshEditorExtension/', '/ChaosClothEditor/', '/ChaosNiagara/', '/ChaosSolverPlugin/', '/ControlRig/', '/GeometryCollectionPlugin/', '/GeometryProcessing/', '/Landmass/', '/MeshModelingToolset/', '/ModelingToolsEditorMode/', '/MotoSynth/', '/PythonScriptPlugin/', '/MagicLeap/', '/UIWS/', '/Water/', '/MagicLeapPassableWorld/', '/MovieRenderPipeline/', '/SequencerScripting/', '/AudioSynesthesia/', '/HairStrands/', '/HDRIBackdrop/', '/PostSplashScreen/', '/Synthesis/', '/SunPosition/', '/Takes/', '/MediaCompositing/', '/GeometryMode/', '/GLTFImporter/', '/MeshEditor/', '/SpeedTreeImporter/', '/OculusVR/', '/SteamVR/', '/Engine/DataprepEditor/Transient/', '/Engine/DataprepCore/Transient/', '/Config/', '/Script/', '/Extra/', '/Memory/', or '/Temp/'
[2021.05.04-17.57.37:510][  0]LogLinker: Warning: [AssetLog] B:\Documentos\Modelos 3d\Unreal Engine\WorldComp_4_26\Content\BodegasCartagena.umap: Failed to load '/CesiumForUnreal/CesiumCreditSystemBP': Can't find file.
...
[2021.05.04-17.57.37:846][  0]LogLinker: Warning: [AssetLog] B:\Documentos\Modelos 3d\Unreal Engine\WorldComp_4_26\Content\BodegasCartagena.umap: Failed to load '/CesiumForUnreal/FloatingPawn': Can't find file.
[2021.05.04-17.57.37:846][  0]LogLinker: Warning: [AssetLog] B:\Documentos\Modelos 3d\Unreal Engine\WorldComp_4_26\Content\BodegasCartagena.umap: Failed to load '/Script/CesiumRuntime': Can't find file.
```

(The part "La ruta no comienza con una raíz válida. La ruta debe comenzar por:" in the trace is "Path does not start with a valid root. Path must begin with ...". Unrelated: There's certainly a *very* good reason why it's impossible (or at least, not obvious how) to Copy+Paste a line from the log of an utrace in UnrealInsights, but I cannot imagine what that reason could be).

So something seems to be off with the path information. My guess is that the prefixes that are mentioned there (`'/Niagara/', '/AxFImporter/'...`) are the "known plugins", and `CesiumForUnreal` is not mentioned there, FWIW. There are no apparent changes in the `uplugin` between 1.1.1 and 1.2.0, except for the version update and the added `Linux` part (which should not affect the Windows build).

**Comment by tiagomagalhaes** [comment]
I think I'm encountering the same issue.
Nothing that looks relevant is coming up in the log but if I run the editor with a debugger attached an exception is thrown inside the CesiumGeometry::Plane constructor.

`abort 0x00007ffe83c6286e
terminate 0x00007ffe83c61f9f
_is_exception_typeof 0x00007ffe7b793094
_is_exception_typeof 0x00007ffe7b794024
__CxxFrameHandler3 0x00007ffe7b79f911
__chkstk 0x00007ffe85d3207f
RtlRaiseException 0x00007ffe85ce1454
KiUserExceptionDispatcher 0x00007ffe85d30bae
RaiseException 0x00007ffe838f4b59
_CxxThrowException 0x00007ffe7b796480
CesiumGeometry::Plane::Plane(glm::vec<3,double,0> const &,double) 0x00007ffda408698c
Cesium3DTiles::createCullingVolume(glm::vec<3,double,0> const &,glm::vec<3,double,0> const &,glm::vec<3,double,0> const &,double,double) 0x00007ffda408409f
Cesium3DTiles::ViewState::create(glm::vec<3,double,0> const &,glm::vec<3,double,0> const &,glm::vec<3,double,0> const &,glm::vec<2,double,0> const &,double,double,CesiumGeospatial::Ellipsoid const &) 0x00007ffda4016c8c
ACesium3DTileset::CreateViewStateFromViewParameters(const FVector2D &,const FVector &,const FRotator &,double) 0x00007ffda3feae07
ACesium3DTileset::Tick(float) 0x00007ffda3ff41bd
AActor::TickActor(float,ELevelTick,FActorTickFunction &) Actor.cpp:1091
FActorTickFunction::ExecuteTick(float,ELevelTick,Type,const TRefCountPtr<FGraphEvent> &) Actor.cpp:173
FTickFunctionTask::DoTask(Type,const TRefCountPtr<FGraphEvent> &) TickTaskManager.cpp:284
TGraphTask<FTickFunctionTask>::ExecuteTask(TArray<FBaseGraphTask *,TSizedDefaultAllocator<32> > &,Type) TaskGraphInterfaces.h:886
FNamedTaskThread::ProcessTasksNamedThread(int,bool) TaskGraph.cpp:709
FNamedTaskThread::ProcessTasksUntilQuit(int) TaskGraph.cpp:600
FTaskGraphImplementation::WaitUntilTasksComplete(const TArray<TRefCountPtr<FGraphEvent>,TInlineAllocator<4,TSizedDefaultAllocator<32> > > &,Type) TaskGraph.cpp:1524
FTickTaskSequencer::ReleaseTickGroup(ETickingGroup,bool) TickTaskManager.cpp:563
FTickTaskManager::RunTickGroup(ETickingGroup,bool) TickTaskManager.cpp:1577
UWorld::RunTickGroup(ETickingGroup,bool) LevelTick.cpp:781
UWorld::Tick(ELevelTick,float) LevelTick.cpp:1576
UEditorEngine::Tick(float,bool) EditorEngine.cpp:1526
UUnrealEdEngine::Tick(float,bool) UnrealEdEngine.cpp:423
FEngineLoop::Tick() LaunchEngineLoop.cpp:4830
GuardedMain(const wchar_t *) Launch.cpp:171
WinMain(HINSTANCE__ *,HINSTANCE__ *,char *,int) LaunchWindows.cpp:257
__scrt_common_main_seh() 0x00007ff666117ffa
BaseThreadInitThunk 0x00007ffe84c27034
RtlUserThreadStart 0x00007ffe85ce2651`

**Comment by kring** [comment]
Thanks @tiagomagalhaes. That looks like it might be a separate issue, but it's useful nonetheless. Is there something unusual about your (initial) camera so that Cesium would be unable to compute planes for its view frustum? Also, is this a shipping build, or is it a crash in the editor like other folks were seeing? I ask because it seems from your call stack that an exception is causing the application to terminate, and that usually only happens in Shipping builds with exceptions disabled.

**Comment by tiagomagalhaes** [comment]
Hi @kring. Want me to open a separate issue?
In any case, don't think the camera is in an invalid location, before updating the Cesium plugin I was able to open this project fine.
And it's not a shipping build, this happens while running inside the editor, in the stack trace above the engine running is `UUnrealEdEngine::Tick(float,bool) UnrealEdEngine.cpp:423`.
But cesium-native is distributed as release only, maybe that's why it's acting like this?

**Comment by kring** [comment]
No need to open a separate issue, but by any chance can you share you share a project with us that exhibits this problem? That would be very helpful for debugging it.

You're right that cesium-native is release only, but that project is compiled with exceptions enabled so throwing an exception there shouldn't immediately kill the process. But if the exception escapes all the way to Engine code it probably will.

**Comment by tiagomagalhaes** [comment]
Unfortunately it's not quite feasible to share the project, this is an integration test with a larger proprietary project.
And trying to extract the offending part isn't easy because the bug itself crashes the editor when I open the map itself. =)

Right now I'm switching from the Marketplace version of the plugin to linking up your github and running against a locally compiled cesium-native with more debug options. Hoping this will let me give you more insight into what's going on.

Looking at cesium-native source and the stack trace I pasted above it looks like this check in the Plane constructor is being hit
```
if (!Math::equalsEpsilon(glm::length(normal), 1.0, Math::EPSILON6)) {
    throw std::invalid_argument("normal must be normalized.");
}
```
and the exception gets bubbled all the way up to windows.

**Comment by tiagomagalhaes** [comment]
Somehow, the unrealWorldToTileset for world terrain tileset is ending up as NaN for all members of the matrix which then screws up any calculations downstream.
Camera could be quite far away from world origin but it did not outright crash before. I did get some warnings about it in Unreal's message log.

**Comment by tiagomagalhaes** [comment]
Rolled back to tag 1.1.1 and it loaded fine.
Camera is not far away from terrain after all.

Currently have to get a few things going so I'll keep using this version for a few days but will try to gather more information for you nest week. =)

**Comment by tiagomagalhaes** [comment]
Tried moving to (9c44582 - Merge pull request #410 from CesiumGS/constrain-user-input), **master** as of the 17th and I'm no longer getting the problem that was failing on Plane constructor.

**Comment by baothientran** [comment]
@Humbertlsk a new version 1.2.1 is released a couple weeks ago, do you still encounter the issue?

**Comment by baothientran** [comment]
since no ones has reported the problem again, I close the issue for now. If it happens again, please feel free to re-open it
