### ISSUE TITLE
Investigate compatibility with sky plugins

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#413]
There has been interest on the forums in increased compatibility with plugins like TrueSky, e.g. making CesiumSunSky share its directional light with these other systems. It may be good to research how these other plugins work and if it is straightforward to better expose the directional light in Cesium SunSky.

TrueSky, for example, references a directional light in the scene. CesiumSunSky has a directional light component as part of the blueprint. It would involve changing the base SunSky functionality somewhat, but it may be possible to modify CesiumSunSky so that it also references a directional light in a scene, rather than its own directional light component.

**Comment by WellyWonder** [comment]
Yes please

**Comment by WellyWonder** [comment]
Any chance for a tutorial or just advice on how to to modify CesiumSunSky so that it also references a directional light in a scene?

**Comment by argallegos** [comment]
Hi @WellyWonder,

We are currently working on a tutorial that covers CesiumSunSky in detail. In the meantime, I tested out a few things and I was able to modify CesiumSunSky to use a scene directional light instead. You can find those changes in [this branch](https://github.com/CesiumGS/cesium-unreal/tree/refactor-sunsky). 
This may be merged into main and included in a future release soon, but I haven't done thorough testing yet so I'm not sure what the timeline on that would look like. 

If you want to replicate the changes yourself, here's what I did:

- Added two new editor variables, a boolean and a Directional Light Object Reference. You can create a directional light in the scene and assign it to the Level Directional Light object reference.
![image](https://user-images.githubusercontent.com/39537389/119851106-23f0d380-bedc-11eb-82ad-dbefce1e5399.png)
- In the Construction Script, add a branch to turn off and on the directional lights based on which one you'd like to use
![image](https://user-images.githubusercontent.com/39537389/119851420-61edf780-bedc-11eb-8fed-77b52f597fe6.png)
- In the Update Sun function, "Orient Sun and Directional Light" section, add a Select node to pick between the two directional lights and replace the original directional light reference. All the nodes above the comment box were added for this.
![image](https://user-images.githubusercontent.com/39537389/119851719-a37ea280-bedc-11eb-8101-9fc3107013ec.png)

Please let me know if this works for you!
