### ISSUE TITLE
Linker error on Ubuntu 18.04

### ISSUE THREAD

**Issue by paricaud9** [CesiumGS/cesium-unreal#418]
I’m trying to set up cesium-native as an external project of an existing cmake project, for then CesiumForUnreal to use. It’s working fine for Windows, but I ran into some issues on Ubuntu 18.04. I’m currently using:
- c++17
- clang++10
- libc++ (specified through -DCMAKE_CXX_FLAGS=-stdlib=libc++)
- cesium-native v0.3.0
- cesium-unreal v1.2.0

I got cesium-native to successfully build, however when consuming it in the Unreal plugin I bump into some errors when linking 
```
…
[6/10] Compile Module.CesiumRuntime.gen.cpp 
[7/10] Compile Module.CesiumRuntime.cpp 
[8/10] Compile Blocks.cpp 
[9/10] Link (lld) Blocks-Linux-DebugGame 
ld.lld: error: undefined symbol: reallocarray 
>>> referenced by UriMemory.c:99 (/__w/396/s/build/linux64/Debug/_deps/cesium-native/src/cesium-native/extern/uriparser/src/UriMemory.c:99) 
>>> UriMemory.c.o:(uriDefaultReallocarray) in archive /__w/396/s/unreal/Blocks/Plugins/CesiumForUnreal/Source/ThirdParty/lib/Debug/liburiparser.a 
clang++: error: linker command failed with exit code 1 (use -v to see invocation) 
```

**Comment by kring** [comment]
@paricaud9 the "developing" instructions show how to build cesium-native so that it works with Cesium for Unreal on Linux:
https://github.com/CesiumGS/cesium-unreal#computer-developing-with-unreal-engine

At a glance, it looks like maybe you need to use the supplied toolchain file: https://github.com/CesiumGS/cesium-unreal/blob/main/extern/unreal-linux-toolchain.cmake

I'm closing this because I don't think there's any action here, but if you have followup questions the best place is probably the [Community Forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by kring** [comment]
@paricaud9 I'll reopen this to help you get it resolved.

Just as background, `reallocarray` is only used in liburiparser.a when the preprocessor definition `HAVE_REALLOCARRAY` is set. That shouldn't happen if CMake (correctly) detects that the Unreal C++ toolchain doesn't have this function.

Some things to check: 
* Use the `CMakeLists.txt` in the `cesium-unreal/extern` directory as the primary CMake project for cesium-native when you plan to use it with Unreal Engine, _not_ the one in `cesium-unreal/extern/cesium-native`.
* Set the `UNREAL_ENGINE_COMPILER_DIR` environment variables as specified in the README:
```
    export UNREAL_ENGINE_DIR=<path_to_unreal_engine>
    export UNREAL_ENGINE_COMPILER_DIR=$UNREAL_ENGINE_DIR/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu
    export UNREAL_ENGINE_LIBCXX_DIR=$UNREAL_ENGINE_DIR/Engine/Source/ThirdParty/Linux/LibCxx
```
* Verify that the directories referenced in `UNREAL_ENGINE_COMPILER_DIR` and `UNREAL_ENGINE_LIBCXX_DIR` actually exist!
* Delete `cesium-unreal/extern/build` after changing any of the above! Some of this, if it was wrong initially, won't be fixed just by re-running the configure.
* Specify the toolchain file when running the CMake configure step:
```
cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="unreal-linux-toolchain.cmake" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
```

Also, our official plugin package includes a built for Linux, now. So if you just want to use Cesium for Unreal on Linux, there's no reason to compile it yourself.

**Comment by kring** [comment]
I'm closing this again, but @paricaud9 please reopen it if we can help further.
