### ISSUE TITLE
Add methods to set georeference origin directly from ECEF

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/cesium-unreal#432]
Possibly a duplicate, as this is marked `TODO` in [this line](https://github.com/CesiumGS/cesium-unreal/blob/9d5d4638a5ad0348b1ee180b1bdeede151782886/Source/CesiumRuntime/Public/CesiumGeoreference.h#L562).

`ACesiumGeoreference` has these methods:

```
SetGeoreferenceOrigin(const glm::dvec3& TargetLongitudeLatitudeHeight)
InaccurateSetGeoreferenceOrigin(const FVector& TargetLongitudeLatitudeHeight);
```

It would be helpful for it to also have methods like these:

```
SetGeoreferenceOrigin(const glm::dvec3& TargetEcef)
InaccurateSetGeoreferenceOrigin(const FVector& TargetEcef);
```

**Comment by kring** [comment]
These two methods have identical parameters, so they'll need different names. Let's rename `SetGeoreferenceOrigin` to `SetGeoreferenceOriginLongitudeLatitudeHeight` (which will make it match the getter, interestingly enough), and same for the Inaccurate version. And then introduce a new `SetGeoreferenceOriginEcef`. Finally, for backward compatibility, let's reintroduce `SetGeoreferenceOrigin` and make it call `SetGeoreferenceOriginLongitudeLatitudeHeight` after logging a warning. We'll also need a CoreRedirect for Blueprints for the Inaccurate version.
