### ISSUE TITLE
3D Tiles disappearing on property change

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#433]
When editing a property at editor-time or run-time, the entire tileset will sometimes disappear from view. Other times, tiles will pop in but others will not fully load, resulting in large unloaded areas.

Video here: https://drive.google.com/file/d/1f27XwyUAjEF4VBdsCOGJzadGsLIsGukK/view?usp=sharing (verbose logs enabled)

**Comment by baothientran** [comment]
I can't reproduce the issue. Does it happen with an empty project?

**Comment by xuelongmu** [comment]
I did some testing and it doesn't seem to happen on master, only my branch https://github.com/CesiumGS/cesium-unreal/pull/430

I had thought it was something unrelated to my changes, but I guess I was responsible for it. Going to comb through my code...

**Comment by xuelongmu** [comment]
Fixed the issue. I had overriden `PostEditChangeProperty` without calling its parent `Super::PostEditChangeProperty`. Silly me 😄
