### ISSUE TITLE
Make Cesium content easily discoverable

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#437]
<sup>This could be considered as a "generalization" of https://github.com/CesiumGS/cesium-unreal/issues/277</supe>

Right now, certain elements do not appear in the content browser. The **Quick**(!)Start provides elaborate guidance at https://cesium.com/docs/tutorials/cesium-unreal-quickstart/#step-3-add-sunsky-lighting-and-a-floatingpawn : ~*"Click here, check there, look, like this image, search for this, change this setting, ignore most of the information that you're flooded with, scroll around, until you find that name"*. We should not force newbie users to go through this procedure (to cover up for our lack of understanding of what's wrong).

We should investigate what is necessary for objects to appear in the "Place Actors" panel. This might already be sufficient. 

As an additional step, we could consider extending the Cesium "Quick Add" panel. Right now, the "CesiumForUnreal" root folder in the Content Browser contains ~20 elements, among them being things like a "PointInBox", a "transparent1x1" image, the profiling blueprint. The C++ classes contain important things like the Tileset, but also things like the "Globe Anchor Parent" (what is that? what is it used for?). 

Having the *important* classes/elements that are necessary to build a level directly in the "Quick Add" panel (maybe as some sort of "small 'content browser'", but with the option to add some explanatory text) could make things **much** more useable (as indicated by the tutorials that could be *much* shorter...).

**Comment by argallegos** [comment]
It would be really nice to have a few actors (CesiumSunSky, DynamicPawn at the very least) available in the Quick Add panel. If that is relatively straightforward, it would be great to add. If not, there may be a way to force the objects to appear in the Place Actors panel - I agree that the current process is too complicated to add actors like that.

**Comment by kring** [comment]
It should be really easy to add this to the Cesium panel. The hardest part is deciding where to put the buttons.

**Comment by kring** [comment]
Fixed in #451.
