### ISSUE TITLE
The node's transform in b3dm is invalid

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#449]
There are multiple grids and multiple nodes in b3dm in 3dtiles, and its transformation becomes 0, 0, 0, which is invalid

**Comment by kring** [comment]
Sorry, I don't know what you mean, Can you elaborate?

**Comment by kak0na** [comment]
The translation, rotation, and scale in the nodes node under Gltf seem to be invalid

**Comment by baothientran** [comment]
Hi @kak0na, if possible, can you share the asset so that we can take a look into it?

**Comment by kak0na** [comment]
https://user-images.githubusercontent.com/37468607/119425182-7cd43680-bd39-11eb-9948-90d2ef37a940.MP4

Change the suffix to 7z

**Comment by kak0na** [comment]
https://we.tl/t-vDwajkrWcB

**Comment by kak0na** [comment]
@baothientran

**Comment by xosg** [comment]
@kring

**Comment by xosg** [comment]
so many glTF features don't work at all！

**Comment by kring** [comment]
Sorry it took so long to look at this @kak0na, but the the link above has expired. I think it's very likely this was fixed by #397, though. Please reopen this issue if you're still experiencing this problem.
