### ISSUE TITLE
Deprecate FloatingPawn and CesiumGlobeAnchorParent

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#450]
Create deprecation warnings for `FloatingPawn` and `CesiumGlobeAnchorParent` for the next release; they will be removed at some future date.

`FloatingPawn` will be removed, `DynamicPawn` will be renamed to `CesiumFloatingPawn` and set as the default pawn in all documentation.

`CesiumGlobeAnchorParent` is a class that is somewhat redundant, its functionality can be replicated by creating a dummy actor class, attaching a `CesiumGeoreferenceComponent`, and parenting a collection of normal UE4 actors to that actor. This enables groups of actors to be globe-aware (i.e. adjust their positions on-the-fly to be accurate relative to a double-precision ECEF coordinate space) without needing each individual actor to have a `CesiumGeoreferenceComponent`.

**Comment by javagl** [comment]
Just as a small "heads-up" (and apologies if this is obvious): Some `/* comments */` in `CesiumGeoreference.h` refer to `CesiumGlobeAnchorParent`. This should be updated accordingly.

**Comment by xuelongmu** [comment]
Just wanted to create some notes for future reference after creating this PR:

Using the DEPRECATED UClass macro will remove an actor from showing up in the content browser, the class browser when creating a child class, and the class selection menu in blueprints. Basically anywhere you search for all classes, it will no longer appear.

If a user already had a `CesiumGlobeAnchorParent` in their level, the MapCheck will generate the following warning:
`CesiumGlobeAnchorParent_1 /Game/Denver.Denver:PersistentLevel.CesiumGlobeAnchorParent_1 : Obsolete and must be removed! (Class is deprecated)`

For FloatingPawn, there's a "Deprecate" checkbox in the Class Settings menu, under Class Options -> Advanced (click the down arrow). The blueprint will subsequently fail to compile and seems to break gameplay logic that relies on it (e.g. I possessed a FloatingPawn and couldn't see any 3D Tiles).

**Comment by javagl** [comment]
Just to confirm this: The usual path to obtain overlays is via the `UCesiumIonRasterOverlay`. But the `UCesiumBingMapsRasterOverlay` and `UCesiumTileMapServiceRasterOverlay` should still be available, right? 

(The point is: The reason to **not** also deprecate these classes is that they can be used for custom-hosted data, that is not available on Cesium ion)
