### ISSUE TITLE
Sublevels cannot be removed after being added once

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#470]
<sup>(I tried this out in a branch with several changes, and would have to verify it in `master`, but am reasonably sure that it is also the case there)</sup>

When follwing the description from https://cesium.com/docs/tutorials/cesium-unreal-050-sublevels/ , one step consists of hitting the "Check for New Sublevels" button, which calls [`CesiumGeoreference::CheckForNewSubLevels`](https://github.com/CesiumGS/cesium-unreal/blob/670cbe9e922290d41608a8160e6a8387bc87fb3d/Source/CesiumRuntime/Private/CesiumGeoreference.cpp#L167). From a first test, it seems like the levels cannot be _removed_ after they have been added once. (I.e. when deleting a level in the "Levels" panel, pressing this button will not remove it from the list). This is "confirmed", to some extent, by the fact that `CesiumSubLevels.Add` is called, but the code does not appear to contain any "clear" or "remove" call.

---

An aside: I'm currently doing some experiments in the context of https://github.com/CesiumGS/cesium-unreal/issues/330 , based on https://github.com/CesiumGS/cesium-unreal/pull/459 , and as part of that, tried to better isolate the sublevel handling. As one tiny part of that, I tried to "automate" the handling insofar that it should not be necessary to press the "Check For New Sublevels" button manually, by adding some delegates along the lines of

    FWorldDelegates::LevelAddedToWorld.AddUObject(this, &ACesiumGeoreference::OnLevelAdded);
    FWorldDelegates::LevelRemovedFromWorld.AddUObject(this, &ACesiumGeoreference::OnLevelRemoved);

I still have to get a better understanding of the sublevel handling in UE, e.g. better understand the concept of "Layers", or the state transitions that levels go though when loading them. But **iff** this is roughly the right approach, I'll try to maintain the right set of sublevels list anyhow. (Whether or not the sublevels will be stored directly in the GeoRef in the future is another question that is still TBD).

**Comment by javagl** [comment]
Just to keep a record here for the person who looks at this next:

There had been attempts to address this:

- Change the function that updates the sublevels, so that the levels that are stored in the `CesiumSublevels` property of the Georeference always match the `world->GetStreamingLevels`
- (Optionally) on top of that: Use `FWorldDelegates::LevelAddedToWorld/LevelRemovedFromWorld` to call this updating function automatically

This approach suffered from the fact that the `world->GetStreamingLevels` contains only the sublevels that are currently "loaded". But a level should not be removed from the `CesiumSublevels` when it is _unloaded_, but only when it is really _deleted_. 

For now, a fix of this issue (that was attempted in the context of the Georeference refactoring) is deferred, and the current behavior is maintained until the exact meaning of the terms "loaded", "deleted", "added", "removed" etc. has been figured out.

**Comment by kring** [comment]
This is no longer an issue.
