### ISSUE TITLE
“Water” is unuseful.

### ISSUE THREAD

**Issue by shanshan1405** [CesiumGS/cesium-unreal#478]
I download CesiumForUnreal v1.3.0 and put it into Plugins folder of project, then build it. Unfortunately, I cannot built it successfully and show this error as follow:
![image](https://user-images.githubusercontent.com/57471768/120761985-5a67c780-c548-11eb-9036-c1ebade71084.png)
Then, i change the "Water" property "Enabled" to "false", project can built successfully, however, i couldnot see the change about the effect about water tiles. 
I wanna know how to change it or where i can find the plugin "Water" i couldn't find it in marketplace or Plugins. BTW, my UnrealEngine version is 4.26, i use CesiumForUnreal version v1.3.0.
In addtion, i find somebreak points in somewhere and i don't know what i should do, for example:
![image](https://user-images.githubusercontent.com/57471768/120764855-2e017a80-c54b-11eb-92f2-82056fd7a212.png)

**Comment by kring** [comment]
@shanshan1405 the water plugin should be included with the Engine:
![image](https://user-images.githubusercontent.com/924374/120765801-eab00780-c55c-11eb-92e1-05b49f46578d.png)

Can you check if it's there on your system, under Edit -> Plugins, and maybe just not enabled for some reason?

**Comment by shanshan1405** [comment]
Yes, i know how to find plugins, however, i have a confusion why i have nothing about the plugin "Water":
![image](https://user-images.githubusercontent.com/57471768/120766841-33f85b00-c54d-11eb-9fd3-da2306c40cd9.png)

**Comment by shanshan1405** [comment]
@kring Yes, i know how to find plugins, however, i have a confusion why i have nothing about the plugin "Water":
![image](https://user-images.githubusercontent.com/57471768/120767752-11b30d00-c54e-11eb-9100-d2871b7f7e54.png)

**Comment by kring** [comment]
I don't know. This page makes it sound like it should just be there in 4.26:
https://docs.unrealengine.com/4.26/en-US/BuildingWorlds/Water/
For lack of something better to try, you could try reinstalled Unreal Engine. Alternatively, maybe ask the question of Epic on the UE4 AnswerHub or UDN?

**Comment by shanshan1405** [comment]
@kring OK. I'll try to find how to solve this problem.

**Comment by shanshan1405** [comment]
@kring It's my fault, maybe i delete the "Water" some day. Now it's not a question. Thank you.

**Comment by kring** [comment]
ok, glad you were able to figure it out @shanshan1405.
