### ISSUE TITLE
Improve default shadowing and exposure settings

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#484]
Based on Alban's helpful feedback, some of the default shadow and exposure settings can be tweaked for better, more accurate visuals.

### Dynamic Shadow Distance
![image](https://user-images.githubusercontent.com/10490807/121083864-f21a1f80-c7ad-11eb-9e00-bad58b156a2b.png)
_Default Dynamic Shadow Distance of 200m (20,000 unreal units)_

![image](https://user-images.githubusercontent.com/10490807/121083950-0fe78480-c7ae-11eb-9335-1489c6a0d193.png)
_Increasing distance to 800m_

![image](https://user-images.githubusercontent.com/10490807/121084008-25f54500-c7ae-11eb-8698-c7b8faf62e20.png)
_Grand Canyon looks better with 5000m_

### Dynamic Shadow Distribution Exponent
![image](https://user-images.githubusercontent.com/10490807/121084319-84babe80-c7ae-11eb-83bc-e8e728840c23.png)
_Building shadows with the default distribution exponent of 1.4._

![image](https://user-images.githubusercontent.com/10490807/121084411-9d2ad900-c7ae-11eb-95d6-fe29c74de8e2.png)
_Increasing to 2.0 gives more realistic shadows for hard edges from a point source._

### Minimum Exposure
This requires adding a PostProcessVolume with infinite extent in the level. In the case that we don't want to bundle another uasset with the plugin, we could document this somewhere in a tutorial.

![image](https://user-images.githubusercontent.com/10490807/121084781-1296a980-c7af-11eb-875a-bf851a548470.png)
_Default exposure in shadowed area with no minimum EV. Sunlit areas are over-exposed and have clipped highlights._

![image](https://user-images.githubusercontent.com/10490807/121084689-f6930800-c7ae-11eb-80ca-3e63554db660.png)
_Minimum EV set to 13.0 using infinite post process volume._

**Comment by shehzan10** [comment]
@xuelongmu Are these settings that go in the plugin, or for example, Cesium for Unreal Samples and/or the Unreal Projects?

**Comment by xuelongmu** [comment]
@shehzan10 First two settings can simply go in CesiumSunSky in the plugin. The latter can probably go in Samples, unless we want to create something like CesiumPostProcess for the plugin.

**Comment by shehzan10** [comment]
> The latter can probably go in Samples, unless we want to create something like CesiumPostProcess for the plugin.

Can you open a corresponding issue in Samples (mark it good first issue)? I think the number of settings and artistic tuning probably means that we shouldn't do it in CesiumPostProcess.

We should also add it to the tutorials.

**Comment by kring** [comment]
Changed state because this isn't in progress (as I originally thought) because it isn't in the new C++ CesiumSunSky in #459.
