### ISSUE TITLE
Package project error when i use CesiumSunSky （C++ project ）

### ISSUE THREAD

**Issue by HereWeG0** [CesiumGS/cesium-unreal#493]
![Code ](https://user-images.githubusercontent.com/35327719/122151345-fa4f1a80-ce91-11eb-9731-75db7276af61.png)
![Error](https://user-images.githubusercontent.com/35327719/122151342-f9b68400-ce91-11eb-91a7-8bba25650215.png)

**Comment by xuelongmu** [comment]
Hi @HereWeG0 ,

Could you try checking to see if the Sun Position Calculator plugin is enabled?

![image](https://user-images.githubusercontent.com/10490807/122252373-4782ba80-ce99-11eb-82dc-6a61507bb2db.png)

**Comment by HereWeG0** [comment]
Hi@xuelongmu 
the Sun Position Calculator plugin is enabled,it works, And i can change the sun position with this function  in PIE model。
![functions](https://user-images.githubusercontent.com/35327719/122320146-5f6b4480-cf54-11eb-8f04-1e9964324e53.png)
But this project cannot be Packaged.

**Comment by kring** [comment]
@HereWeG0 can you share more of your log? It's very hard to see what might be the problem from that screenshot of a log, since it's cut off both horizontally and vertically.

**Comment by kring** [comment]
One thing to try: packaging tends to be error-prone with the plugin installed in your project. Can you install the Cesium for Unreal plugin to your Engine plugins directory instead and see if that helps?

**Comment by HereWeG0** [comment]
@kring  Thank you for your  reply. Maybe it's my mistake. When adding my Umg here, packaging project error. Then i move it to the level blueprint. The  project can be packaged  now. 
![code1](https://user-images.githubusercontent.com/35327719/122356317-416a0800-cf85-11eb-84ee-f267c7093313.png)

**Comment by HereWeG0** [comment]
@kring  Thank you for your  reply. Maybe it's my mistake. When adding my Umg here, packaging project error. Then i move it to the level blueprint. The  project can be packaged  now. 
![code1](https://user-images.githubusercontent.com/35327719/122356317-416a0800-cf85-11eb-84ee-f267c7093313.png)
