### ISSUE TITLE
Create C++ CesiumSunSky base class

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#495]
This will allow classes in C++ to call methods in CesiumSunSky without jumping through hoops like iterating through property / function names.

Blueprint logic can be kept in blueprints for ease of modification, using `BlueprintNativeEvent` so that a combination of C++ and Blueprints functionality can be used.

This will also give us an opportunity to add Android compatibility, by creating a basic DirectionalLight + Atmosphere setup using engine-provided `BP_Sky_Sphere`. It's not as realistic as the SkyAtmosphere component but it will enable other CesiumSunSky features such as time of day to be usable on Android platform.

Epic Games' response to question of Android not being supported with SkyAtmosphere component:
```
Hi, on mobile to render SkyAtmosphere you will need to enable support for Vertex Fog in the project settings and also add a Skybox mesh with a material tagged as IsSky and use the SkyAtmosphere [material] nodes to visualize the Atmosphere.

As an example for such material you can create a template map "TimeOfDay" and examine SkyDomeMesh there.

 

In 4.27 we have added on screen warning to let user know why sky atmosphere is missing on mobile. 
```

#190

**Comment by kring** [comment]
This has been done.
