### ISSUE TITLE
After 3dtileset is loaded, all location is the same

### ISSUE THREAD

**Issue by zrkcoder** [CesiumGS/cesium-unreal#507]
![image](https://user-images.githubusercontent.com/71759908/123621526-e3b7a480-d83d-11eb-8a08-1102e025de69.png)
![image](https://user-images.githubusercontent.com/71759908/123621687-0fd32580-d83e-11eb-814d-fe54a104ee11.png)

**Comment by kring** [comment]
@zrkcoder I'm afraid I don't know what you mean. Can you elaborate? Better yet, please consider posting to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead. We prefer to use GitHub issues only for confirmed bug reports and feature requests.
