### ISSUE TITLE
Provide option to ignore the glTF spec and use smooth normals instead of flat normals

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#510]
The [glTF spec says](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes):

> When normals are not specified, client implementations should calculate flat normals.

Calculating flat normals requires duplicating every vertex that is shared between multiple triangles, which increases memory usage, loading time, and rendering time. In many cases, smooth normals -  where each vertex's normal is the weighted average of the normals of its faces - would be just as good or maybe even better. We can easily provide a Tileset option to toggle between smooth normals (faster) and flat normals (strictly spec compliant).

**Comment by nithinp7** [comment]
@kring @baothientran Would it be at all beneficial to make this an option in TilesetOptions? So then smooth normals could be calculated (when normals are missing) on the cesium-native side?
