### ISSUE TITLE
Research options for styling based on feature metadata

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#513]
Full runtime support for [3D Tiles Styling](https://github.com/CesiumGS/3d-tiles/tree/master/specification/Styling) is probably out of reach in Unreal Engine due to the inability to create and compile shaders at runtime. However, we hopefully will be able to find ways to expose feature metadata to Materials, so that users can build custom Materials in the Editor that style features based on their properties.

This task to is to research and prototype ways of doing this, and then write separate issues describing how the implementation should proceed.

**Comment by kring** [comment]
I just discovered `FMaterialUpdateContext`, defined in `C:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Engine\Public\MaterialShared.h`. It looks like this can be used to modify UMaterial and UMaterialInstance instances, compile them, and update them with the render thread. And I don't see anything Editor-specific about it. I haven't tried it, so there could be some major gotcha (other than the shader compile time, which we can safely assume will be on the long side), but it looks promising.

**Comment by hanaimin** [comment]
it's great.

**Comment by kring** [comment]
Addressed in #698.
