### ISSUE TITLE
Add support for KHR_mesh_quantization and EXT_meshopt_compression glTF extensions

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#515]
As a first pass, these can simply be decompressed on the CPU, the way Draco is, and most of the work there can even be in cesium-native. But we should investigate what it takes to send the compressed data all the way to the GPU, since that's a lot of the point of these extensions. We'll likely need to write some custom rendering code rather than using the standard static mesh.

**Comment by kring** [comment]
Added in CesiumGS/cesium-native#685

**Comment by jo-chemla** [comment]
Linking PR: https://github.com/CesiumGS/cesium-native/pull/689
