### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-unreal#53]
We should have a guide for using the Cesium for Unreal plugin.

These instructions may help in the short term but should be updated to follow best practices before the release:

> Here are some steps for loading a tileset locally. You'll need to host the tileset with a local server. A sample tileset can be downloaded from here: https://drive.google.com/file/d/12xQr-q9hRZxcGAYJ0ZUnoTvwiYpeSfwX/view?usp=sharing
> 
> 1. Load the `TakeThree` project and delete the `CesiumOSMBuildings` actor.
> 2. Add a `Cesium 3DTileset` actor to the scene  
> 3. Set url to a local server path like http://localhost:8002/static/Desktop/agi/tileset.json (your path will be different). Alternatively, if you have a tileset hosted on Ceisum ion, pass in the asset id / access token, e.g. `142781` and  `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5YTRiMjI4OS04NTgzLTQ2YjgtOTNmNi02NTVmNjFkZjk4NzgiLCJpZCI6OSwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTU5Nzk2ODQ2N30.clxjNE-5Bc2Y9e7TDt9gN-WpYr6F3BmI-gediu1MTCw`.
> 4. Set the transform location to `0, 0, 0`
> 5. Optionally, set the origin parameters on the Georeference object. For the AGI tileset use Longitude: `-75.5967069626` Latitude: `40.0387958754` Height: `70.257829797`
> 6. Press play
> 
> Other tips:
> 
> * Disable lighting by pressing Shift + F2. Might look better for photogrammetry until https://github.com/CesiumGS/cesium-unreal/issues/52 is addressed.

**Comment by kring** [comment]
The Cesium for Unreal user guide is here: https://cesium.com/docs/tutorials/cesium-unreal-quickstart/
