### ISSUE TITLE
Artifacts when using a terrain asset with CWT as a base

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#541]
Cesium for Unreal doesn't support layered terrain yet, but I still didn't expect it to fail like this:
![image](https://user-images.githubusercontent.com/924374/124866059-1d876880-dfff-11eb-9e8f-efbec570000b.png)

There are also many log meshes like this:
```
LogPhysicsCore: Error: PHYSX: (D:\Build\++Fortnite\Sync\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Source\PhysXCooking\src\mesh\TriangleMeshBuilder.cpp 802) eINVALID_PARAMETER : TriangleMesh::loadFromDesc: desc.isValid() failed!
```

Thanks for reporting it @keyboardsounds. For Cesium folks, the ion asset ID from the screenshot above is 508504 and we have Emma's permission to access it for debugging purposes. The same asset works fine in CesiumJS.

**Comment by baothientran** [comment]
this seems to be related to this issue https://github.com/CesiumGS/cesium-native/issues/274

**Comment by kring** [comment]
This is a duplicate of #561. Closing.
