### ISSUE TITLE
3D tiles do not load as expected during Simulate play mode.

### ISSUE THREAD

**Issue by 3DStephen** [CesiumGS/cesium-unreal#551]
The 3D tiles load properly when in Editor and when in Play-In-Editor mode, but break during Simulate. It seems that Cesium doesn't know what camera frustrum to use, and the tiles are only showing far away from the user. The expected behavior would be that Cesium falls back to the Editor viewport frustrum during this play mode.

![Cesium_SimulatePlay](https://user-images.githubusercontent.com/7797824/125860404-5f0398b8-c4e2-4c2b-83a1-24e80c8ea582.png)

**Comment by kring** [comment]
We added support for multiple simultaneous views in v1.5.0, which I just confirmed fixes this issue.
