### ISSUE TITLE
Unable to add blank tileset (from panel) without logging in to Ion

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#562]
There isn't a reason to require a Cesium Ion login to add a blank tileset to the scene. For users currently stuck on this issue, a blank tileset can be added by searching for the "Cesium3DTileset" actor in the "Place Actors" panel.

###### The "Add Blank" option is greyed out when not logged in to Cesium Ion.
![add-blank-greyed](https://user-images.githubusercontent.com/6706316/126839977-dcede0b5-0919-4cca-b43b-30dc0e8b913e.jpg)

**Comment by kring** [comment]
The option you're hovering over opens the panel to add a tileset from ion. You need to be logged in for that. There used to be an "Add Blank" button, but we got rid of it last release and replaced it with the "Blank 3D Tiles Tileset" item below the toolbar. Hopefully that one still works when not logged in to ion?

**Comment by nithinp7** [comment]
Ah I don't know how I missed that, I just got confused with what that symbol used to be! I think the panel works as intended then.
