### ISSUE TITLE
Android Build broken --std=c++17 not allowed with 'C'

### ISSUE THREAD

**Issue by gabware** [CesiumGS/cesium-unreal#566]
Hi,

Our Unreal Project that's using Cesium does not compile on Android when I pull 
fb132f9cd8ed67720a1ef0cbf151cf9d32778d00 .

I'm open to any suggestions and discussion :)
I'll post more information as I go.

## Compilation output

(this is the output of an incremental compilation, showing the only 2 errors I get.)

```
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   Building 4 actions with 72 processes...
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     [1/4] android_native_app_glue.c [arm64]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     error: invalid argument '-std=c++17' not allowed with 'C'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     [2/4] cpu-features-patched.c [arm64]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     error: invalid argument '-std=c++17' not allowed with 'C'
PackagingResults: Error: invalid argument '-std=c++17' not allowed with 'C'
PackagingResults: Error: invalid argument '-std=c++17' not allowed with 'C'
```

## Versions
* Cesium-Unreal : pulled @ 1ac697e3b195e634b3a0429405ef33498dacaf3b w/ cherrypick fb132f9cd8ed67720a1ef0cbf151cf9d32778d00 
  * I'll try to update to latest, but have little confidence it is going to fix the problem given what's bellow.
* Unreal Engine version: 4.26.0
* Android NDK:  PLATFORM_ANDROID_NDK_VERSION = 210200
  * NDK toolchain: r21b, NDK version: 21, GccVersion: 4.9, ClangVersion: 9.0.8
  * Compiling Native 64-bit code with NDK API 'android-21'

## Problem analysis

`cpu-features-patched.c` and `android_native_app_glue.c` are added to the list of source files of the `Launcher` and `AndroidLauncher` modules. See AndroidToolchain::ModifySourceFiles in Android\AndroidToolChain.cs .

In `AndroidToolChain::CompileCPPFiles` those two files are treated as plain C files, `AndroidToolChain::GetCompileArguments_C` is used to retrieve some of their compilation options. This sets '-x c'.

`-x c` is incompatible with `--std=c++17` that is passed through the `AdditionalCompilerArguments`.

The hack done in CesiumRuntime.build.cs seems to break the `Launch` module when Targetting Android.

## What happens without fb132f9cd8ed67720a1ef0cbf151cf9d32778d00 

The CesiumNative plugin does not compile because of its usage of C++17 and because before 4.26.2  the value of `CppStandard` in the ModuleRules was ignored. (C++ code was compiled as C++14).

## Interesting pages to read for context

[Sneakily force C++17 mode in Android builds #544](https://github.com/CesiumGS/cesium-unreal/pull/544)
[Sneakily force C++17 mode in Android builds - changelist](https://github.com/CesiumGS/cesium-unreal/commit/fb132f9cd8ed67720a1ef0cbf151cf9d32778d00)
[Use 4.26.0 on Travis. Also make Android job only build on Android.](https://github.com/CesiumGS/cesium-unreal/commit/c4a30c92b4e13e5fc77b2f2bc2234b5605f3e048)
[Where to get 4.26.0 or 4.26.1?](https://udn.unrealengine.com/s/question/0D54z000073a47JCAQ/where-to-get-4260-or-4261)
[Note about compiling with C++17](https://community.cesium.com/t/packaging-fails-if-blueprint-nativization-method-inclusive/14390/2)

**Comment by gabware** [comment]
@kring : Have you seen this before ? 
Any idea what's going on with the "Launch" module ?

Thanks in advance !

**Comment by kring** [comment]
Hi @gabware, I don't know anything about the Launch module specifically, but I suggest you upgrade to Unreal Engine 4.26.2. That version doesn't need our hack (and it will be disabled automatically). 4.26.2 is meant to be fully backward compatible with 4.26.0, so hopefully there aren't any barriers to you for upgrading. Also you'll want to use the Cesium for Unreal v1.4.1 tag or the latest build from the Marketplace rather than cherry picking https://github.com/CesiumGS/cesium-unreal/commit/fb132f9cd8ed67720a1ef0cbf151cf9d32778d00, because that commit sets the C++17 flag on all UE versions, not just versions prior to 4.26.2.

**Comment by gabware** [comment]
Thanks for the quick reply Kevin.

Updating to 4.6.2 seems the cleaner option. I'll see if it is possible in my case...
And of course, I'll properly update Cesium For Unreal ;) 

For completeness (in case someone w/ the same problem reads this conversation):
I didn't mention it, but also cherrypicked (partially) c4a30c92b4e13e5fc77b2f2bc2234b5605f3e048 , which set the same flag but only if the version is < 4.26.2  . It was only to test if the compilation issue related to C++17 would go away.

**Comment by kring** [comment]
Closing this, please reopen if you have anything to add.
