### ISSUE TITLE
Plugin Update Instructions

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/cesium-unreal#568]
Our VR tutorial has a line like this:

> Make sure you have the latest version of Cesium for Unreal. To find the updater, open the **Epic Games Launcher** and go to the **Library** tab. Below the version of Unreal that you are using for this tutorial, click **Installed Plugins**.

@argallegos suggested that we should have info about updating the plugin somewhere in our documentation (in a guide and/or FAQ).

**Comment by argallegos** [comment]
Thanks for making this issue, @getinthedamnbox. It's not too complicated to update the plugin, and we don't necessarily need a whole page for it, but it may be good to bundle in to the FAQ (https://github.com/CesiumGS/cesium-unreal/issues/550) or perhaps on another page. 

The guide should probably include:

- How to know if you need to update the plugin
- Updating the plugin through the Epic launcher
- Possibly updating the plugin if using it through git - not sure if this is covered already in another guide, but if not we should have instructions somewhere
- Updating Cesium for Unreal Samples (You can't really update them like you would a plugin, you have to make a new project as far as I know, but should still have steps for it)

**Comment by argallegos** [comment]
Now complete - Has been bundled in with #550
