### ISSUE TITLE
Summary for issues related to DynamicPawn and GlobeAwareDefaultPawn

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-unreal#570]
In the context of the [Georeference refactoring](https://github.com/CesiumGS/cesium-unreal/pull/459), I started looking closer at the `DynamicPawn` and its base class, `GlobeAwareDefaultPawn`. I'd really, *really*, **really** like to bring the Georeference refactoring to an end. But the pawn class and its behavior is tightly coupled with the `Georeference`, and there are some interdependencies of which I'm not sure where, how and when they are going to be resolved.

An attempt of a summary:

- There are some issues caused by the black-box of Unreal and its behavior during "Play In Editor", with differences in the behavior and state space of a pawn depending on whether it is "auto-possessed" or not. Here is a [recent comment](https://github.com/CesiumGS/cesium-unreal/pull/459#discussion_r675639262) where I tried to summarize some of these issues. This is probably related to https://github.com/CesiumGS/cesium-unreal/issues/269 and I wonder whether the path of implementing `ApplyWorldOffset` may make sense here.
- There is a whole collection of questions related to our pawn classes from the forum (mostly from the same user - maybe we can orchestrate our responses and gather some feedback (as in "use cases", "goals", and "(technical) requirements"))
  - [DynamicPawn_Child](https://community.cesium.com/t/dynamicpawn-child/14585), about adjusting the movement speed of a pawn when subclassing the `DynamicPawn` class (no idea how to address that)
  - [Dynamic Pawn to Dynamic Character](https://community.cesium.com/t/dynamic-pawn-to-dynamic-character/14633), which seems to be about applying the dynamic behavior of the `DynamicPawn` to the Unreal [`Character`](https://docs.unrealengine.com/4.26/en-US/InteractiveExperiences/Framework/Pawn/Character/) class. 
  - [Space bar increases height](https://community.cesium.com/t/space-bar-increases-height/14588). As discussed briefly in Slack: This is caused by the fact that `GlobeAwareDefaultPawn` inherits from `DefaultPawn`. From a theoretical standpoint, this should **not** be done. From a practical standpoint, this should ... also not be done, because of issues like this one, but... that's the way it is now. The problem is that the `DefaultPawn` is an "engine-internal" class, and uses code like `AddEngineDefinedAxisMapping(FInputAxisKeyMapping("DefaultPawn_MoveUp", EKeys::SpaceBar, 1.f))` which carries the comment that this *"...engine defined axis mapping that cannot be remapped"*. We could only totally disable the default mapping and establish our own one (giving the user some control over whether the `SpaceBar` is mapped to `DefaultPawn_MoveUp`), or ... just not inherit from this class in the first place.
   - [Ue4 get actor ecef](https://community.cesium.com/t/ue4-get-actor-ecef/14615). This refers to the fact that the pawn rotates when flying along the surface of the earth. I think this *might* actually be a bug (but am not sure): I think the pawn only **seems** to rotate, but the apparent rotation is caused in some not-sooo-obvious way by the origin rebasing. To try it out: 
     - Start a sample (e.g. the `01_Cesium World` sample) and hit "Play"
     - Look at the horizon and move forward quickly (use "mouse wheel up" to move fast)
     - -> The pawn *seems* to stay at a constant height and orientation relative to the globe
     - Do the same, but disable "Keep World Origin Near Camera" in the Georeference before that
     - -> The pawn *seems* to move in a straight line, and shoot straight out into space

      This *might* be related to the known issue https://github.com/CesiumGS/cesium-unreal/issues/334 , which I don't fully understand. But the fact that the (internal) method `Pawn::GetViewRotation` is overridden in `GlobeAwareDefaultPawn` so that it involves some ENU-to-Unreal rotation may, of course, confuse all the Unreal-Internal controller mechanisms arbitrarily and in an unpredictable way. Maybe we could avoid overriding this method, and maybe this would be easier if we didn't inherit from `DefaultPawn`, but ... it's complicated. 
- A collection of related issues which *might* be simple, but need a "triage", as it seems to be called:
  - https://github.com/CesiumGS/cesium-unreal/issues/303 
  - https://github.com/CesiumGS/cesium-unreal/issues/538
  - https://github.com/CesiumGS/cesium-unreal/issues/265 (remotely related)

I started some fixes for the pawn class that are related to the Georeference refactoring. Unfortunately, it's sometimes hard to distinguish between a "regression" and a "change in the behavior that fixed a bug of which we didn't even know that it was a bug" (therefore, they are in a separate branch ( https://github.com/CesiumGS/cesium-unreal/commits/bp-function-library-pawn-fixes ), which is *not* part of the Georeference PR). But regardless of the classification of things as bugs or how and when they are addressed, two questions from which possible actions in view of the list above could be derived:

- Is anybody opposed to letting `GlobeAwareDefaultPawn` **not** inherit from `DefaultPawn`?
- When moving forward in a straight line, should the pawn move forward in a straight line, or in a curve around the globe?

**Comment by kring** [comment]
I think the concrete actions in this issue have already been addressed, so I'm going to close it.
