### ISSUE TITLE
[TileMapServiceRasterOverlay.cpp:168] Could not parse tile map service XML.

### ISSUE THREAD

**Issue by 1457753144** [CesiumGS/cesium-unreal#578]
![image](https://user-images.githubusercontent.com/88534319/128484577-0e729e59-2c33-4df3-8431-57340c8923ce.png)

LogCesium: Warning: [2021-08-06 16:32:11.426] [warning] [Tileset.cpp:570] The tileset contains a gltfUpAxis property. This property is not part of the specification. All glTF content should use the Y-axis as the up-axis.
LogCesium: Warning: [2021-08-06 16:32:11.461] [warning] [TileContentFactory.cpp:74] No loader registered for tile with content type '' and magic value 'pnts'.
LogCesium: Error: [2021-08-06 16:32:14.564] [error] [Tileset.cpp:155] Received status code 404 for asset response https://api.cesium.com/v1/assets/0/endpoint?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiMDc2NjE3MS05YmZkLTRjNDUtYTBlYS0zMTMwMTIxNmI5MTMiLCJpZCI6MjU5LCJpYXQiOjE2MjUyMzc4OTl9.5mzZOAR2fNr6o7BjP5O0oxMl7p44gti2nu8mf2krOpg
LogHttp: Warning: 0000023F537BC100: request has been successfully processed. URL: http://localhost:9000/image/tms/fe886610f65f11eb8a9513f02b9ea524/tilemapresource.xml, HTTP code: 500, content length: 744, actual payload size: 744, elapsed: 4.46s
LogHttp: Warning: 0000023F537BC100 Response Header Content-Length: 744
LogHttp: Warning: 0000023F537BC100 Response Header Content-Type: text/html
LogHttp: Warning: 0000023F537BC100 Response Header Cache-Control: no-cache
LogHttp: Warning: 0000023F537BC100 Response Header Date: Fri, 06 Aug 2021 08:32:15 GMT
LogHttp: Warning: 0000023F537BC100 Response Header Last-Modified: Fri, 06 Aug 2021 08:32:15 GMT
LogHttp: Warning: 0000023F537BC100 Response Header Expires: Sat, 17 Jun 2000 12:00:00 GMT
LogHttp: Warning: 0000023F537BC100 Response Header Pragma: no-cache
LogCesium: Error: [2021-08-06 16:32:15.842] [error] [TileMapServiceRasterOverlay.cpp:168] Could not parse tile map service XML.

**Comment by kring** [comment]
@1457753144 it appears your server is returning a 500 code when Cesium for Unreal requests the tilemapresource.xml file. 500 errors indicate a problem on the server side. I don't think there's anything we can fix here, so I'm closing this, but please take it to the [Community Forum](https://community.cesium.com/c/cesium-for-unreal/10) if you'd like to discuss further.
