### ISSUE TITLE
nullref when GeoreferenceComponent is 

### ISSUE THREAD

**Issue by Jesus-tatherium** [CesiumGS/cesium-unreal#580]
When the blueprint class default scene root is replaced by cesium georefrence component, there a 2 errors in CesiumGeoreferenceComponent.cpp.

1 in _updateAbsoluteLocation when setting const FVector& relativeLocation = this->_ownerRoot->GetComponentLocation();
1 in _updateActorToECEF when setting FMatrix actorToRelativeWorld = this->_ownerRoot->GetComponentToWorld().ToMatrixWithScale();

**Comment by kring** [comment]
Hi @Jesus-tatherium, the CesiumGeoreferenceComponent isn't intended to be used as a root, and in a future version the plugin will be changed to prevent it. So I'm going to close this, but I suspect there's an underlying use-case here that's worth discussing. Please consider raising it on the [Community Forum](https://community.cesium.com/c/cesium-for-unreal/10).
