### ISSUE TITLE
Support loading local imagery with ion tilesets like CWT

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#593]
Currently, the only options for raster overlays with Cesium World Terrain are Bing Maps, Cesium ion, and TMS. Users can not add a raster overlay using `file:///`. 

Is this desired? A possible use case could be a very large dataset that can't be uploaded to Cesium ion, for example.

**Comment by kring** [comment]
@argallegos even with a file URL there would be some format or structure to it. TMS would be a popular one, actually, and should work today. Unless you're talking about directly using a geotiff, which definitely wouldn't enable "a very large dataset" without some pretty specific requirements around how thte geotiff is structure (a [COG](https://www.cogeo.org/) for instance) and a bunch of work on our end.

**Comment by kring** [comment]
Closing this because I don't think there's anything specific to do. Please reopen if you disagree.
