### ISSUE TITLE
Water plugin custom water bodies render in an incorrect location with Cesium for Unreal

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#609]
Not sure if this needs an issue here or not, because I _think_ that this is a bug with the Water plugin, but it's good to be aware of. 

It looks like Water Body Custom actors (and maybe others) will render at an incorrect place when playing in a packaged build or in Standalone mode, though their actual transform will stay correct. The water may follow the camera or hop around to different places. It doesn't seem to be a georeferencing issue, though it may be related to origin rebasing somehow.

Here's an example:
This is the water's actual world location. It renders here when playing in editor. 
![image](https://user-images.githubusercontent.com/39537389/130800870-82eb9ed6-bcaf-43c9-8e17-0bc2fd1ad2e3.png)

Here's the water when playing in a standalone game.
![waterIssue](https://user-images.githubusercontent.com/39537389/130801012-e573ea86-9e6f-46b9-9c5e-6a6ee0d34418.png)

The coordinates of the water actor do not change, and adding a CesiumGeoreference component doesn't help. Moving the camera often results in the water disappearing and appearing somewhere else.

**Comment by kring** [comment]
Closing this as it's almost certainly a bug in the Water Body Actor, and therefore an Engine bug and not something we can fix. In UE5 the problem goes away because we don't do origin rebasing there.
