### ISSUE TITLE
How to build windows .exe with open XR?

### ISSUE THREAD

**Issue by sandy20683** [CesiumGS/cesium-unreal#620]
Hi 
I want to build windows .exe in open XR but getting errors anyone can pls help.

**Comment by argallegos** [comment]
Hi @sandy20683, I recommend you ask this question on the [Cesium Community forums](https://community.cesium.com/c/cesium-for-unreal/10). When you make your post there, please include the error messages that you are seeing, and steps to reproduce the issue, if possible.
