### ISSUE TITLE
Why do many originally Separate meshs become a whole？ Now I load the model and find that a model has only one mesh, and a mesh has only one primitive.

### ISSUE THREAD

**Issue by XiaomengT** [CesiumGS/cesium-unreal#639]

**Comment by kring** [comment]
Sorry we ignored this issue for so long @XiaomengT. In the future, you may have better luck posting to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). In any case, I'm going to close this issue because it has been so long and I'm not quite sure what is being asked.
