### ISSUE TITLE
Support 360° panoramic renders

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#648]
As originally noticed on the [community forum](https://community.cesium.com/t/panoramic-render-cesium-for-unreal/15059/3), 360 degree panoramic renders don't work well with tilesets, even after the recent multiple view frustrum changes. 

Panoramic renders aren't a part of Unreal Engine by default but can be achieved using Unreal's [Panoramic Capture](https://docs.unrealengine.com/4.27/en-US/WorkingWithMedia/CapturingMedia/StereoPanoramicCapture/) plugin or other [third party 360 camera tools](https://www.unrealengine.com/marketplace/en-US/product/camera). Supporting 360 degree rendering is a great idea for a ton of reasons. 

As for the actual issues with rendering:
Even with Frustrum Culling turned off, it looks like tiles away from the forward camera view are loaded at significantly lower detail. The forum user reported the following tileset settings and computer hardware:
>Max screen space error: 16
Preload ancestors: yes
Preload siblings: yes
Max simultaneous tile loads: 2000
Loading Descendent Limit: 1000
Frustrum culling: off
Fog culling: off
RTX3090 cards (24MB VRAM) on a decent computer.

This could be a problem with the view frustrums - both plugins linked above use SceneCapture2D components for the other views, which should be supported, so that feature may be missing something. Or, it might be a problem with Frustrum culling/tile loading. Frustrum culling sometimes will cause background tiles to load in significantly slower, and: https://github.com/CesiumGS/cesium-unreal/issues/375. So possibly the issue could be solved by fixing #375.

**Comment by kring** [comment]
The detail is intentionally low outside the view frustum by default, but you can change it. In addition to the other settings, set:
* EnforceCulledScreenSpaceError = true
* CulledScreenSpaceError = 16

**Comment by kring** [comment]
Setting CulledScreenSpaceError should fix it when frustum culling is disabled. SceneCaptures are also automatically considered these days in some cases, and you can define custom cameras in blueprints if that doesn't help. So I think we can call this one resolved.
