### ISSUE TITLE
CesiumRasterOverlay material has error, undefined preview connection

### ISSUE THREAD

**Issue by xuelongmu** [CesiumGS/cesium-unreal#650]
The CesiumRasterOverlay material has a node for an Input Texture that has its input type set to `Function Input Texture 2D`. Without a valid preview texture wired to this node, it will complain and fail to compile with the error `[SM5] Missing Preview connection for function input 'Texture'`.

I was able to get rid of this error by wiring in a Texture Object set to the `transparent1x1` texture, but I'm not sure if it's the correct input there. Wanted to bring up the error in case you know of the best texture to place there for preview.

![image](https://user-images.githubusercontent.com/10490807/134247492-8f9bd836-eb2a-46dc-9935-747f54eef52d.png)

**Comment by kring** [comment]
I'm not entirely clear why this hasn't been an issue until now, but `transparent1x1` is a good default texture to use.

**Comment by kring** [comment]
By the way, `CesiumRasterOverlay` is only used by deprecated materials at this point. The new Material Layers system doesn't use it.
