### ISSUE TITLE
computeTangentSpace called before texture coordinates are set

### ISSUE THREAD

**Issue by fly1008** [CesiumGS/cesium-unreal#652]
CesiumRuntime\Private\CesiumGltfComponent.cpp  530line loadPrimitive function.
now, call computeTangentSpace before updateTextureCoordinates, wrong?
need after updateTextureCoordinates.

**Comment by kring** [comment]
Good eye @fly1008, you're right! I'm surprised this didn't lead to more serious problems.

**Comment by fly1008** [comment]
There no  more serious problems. I just found a lighting problem around the corner of a building.
