### ISSUE TITLE
Unable easily add additional cameras be considered in ACesium3DTileset tile culling

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal#665]
As it stands ACesium3DTileset actors dynamically search for an [active player camera](https://github.com/CesiumGS/cesium-unreal/blob/a6db71251f15d5e69452eaa2a9427cdf2168803e/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L866) as well as additional [scene capture components
](https://github.com/CesiumGS/cesium-unreal/blob/a6db71251f15d5e69452eaa2a9427cdf2168803e/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L1009) on the tick to determine which cameras to consider for culling. With player cameras the implementation is great however with scene capture components it's slightly rigid as it expects ASceneCapture2D actors which hold USceneCaptureComponent2D components explicitly, while not covering use cases where you simply add USceneCaptureComponent2D to a custom actor, or have child actors. Gathering frequently on tick can also be costly on levels with high object counts. As the [comment](https://github.com/CesiumGS/cesium-unreal/blob/a6db71251f15d5e69452eaa2a9427cdf2168803e/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L1011) states it would be great to rather register cameras explicitly.

@nithinp7 @kring @javagl @baothientran

**Comment by kring** [comment]
This was added in #734.
