### ISSUE TITLE
Support pnts tile payloads

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#670]
Splitting up [this old issue](https://github.com/CesiumGS/cesium-unreal/issues/12) so we can more accurately track progress.

Attempting to load point clouds results in errors like` [warning] [TileContentFactory.cpp:74] No loader registered for tile with content type 'application/octet-stream' and magic value 'pnts'.`

**Comment by kring** [comment]
CC https://github.com/CesiumGS/cesium-native/issues/333

**Comment by j9liu** [comment]
Closed by #1037.
