### ISSUE TITLE
Support i3dm tile payloads

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#671]
Splitting up [this old issue](https://github.com/CesiumGS/cesium-unreal/issues/12) so we can more accurately track progress.

Add support for [Instanced 3D Models](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/Instanced3DModel).

Attempting to load i3dm tilesets results in errors like `[warning] [TileContentFactory.cpp:77] No loader registered for tile with content type '' and magic value 'i3dm'`

**Comment by kring** [comment]
We haven't observed it to be urgent for most of our users, which is why it hasn't been prioritized. If it's especially urgent for you, @DevElves, we could discuss options for you to fund development of it. We also welcome contributions in the form of pull requests.

**Comment by j9liu** [comment]
This has been closed by #1371 and is available in the latest Cesium for Unreal release!
