### ISSUE TITLE
BP FlytoLocationLongitudeLattitudeHeight Broken in 1.7 ?

### ISSUE THREAD

**Issue by Ruveron** [CesiumGS/cesium-unreal#678]
Bonjour,
Since the last version 1.7, it seems the BP FLY to Location Longitude Lattitude Height doesn't work any more.

I create a new project
Add Cesium World Terrain + Cesium OSM + CesiumSunSky + DynamicPawn
Add an empty actor (rename Pos_Actor)
Create level blueprint to fly on a key to the location of the actor.

This process was working in previous build.
The MOVEtoLongitudeLatitudeHeight work but not the FLYtoLongitudeLatitudeHeight

(Not a problem of key ;)   )

Any idea or is it a bug ?
Philippe

![image](https://user-images.githubusercontent.com/46521154/139861011-55c48290-9720-4483-ae64-fb56ec8d9e15.png)

**Comment by kring** [comment]
Hi @Ruveron I just tried it out, and the Fly To seemed to work ok. Can you tell me more about how it's failing for you? Here's my blueprint:
![image](https://user-images.githubusercontent.com/924374/139953342-eac9f32a-e6a8-4121-90c2-b6fd0ecc4ab2.png)

Cube is a just a default Cube from Place Actors but with a Cesium Globe Anchor Component attached.

**Comment by kring** [comment]
I tried removing the Globe Anchor Component from the Cube, and the Fly To still works.

**Comment by kring** [comment]
And I also tried starting a brand new level and using an empty actor instead of a cube. Still working. Let me know what else I can try.

**Comment by Ruveron** [comment]
Hi,
Just try another time in a new project.
Same problem. (with, without globalanchor / movable on actor, ...)
When I press the key, nothing happen.   
If i add a print after inaccurateFly, the print well appear on play.

I'll try on another computer.

**Comment by Ruveron** [comment]
just try on another computer : it works.

Back on the one with the problem : I uninstall Cesium, clear directory, install cesium.
Launch one of the test project i have => Problem always here.

Doesn't see what could be wrong on this station.
No other configuration files for cesium other than in Epic plugin directory ?

**Comment by Ruveron** [comment]
I take the project from the computer where it works and copy it on the one who doesn't work.
The project was working on it !
I found the problem but it's not clear.
It seems to be a problem of location.

On a working project with an actor with Globalanchor;
move the DynamicPawn at  43.2951 and -0.370797
Go there (F)
CesiumGeoreference : PlacegeoreferenceHere
move your actor on the same place ( 43.2951 / -0.370797 / height 350 on the cesiumglobalanchor of the actor)

Launch : it doesn't work any more.

**Comment by Ruveron** [comment]
Hello,
Can you confirm me that it is a bug or what i'm doing wrong ?
Thanks,
Philippe

**Comment by kring** [comment]
Hi @Ruveron, sorry for the delay here, but yes I'd call this a bug. The problem is that the InaccurateFlyTo... functions completely ignore requests to do "short" flights. How short is too short depends on the value of the `DynamicPawn`'s "Fly To Granularity Degrees". I'm going to open a pull request to fix the bug, but in the meantime you should be able to work around it by setting this property to a smaller value.

![image](https://user-images.githubusercontent.com/924374/143820982-729adc7d-fc1a-4d57-8212-d8d773cd8ec1.png)

**Comment by Ruveron** [comment]
Hi !
Thanks for the update :)
I'll très this tomorrow.
Tanks
Philippe
________________________________

Philippe Ruveron
Technico-Commercial Imagerie / Formateur / Responsable systèmeProdware France
***@***.***
Prodware AIGA 
Grande Halle Oberthur
74A rue de Paris, RENNES 
35000
www.prodware-innovation-design.fr
Brochure interactive
