### ISSUE TITLE
Failed to open map file in 'Cesium for Unreal Samples'

### ISSUE THREAD

**Issue by DanilaTing** [CesiumGS/cesium-unreal#686]
When I try to open the expamples for cesium file i get this error: 
"Failed to open map file. This is most likely because the map was saved with a newer version of the engine."

I'm using Unreal Engine 4.27.1 on mac with m1.

**Comment by kring** [comment]
@DanilaTing if you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10). The samples should work in 4.27.1, so I'm not sure what's going on there.
