### ISSUE TITLE
Missig CesiumRuntime, CesiumEditor

### ISSUE THREAD

**Issue by Neurowerk** [CesiumGS/cesium-unreal#692]
Hi. I use Unreal Engine 4.26.2 in Ubuntu 20.04, i built Cesium for Unreal from source without errors, when i use it in project, i have error, Missing modules: The following modules are missing or built with a different engine version:
CesiumRuntime
CesiumEditor
Engine modules cannot be compiled at runtime. Please build through your IDE
![Screenshot from 2021-11-23 17-57-06](https://user-images.githubusercontent.com/64277542/143029333-b413511f-1013-4bb1-8d98-eef04d81d2ab.png)
.
Please help.How to fix it?

**Comment by shehzan10** [comment]
Have you looked at the Unreal Engine packaging step for the plugin that builds the modules? See the Linux command under https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/packaging-guide.md

**Comment by Neurowerk** [comment]
Great Thanks, @shehzan10 !
Module is working fine!
