### ISSUE TITLE
CesiumTileMapServiceRaster load TMS false  v1.81

### ISSUE THREAD

**Issue by yuanlei88** [CesiumGS/cesium-unreal#705]
I can load TMS in V1.70  but V1.81 only show Color fast , not show Image ,please help Me    MinLevel:0, Maxlevel:17, Material Layer Key:Overlay1, space Errow:2 Texture Size:512 or 2048 , Tile Loads:20, Cache Bytes:16777216 .Output log has no error.Please Help me .thank!

**Comment by kring** [comment]
@yuanlei88 I tried two TMS tilesets with these URLs, and both worked correctly in v1.8.1:
* https://sandcastle.cesium.com/images/cesium_maptiler/Cesium_Logo_Color/tilemapresource.xml
* https://sandcastle.cesium.com/CesiumUnminified/Assets/Textures/NaturalEarthII/tilemapresource.xml

I'm not quite sure what you mean by "only show Color fast , not show Image", so it may help if you can provide some more details. If it's possible for us to try out your actual TMS server, that would be the quickest way to see what is going wrong.

**Comment by yuanlei88** [comment]
<TileMap version="1.0.0" tilemapservice="http://tms.osgeo.org/1.0.0"&gt;
<Title&gt;R-CN-JSCZS-2020-1M</Title&gt;
<SRS&gt;EPSG:3857</SRS&gt;
<BoundingBox miny="3652828.486212716" minx="13261824.407478109" maxy="3771661.834271001" maxx="13380148.927263588"/&gt;
<Origin y="3652828.486212716" x="13261824.407478109"/&gt;
<TileFormat width="256" height="256" mime-type="image/png" extension="png"/&gt;
<TileSets profile="global-mercator"/&gt;
<TileSet href="0" units-per-pixel="20037508.34" order="0"/&gt;
<TileSet href="1" units-per-pixel="10018754.17" order="1"/&gt;
<TileSet href="2" units-per-pixel="5009377.085" order="2"/&gt;
<TileSet href="3" units-per-pixel="2504688.5425" order="3"/&gt;
<TileSet href="4" units-per-pixel="1252344.27125" order="4"/&gt;
<TileSet href="5" units-per-pixel="626172.135625" order="5"/&gt;
<TileSet href="6" units-per-pixel="313086.0678125" order="6"/&gt;
<TileSet href="7" units-per-pixel="156543.03390625" order="7"/&gt;
<TileSet href="8" units-per-pixel="78271.516953125" order="8"/&gt;
<TileSet href="9" units-per-pixel="39135.7584765625" order="9"/&gt;
<TileSet href="10" units-per-pixel="19567.87923828125" order="10"/&gt;
<TileSet href="11" units-per-pixel="9783.939619140625" order="11"/&gt;
<TileSet href="12" units-per-pixel="4891.9698095703125" order="12"/&gt;
<TileSet href="13" units-per-pixel="2445.9849047851562" order="13"/&gt;
<TileSet href="14" units-per-pixel="1222.9924523925781" order="14"/&gt;
<TileSet href="15" units-per-pixel="611.4962261962891" order="15"/&gt;
<TileSet href="16" units-per-pixel="305.74811309814453" order="16"/&gt;
<TileSet href="17" units-per-pixel="152.87405654907226" order="17"/&gt;

</TileMap&gt;





&nbsp; For reasons of confidentiality, I cannot provide you with the address, please forgive me, here is the content of my loading image and xml above, please help me!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CesiumGS/cesium-unreal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上6:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CesiumGS/cesium-unreal] CesiumTileMapServiceRaster load TMS false  v1.81 (Issue #705)





 
@yuanlei88 I tried two TMS tilesets with these URLs, and both worked correctly in v1.8.1:
  
https://sandcastle.cesium.com/images/cesium_maptiler/Cesium_Logo_Color/tilemapresource.xml
 
https://sandcastle.cesium.com/CesiumUnminified/Assets/Textures/NaturalEarthII/tilemapresource.xml
  
I'm not quite sure what you mean by "only show Color fast , not show Image", so it may help if you can provide some more details. If it's possible for us to try out your actual TMS server, that would be the quickest way to see what is going wrong.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuanlei88** [comment]
![Uploading 1639137170160.jpg…]()

**Comment by kring** [comment]
I can't see anything wrong with your tilemapresource.xml. Also, very little changed in the TMS support between v1.7.0 and v1.8.1. You can see all the differences here:

* https://github.com/CesiumGS/cesium-native/compare/v0.9.0...v0.10.0 (then click Files Changed, then 121 changed files, then `Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp`)
* https://github.com/CesiumGS/cesium-unreal/compare/v1.7.0...v1.8.1 (then click Files Changed, then 34 changed files, then `Source/CesiumRuntime/Private/CesiumTileMapServiceRasterOverlay.cpp`

If you can't share the problematic TMS (even if it's a different one that exhibits the same problem), there's not much to go on here, so I'm not sure I'll be able to help. Maybe try some basic diagnostics:

* Are you _sure_ the only thing that changed when it went from working to not-working was the Cesium for Unreal version?
* What kind of tileset are you attaching the overlay to? Does the overlay work on other tilesets (such as Cesium World Terrain)? Do other overlays work on this tileset?

Also I still don't know what you mean by "color fast", so I'm not even clear on what problem you're actually seeing.

**Comment by yuanlei88** [comment]
http://122.195.60.10:3001/image/tms/2104da80566311ec8869e5ab91863e49/tilemapresource.xml




---Original---
From: "Kevin ***@***.***&gt;
Date: Fri, Dec 10, 2021 19:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CesiumGS/cesium-unreal] CesiumTileMapServiceRaster load TMSfalse  v1.81 (Issue #705)




 
I can't see anything wrong with your tilemapresource.xml. Also, very little changed in the TMS support between v1.7.0 and v1.8.1. You can see all the differences here:
  
***@***.*** (then click Files Changed, then 121 changed files, then Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp) 

v1.7.0...v1.8.1 (then click Files Changed, then 34 changed files, then Source/CesiumRuntime/Private/CesiumTileMapServiceRasterOverlay.cpp 
 
If you can't share the problematic TMS (even if it's a different one that exhibits the same problem), there's not much to go on here, so I'm not sure I'll be able to help. Maybe try some basic diagnostics:
  
Are you sure the only thing that changed when it went from working to not-working was the Cesium for Unreal version? 

What kind of tileset are you attaching the overlay to? Does the overlay work on other tilesets (such as Cesium World Terrain)? Do other overlays work on this tileset? 
 
Also I still don't know what you mean by "color fast", so I'm not even clear on what problem you're actually seeing.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kring** [comment]
Thanks! I can confirm this is working in CesiumJS, but not in Cesium for Unreal. I'll investigate.
![image](https://user-images.githubusercontent.com/924374/145572962-9c987b0d-2a52-4b39-af47-46f76ab67f77.png)

(by the way, by replying to my email you've posted the link to a public github issue. You may want to visit github and delete it.)

**Comment by kring** [comment]
Ok, I think I see the problem. I'll work on a proper solution, but here's a workaround in the meantime: set the "Maximum Screen Space Error" to a much smaller value. Setting it to `0.01` looks about right to me. You'll need to set it back to 2.0 after the bug is fixed.

**Comment by kring** [comment]
Just to be clear, set the "Maximum Screen Space Error" property on the TMS overlay, not the Tileset!

**Comment by kring** [comment]
Thanks for helping me reproduce the problem @yuanlei88. I opened CesiumGS/cesium-native#414 to fix it.
Our build server is building a version of Cesium for Unreal with the change now. Keep an eye on https://app.travis-ci.com/github/CesiumGS/cesium-unreal/builds/243257310 and when it's complete, you can download the build by visiting https://github.com/CesiumGS/cesium-unreal/tree/non-global-lod, clicking the green tick near the top, and then clicking the "Details" button next to either UE4.26-AllPlatforms or UE4.27-AllPlatforms. Then exctract the zip file to `C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace` or equivalent. If you changed "Maximum Screen Space Error", change it back before installing this build!

![image](https://user-images.githubusercontent.com/924374/145577675-11586399-420b-41c8-84a0-02fd50cc4f99.png)

**Comment by yuanlei88** [comment]
Thank you very, very much for your help
