### ISSUE TITLE
After packaging the project ALL global-anchored Blueprints ends up under terrain

### ISSUE THREAD

**Issue by RaiaN** [CesiumGS/cesium-unreal#709]
- I can't find valid reasons why this might happen. There is no logic in Blueprints that adds an offset.
- Blueprints are on different sublevels but those are not georeferenced by Cesium. I simply use GlobalAnchorComponent to anchor them
- WorldComposition is not enabled
- Sublevels are set to 'always loaded' mode
- Standalone preview play does not have this issue
- Editor play does not have this issue

Cesium version 1.8 (last release)

Help?

**Comment by kring** [comment]
Sorry for the slow response on this one @RaiaN. Are you still having the problem? If so, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) and hopefully we can help you out. I can't think of what might cause that offhand, so we might need to take a look at your project. In any case, I'm going to close this issue.
