### ISSUE TITLE
How to get the height of the terrain from latitude and longitude ?

### ISSUE THREAD

**Issue by CrazyJiajialin** [CesiumGS/cesium-unreal#711]

**Comment by shehzan10** [comment]
Hello @CrazyJiajialin - Thanks for reaching out. For community questions and how-tos, we recommend that you reach out via the [Cesium Community Forum](https://community.cesium.com/c/cesium-for-unreal/10), while GitHub issues are generally kept for feature requests, bug fixes, and similar discussions.
