### ISSUE TITLE
Sun Sky Tutorial: Add fix for ground-to-space transition

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#712]
Regarding the problem of the sky atmosphere looking strange at a certain height when moving from a ground view to aerial view or vice-versa, this advice seems to fix it:

> The Sky Atmosphere system is optimized for scenes that are on ground level. However, there is nothing preventing you from traveling from the ground to a high aerial view, or even outer space. While the transition through the atmosphere should be seamless—without a noticeable transition—from the look-up tables (LUTs) to per pixel tracing, you may sometimes experience a hitch or when this happens.
> This optimization can be disabled by setting the following console command values to 0:
> - r.SkyAtmosphere.FastSkyLUT
> - r.SkyAtmosphere.AerialPerspectiveLUT.FastApplyOnOpaque

Information is from: https://docs.unrealengine.com/4.27/en-US/BuildingWorlds/FogEffects/SkyAtmosphere/#movingfromgroundtoouterspace

CC: @argallegos

**Comment by argallegos** [comment]
Thanks, Nithin! I will add this to one of the tutorials.

**Comment by kring** [comment]
Probably would make sense to make a note of this in this tutorial:
https://cesium.com/learn/unreal/unreal-geospatially-accurate-sun/

**Comment by argallegos** [comment]
Apologies, apparently I didn't actually publish this to the site. This fix has now been added to the Sky Atmosphere section of [here](https://cesium.com/learn/unreal/unreal-geospatially-accurate-sun/#reference-sky-atmosphere).
