### ISSUE TITLE
Unreal Engine 5 support

### ISSUE THREAD

**Issue by demonixis** [CesiumGS/cesium-unreal#714]
Hello,
I try to compile the current plugin (the one from the marketplace) from 4.27 to 5.0 but there are some errors. I saw that there is an UE5 branch, but it's old. I tried to merge it with main, but I can't resolve one conflict.
Have you plans to update this branch soon?

**Comment by nithinp7** [comment]
The most up-to-date branch for UE5 support is #651. We already have an issue for UE5 support in general here: #463, so closing this as duplicate. There are also multiple issues for particular action items needed for full UE5 support I opened recently.
