### ISSUE TITLE
Crash after applying a material to a tileset with drag-and-drop

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#717]
Steps to reproduce:
1. Drag a material onto a tileset from the Content Browser. The material should apply to the tileset.
2. Click on the tileset and find the Material parameters in the details panel
3. Try to set the Material or Water Material via drag-and-drop or using the dropdown in the parameter
4. Editor will immediately crash.

When drag-and-dropping a material onto the tileset, it will apply to the tileset, but doesn't seem to be applying properly. It won't show up in the Details panel on that tileset, and sometimes won't apply to all tiles (random other tiles will use the old material still). So whatever the editor is doing to change the material might be fighting with what we do to change the material.

We should probably either prevent drag-and-drop material changing at all, or else make sure that when a material is drag and dropped it is applied properly in the tileset code too.

Sorry, no logs that I've been able to find for this one.

**Comment by kring** [comment]
This was fixed in #842.
