### ISSUE TITLE
Unable to build a working app for Android (Samsung Galaxy Tab S7)

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#718]
[User on the forums](https://community.cesium.com/t/building-for-android-app-doesnt-start/16794) reported that apps built with Cesium for Unreal won't start properly. They are building for Samsung Galaxy S7. When the Cesium plugin is disabled, the app runs fine. 

This issue requires further testing and investigation on our end.

**Comment by AMX-MattWalker** [comment]
Small clarification. Device is Samsung Galaxy Tab S7

**Comment by AMX-MattWalker** [comment]
@shehzan10 I haven't tested with earlier versions but happy to do so. 
Is there a particular release you think I should try rolling back to?

**Comment by shehzan10** [comment]
@AMX-MattWalker I'm not entirely sure. I would suggest walking backwards from the latest release. Maybe try 2-3 releases so that you are not spending too much time.

A couple more questions:
* Does the error happen on other Android devices too?
* Can you share the Android version currently running on the Tab S7?

**Comment by brholtkamp** [comment]
Just posting this in case it helps, I just solved an Android related problem of a crash on my Quest 2 product.

Make sure that you have the `PhysxCooking` plugin enabled on your project.
![image](https://user-images.githubusercontent.com/716725/149256784-ac4d4af2-a39c-43b1-85a9-02fd551ef69b.png)

I was able to catch this stack on my end:
![image](https://user-images.githubusercontent.com/716725/149257035-d73d5ebf-a57e-4343-9e43-f1fff718118c.png)

https://github.com/CesiumGS/cesium-unreal/blob/a3ee859dc47da5d1b77c1648b6b4d111ec2c9e82/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L525
This line is the culprit, it doesn't gracefully handle a `nullptr` when that module isn't available.

**Comment by AMX-MattWalker** [comment]
@shehzan10, I tested v1.8.0, v1.7.0 and v1.6.1 in UE 4.27. same result. app launches but does not proceed past the Unreal Engine splash screen.

Unfortunately I don't have any other android devices, but I've sent the APK to a colleague and they report the same result. His device is an Samsung Galaxy S8 running Android v9 

The Samsung Tab S7 is running Android 11 (T870XXS2BUK2)

I've setup the project's android build settings to use Target SDK Version 30.  Maybe I should try lowering it?
![image](https://user-images.githubusercontent.com/70559342/149418535-4b42146f-e73e-42d6-ad33-40e6b958b9c5.png)

**Comment by AMX-MattWalker** [comment]
Dropped back to Target SDK version 22 with same result

**Comment by AMX-MattWalker** [comment]
@argallegos, any thoughts on ways to progress this?

**Comment by argallegos** [comment]
Hi @AMX-MattWalker, I'm not sure if this is the same issue, but could you try the following? 

In Project Settings/Platforms/Android, scroll down to the Build section. Uncheck "Support armv7" and check "Support arm64". Then, try packaging again. Let me know if this makes a difference.

**Comment by kring** [comment]
Closing this as it's very old and packaging on Android has been working fine lately.
