### ISSUE TITLE
Display of building models in loaded 3DTiles is corrupted

### ISSUE THREAD

**Issue by sekiguchi-yohei** [CesiumGS/cesium-unreal#725]
3DTiles building models imported by cesium for unreal v1.9.0 are not displayed properly.
This did not happen in v1.5.1, which I have been using.
Also, v1.9.0 now uses more memory to load 3D models than before, causing crashes due to lack of memory and freezing of the UE editor.

- Environment where problems do not occur
> OS Version：Windows Server2019
> RAM：16GB
> Unreal Engine Version：4.26.2
> cesium for unreal Version：v1.5.1

- Environment in which the problem occurs
> OS Version：Windows Server2019
> RAM：16GB、32GB、64GB、128GB 
>   ※I tried with a wide range of memory sizes, suspecting the machine specs, but the same event occurs.
> Unreal Engine Version：4.26.2、4.27.2
>   ※I've tried with two patterns that also support the UE version, and the same thing happens.
> cesium for unreal Version：v1.9.0

Setting up cesium for unreal related actors
- Cesium3DTileset Actor settings
> [Cesium] - [Source]: Change to [From Url]
> [Cesium] - [Url]: Enter the URL of the target tileset.json
> [Tile Culling] - [Enable Frustum Culling]: Change to false

- CesiumGeoreference Actor settings
> [Keep World Origin Near Camera]: change to false

Is this phenomenon a bug?
Or is it caused by the settings in cesium for unreal?
Or is it caused by the 3DTileset? (I can give you the 3DTileset I used for my research if you need it)

**Comment by kring** [comment]
@sekiguchi-yohei we expect v1.9.0 should use less memory if anything, not more. So if you're seeing the opposite, please share your tileset and actor settings so we can take a look.

**Comment by sekiguchi-yohei** [comment]
Thank you very much.

Settings for Cesium3DTileset Actor and CesiumGeoreference Actor are described in up.
（Setting up cesium for unreal related actors）
The Tileset we used is as follows.
I replaced the tileset.json included below with the attached tileset.c4u.json and specified that as the URL.
https://gic-plateau.s3-ap-northeast-1.amazonaws.com/2020/Tokyo23ku3DTiles/13103_minato-ku_2.zip
[tileset.c4u.json.zip](https://github.com/CesiumGS/cesium-unreal/files/7885471/tileset.c4u.json.zip)

I'm looking forward to working with you.

**Comment by kring** [comment]
@sekiguchi-yohei I tried your tileset in CesiumJS (to start), and it worked ok with the original tileset.json, but with the replacement one it doesn't display anything. Is this expected?

Here's [my Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=bVDRSsMwFP2V0KcORrKq4KhdEeajoODQl7xkzdVF06TcpBmb+O8m7WRTl/sQ7rnn3HOSIJAEBVtAsiAGtmQJTvUtfR6wnGfN0C+t8UIZQJ5NySc3hHhAjMgj2qAkYPkjbBCEhxeLWq5GSj7h5mtyww03Ibp5pcGB/203Xpd3q3GYDxY96pLwbON9VzJWXFzTWayinM/mBTusoc1VT9+dNTHY0WYIT10DBmiHqlVeBXBUSJkfdIl4oO2tbVf2dMBNNs0q53ca6hQknVvVdhZ9CpVTyjy0nY4PdWzdNx8ph3NJmqgVO5VWUgWi5OLMV5JGC+fi5LXX+kntgWd1xSL/n1RbIZV5ewiAWuwSbVPU9yNIKa1YbM8rvbV6LfDP5m8).

**Comment by sekiguchi-yohei** [comment]
Hello.
(Sorry for not responding back)
This is the problem here, but we have confirmed that it is resolved in v1.11.0, so we will close it.
Thank you!
