### ISSUE TITLE
Problem adding color + infrared (4-band) imagery to tileset

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unreal#759]
Hi. First off, I love this plugin! I'm currently using it in an upcoming game based on the [Three Mile Island](https://en.wikipedia.org/wiki/Three_Mile_Island_accident) accident. I only am having one small issue with 4-band or infrared orthoimagery from [PennPilot](https://maps.psiee.psu.edu/ImageryNavigator/). It doesn't render properly as a base layer (a majority of it will just appear blank). I found a workaround to be using Bing Maps Aerial as a base layer and draping the imagery over it. Is there a way to fix this so it doesn't appear to be white?
![HighresScreenshot00001](https://user-images.githubusercontent.com/29965024/155019324-e2dfcb31-134d-4563-b482-76d3583cfb87.png)
![Screenshot 2022-02-21 150221](https://user-images.githubusercontent.com/29965024/155019506-3c50e8f2-ea03-45cd-b416-8c46b50c424a.png)

**Comment by kring** [comment]
Hi @brandondsantos, glad to hear you're enjoying the plugin!

> Is there a way to fix this so it doesn't appear to be white?

Sorry but I'm not quite sure what you mean. What's white that shouldn't be?

**Comment by brandondsantos** [comment]
> Hi @brandondsantos, glad to hear you're enjoying the plugin!
> 
> > Is there a way to fix this so it doesn't appear to be white?
> 
> Sorry but I'm not quite sure what you mean. What's white that shouldn't be?

The top photo is supposed to look like the bottom, but there appears to be transparency (possibly from the imagery's alpha channel?) preventing me from achieving the desired output. The imagery in question is Cesium ion Raster Overlay.

**Comment by kring** [comment]
Since the imagery is from Cesium ion, does it look correct on the ion web site? If so, can you please send me the asset ID and a token I can use to access it, so that I can look into why it's wrong in Cesium for Unreal? My email address is in my GitHub profile.
