### ISSUE TITLE
UE5-Preview 1 Unable to open project after importing Cesium for Unreal v1.11.0 

### ISSUE THREAD

**Issue by gvindiol** [CesiumGS/cesium-unreal#769]
My system has UEPreview1 and UE-EA2 installed from Epic Launcher.
I get errors when adding the CesiumforUnrealv1.11.0 to my project Plugins directory.
![image](https://user-images.githubusercontent.com/44582391/156259376-c6196528-be0b-42eb-812e-208f55ae62ed.png)
![image](https://user-images.githubusercontent.com/44582391/156259651-d9c2f1ca-2519-4c4f-bb7e-684275d5561c.png)

**Comment by kring** [comment]
Hi @gvindiol, those errors look like you're trying to use the plugin with a UE5 Early Access build. Note the "UE_5.0EA" at the top of the error list in your screenshot. Only Preview 1 is supported.
