### ISSUE TITLE
Crash when I try to use cesium-unreal

### ISSUE THREAD

**Issue by StarsTesla** [CesiumGS/cesium-unreal#772]
Hi there! Almost two weeks ago when I use the cesium-unreal to display my photogrammetry scene, but today, when I try to start a new ue4 project for my new scene, I found that no matter what I have done, the display is always nothing by using censium-unreal and ion, so I tried to change a project, use the old project, down the version to 1.11, change to the old 3dtiles and even with the ue5.
I have done with reinstalling whole UE or the plugin，nothing changed. I also tried to use other scene like CityPark in the marketplace, it shows fine.
Is there a solution？

Here are the screen shots：
all white after I add cesium sky（all black without sky but with the terrain）
![a1 - 虚幻编辑器 2022_3_3 0_23_15](https://user-images.githubusercontent.com/45264423/156405646-f0d18c27-0a79-43a1-933e-7b1f47e5cb29.png)

crash report after I add a local tiles and the click it
![Unreal Engine 4 Crash Reporter 2022_3_3 0_21_26](https://user-images.githubusercontent.com/45264423/156405968-362d1b58-f640-4cf1-a26f-f3947157a125.png)

normal for citypark or other project without cesium using

![CityPark - 虚幻编辑器 2022_3_3 0_33_34](https://user-images.githubusercontent.com/45264423/156406272-b1fe2365-d0ac-43c3-8801-19cf81cb37b0.png)

**Comment by StarsTesla** [comment]
**Here is the whole crash log：**
And I found that I even don't need to add a local address，just double click could crash the ue4，the key problem also could be why the ion assets did'n display，the output log didnt give any error or warning when I add the terrain or sky to the world.

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000220

UE4Editor_CesiumRuntime!ACesium3DTileset::OnFocusEditorViewportOnThis() [D:\build\++Portal\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:396]
UE4Editor_CesiumRuntime!TBaseFunctorDelegateInstance<void __cdecl(TArray<AActor *,TSizedDefaultAllocator<32> > const &),FDefaultDelegateUserPolicy,<lambda_da65987502ec0d657c9e0a63cfc48592> >::ExecuteIfSafe() [D:\RocketSync\4.27.0-17155196+++UE4+Release-4.27\Working\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:839]
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_SceneOutliner
UE4Editor_SceneOutliner
UE4Editor_SceneOutliner
UE4Editor_SceneOutliner
UE4Editor_SceneOutliner
UE4Editor_SceneOutliner
UE4Editor_SceneOutliner
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
user32
user32
UE4Editor_ApplicationCore
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by kring** [comment]
I'm not sure what's going on with the access violation, but the all white screen when you add CeisumSunSky is easy fix. You need to enable "Extend default luminance range in Auto Exposure settings" in the Project Settings, as explained in the Getting Started guide: https://cesium.com/learn/unreal/unreal-quickstart/#step-5-add-lighting-with-cesiumsunsky.

**Comment by StarsTesla** [comment]
Actually I enabled, so that's the most confused thing.

**Comment by StarsTesla** [comment]
I found that only I click run then I can see the sky and terrain, preview cannot show me the stuff, but what' wrong with the local tileset, click it will totally crash.

**Comment by kring** [comment]
Are you on a remote desktop connection? You could be running into https://github.com/CesiumGS/cesium-unreal/issues/660

As for the crash... I'm not sure. Perhaps there's something wrong with the tileset prevening it from loading, and the plugin isn't handling the focus correctly for a broken tileset. I'd suggest keeping the Output Log open and see if anything helpful is printed there just before it crashes.

**Comment by StarsTesla** [comment]
Finally，I am sure that the problem is the remote realtime rendering，shit bro thanks~
