### ISSUE TITLE
Perforce-like source control breaks Cesium ion token operations

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#776]
Some source control systems, like Perforce, mark files read-only until they're explicitly checked out by the user. If a project's config files are read-only, we won't be able to update them when the user selects a project default token or signs in to Cesium ion. Apparently it just silently fails.

As report on the forum:
https://community.cesium.com/t/need-to-authorize-cesium-every-time-unreal-engine-is-launched/17595/4

At the very least we should report when we can't save a token change. Ideally, we'd ask Unreal to check it out of source control for us.

**Comment by kring** [comment]
@AlbanBERGERET-Epic provided some info about how the Editor does the checkout when settings are edited.

The checkout  is done here:
https://github.com/EpicGames/UnrealEngine/blob/4.27.2-release/Engine/Source/Developer/SettingsEditor/Private/Widgets/SSettingsSectionHeader.cpp#L428

We should be able to get the absolute path of the config file from the `GetDefaultConfigFilename` method of our settings object, as is done here:
https://github.com/EpicGames/UnrealEngine/blob/4.27.2-release/Engine/Source/Developer/SettingsEditor/Private/Widgets/SSettingsSectionHeader.cpp#L268

**Comment by kring** [comment]
Fixed in #929 
(still don't know why GitHub isn't closing issues automatically anymore)

**Comment by lilleyse** [comment]
I think github only closes issues for PRs that go into the default branch
