### ISSUE TITLE
outside earth can see strange things

### ISSUE THREAD

**Issue by 313364973** [CesiumGS/cesium-unreal#792]
when roate camera  outside earth , can see strange images
![1647595658(1)](https://user-images.githubusercontent.com/5771482/158976793-867edab1-74cf-4671-8607-e4ef17a8e69e.jpg)

**Comment by 313364973** [comment]
![image](https://user-images.githubusercontent.com/5771482/159231269-0ccdef5c-34e7-480c-a912-6038ed47afb9.png)
i change this option finished my problem

**Comment by kring** [comment]
Closing this as I don't think there's any action.

**Comment by kring** [comment]
Thanks for posting your solution @313364973.
