### ISSUE TITLE
cesiumForUnreal is in compatible

### ISSUE THREAD

**Issue by a873054267** [CesiumGS/cesium-unreal#794]
I had compile the source code according to READ.ME；But there are still some problems；
1. when I open the project file， Pop-up prompts  ‘cesiumForUnreal is in compatible‘；I had changed the engineversion to match the
 unreal engine version,but that's not  work；
3. so I tried to solve this problem accroding to  [https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/packaging-guide.md](url)
4. when i execute the commond in  the last article，many files cannot be found； 
such as：
  C:\project\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Public\Cesium3DTileset.h(5): fatal error C1083: cannot open the file: “Cesium3DTilesSelection/ViewState.h”: No such file or directory;

**Comment by kring** [comment]
What version of Unreal Engine are you using? And where have you installed Cesium for Unreal from? From the Epic Marketplace? From GitHub? Building it yourself?

**Comment by a873054267** [comment]
> What version of Unreal Engine are you using? And where have you installed Cesium for Unreal from? From the Epic Marketplace? From GitHub? Building it yourself?

1. the  Unreal Engine is 4.26.1;
2. I download the cesium for unreal from github; use the commond :'git clone --recursive https://github.com/CesiumGS/cesium-unreal.git;
3. yeah; I built it by cmake; the version of cmake is 3.23.0-rc2; the Visual studio  version is 2017 (15.9.45) 
'

**Comment by kring** [comment]
Building cesium-unreal from source can be a bit challenging. You need to follow these instructions, and slight tweaks may be needed depending on your system:
https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/developer-setup-windows.md

I'd suggest using the built plugin from the Epic Marketplace or the Releases page if possible:
https://github.com/CesiumGS/cesium-unreal/releases

If your Unreal Engine isn't an official release from Epic, but rather one you built yourself, you may see that message about the plugin being for a different version. You should be able to ignore it, though.

I don't think there's anything for us to fix in the plugin here, so I'm going to close this. If you're still running into trouble, please post to the [Community Forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by a873054267** [comment]
> Building cesium-unreal from source can be a bit challenging. You need to follow these instructions, and slight tweaks may be needed depending on your system: https://github.com/CesiumGS/cesium-unreal/blob/main/Documentation/developer-setup-windows.md
> 
> I'd suggest using the built plugin from the Epic Marketplace or the Releases page if possible: https://github.com/CesiumGS/cesium-unreal/releases
> 
> If your Unreal Engine isn't an official release from Epic, but rather one you built yourself, you may see that message about the plugin being for a different version. You should be able to ignore it, though.
> 
> I don't think there's anything for us to fix in the plugin here, so I'm going to close this. If you're still running into trouble, please post to the [Community Forum](https://community.cesium.com/c/cesium-for-unreal/10).

thank you very so much
