### ISSUE TITLE
Cesium for Unreal v1.11.0 for UE5 PR - Editor Crashes if SQLiteDB becomes broken

### ISSUE THREAD

**Issue by MetaMatticus** [CesiumGS/cesium-unreal#795]
When using Cesium for Unreal v1.11.0 for UE5 PR In UE5 PR2, If the cesium-request-cache.sqlite file database becomes broken the editor crashes.

**Comment by kring** [comment]
This was fixed in https://github.com/CesiumGS/cesium-native/pull/490.
