### ISSUE TITLE
Precision notes

### ISSUE THREAD

**Issue by pjcozzi** [CesiumGS/cesium-unreal#80]
A cleaned up version of this should go into a guide / README / whitepaper / marketing materials - as we unlock game engines for modeling & sim / real-world use cases, the accuracy of the rendering will come into question over and over again - _game engines are known not to be accurate for global-scale WGS84, how did Cesium "fix" that?_

Slack excerpt from @kring @pjcozzi:

>> 1. Cesium for Unreal does math in double precision
>> 2. Cesium for Unreal uses Unreal's origin rebasing feature to minimize the magnitude of the components in the the translate column in the view matrix so that the single-precision math in the Unreal Engine and on the GPU isn't so bad.  Do we have any numbers around this, e.g., 1 cm for 131,071 meter tiles as Deron mentions for RTC, https://help.agi.com/AGIComponentsJava/html/BlogPrecisionsPrecisions.htm
>
>That's right, and the precision should be close to the same as RTC. Either approach brings the translation component of the model-view matrix nearly to zero. The maximum distance of the camera from the view origin is user-configurable and defaults to 100 meters (which is probably overly conservative), so that doesn't change the expected precision meaningfully.
>
>The biggest weakness of this approach is that Unreal's global origin is specified as a signed, 32-bit integer in centimeters, so the overall range is +/- 21 million meters. That's sufficient to get high precision for the whole Earth, but as the camera moves to geostationary orbit or to other parts of the solar system, we'll lose precision fast. I doubt anyone much cares at the moment though.

Also:

>UE is single precision everywhere, but we're using the "origin rebasing" feature to keep the world origin close to the camera and the Cesium primitives know how to rebase in double precision
>
>djusting the origin takes several milliseconds. We update it automatically based on the camera's distance from the previous origin.

CC @shehzan10 for your situational awareness.

----

* [ ] TODO: how will this change with Unreal 5 precision updates?

**Comment by kring** [comment]
Nothing further actionable here, closing.
