### ISSUE TITLE
Invisible editor viewports still affect tile selection

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#801]
I saw this in UE5 preview 2, so I'm not certain if it happens in UE4, too.

* Click the "Maximizes or restores this viewport" button in the top-right corner of the main viewport:
![image](https://user-images.githubusercontent.com/924374/160304779-cbc7a22b-d265-405e-915a-bf6f84055d27.png)
* The view turns into a grid with four viewports, the original main viewport plus three orthographic views.
![image](https://user-images.githubusercontent.com/924374/160304970-a49c485c-ae63-4e34-b907-4be74cd0e103.png)
* Click "Maximizes or restores this viewport" again in the main viewport window in the lower left to restore the original view.
![image](https://user-images.githubusercontent.com/924374/160304828-6cb9ccbc-50c1-49f9-a91d-0420bc14107f.png)

Even though everything now looks the same as when we started, those additional orthographic views are now affecting tile selection. If you fly the editor camera elsewhere and look back toward where you started, you'll see high-detail tile selection in the original area, caused by those non-visible viewports.

These viewports return true for `IsOrtho()` and false for `IsRealtime()`, so we can exclude them on either or both of those results and that would probably be a good change. But it's possible to create a normal realtime, prespective view, and the we still wouldn't want it to affect tile selection when it's not visible. It's not clear from a quick look how we can tell when a viewport isn't visible, but there is most likely a way.

**Comment by nithinp7** [comment]
For occlusion culling I had to check if `FEditorViewportClient::IsVisible()` was true before considering it. The function's documentation says it is "True if the window is maximized or floating." I think this also means it would be false for any viewport once it is closed again. So we could probably add a check for "IsVisible" around here: https://github.com/CesiumGS/cesium-unreal/blob/85079a8b8c3f7595d49132646284668f1c7913f6/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L1308
