### ISSUE TITLE
UE5 Preview 2 tileset physics & collision issue

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#809]
Tileset physics may not be working correctly in UE5 Preview 2. 

This seems to occur mostly near tile seams. It seemed harder to fall through Cesium World Terrain than the Denver tileset.

Tested with Unreal's First Person and Third Person template controllers, and Cesium for Unreal's Dynamic Pawn. Running around with Unreal's first or third person character controller causes the pawn animation to jitter, as if it keeps thinking it's falling, while running over a tileset. Eventually the pawn will fall through the tileset. 

To replicate:

- Load Cesium for Unreal Samples Level 3 in UE5
- Press play
- Run forward about 5 meters until you are off the starting platform
- Run around until you fall through.

**Comment by kring** [comment]
This happens even if you tick Debug -> Suspend Update on the tileset, which will prevent LOD switches. So it doesn't appear to be LOD switch related.

**Comment by shehzan10** [comment]
@kring I assume we can close this? You mentioned that it was fixed in the final release?

**Comment by kring** [comment]
Yes, the final UE5 release no longer has this problem! 🎉
