### ISSUE TITLE
Generate MSL ellipsoid tiles as an alternative to Cesium World Terrain

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#817]
Unlike CesiumJS, Cesium for Unreal doesn't create a plain ellipsoid when Cesium World Terrain is not being used. Allowing for a non-CWT ellipsoid will support a variety of use cases.

Given the way actors are handled in Unreal, it probably makes sense to allow users to add the MSL ellipsoid as they would any other 3D Tileset, or else have it toggleable on the Georeference if a 3D Tileset is not an option. We don't necessarily want it to always be on by default when CWT is not being used.

**Comment by argallegos** [comment]
A user on the forum has made a solid argument in support of this feature [here](https://community.cesium.com/t/what-cesium-for-unreal-tutorials-do-you-want-to-see/14439/27). In particular, this would help avoid some of the distortions and artifacts on Cesium World Terrain.

**Comment by argallegos** [comment]
For some reason or another there are a lot of users requesting this feature recently. [thread 1](https://community.cesium.com/t/cesium-world-terrain/17763), [thread 2](https://community.cesium.com/t/the-terrain-is-uneven-how-to-get-a-relatively-flat-terrain/18261), [thread 3](https://community.cesium.com/t/wgs84-ellipsoid-in-unreal/18152), [thread 4](https://community.cesium.com/t/how-to-have-a-flat-terrain/16553/5)

I posted a workaround of uploading a flat DEM file to ion and using that in place of CWT, but that's not a good long-term solution. Given the amount of interest in it currently, we may want to prioritize this feature. 

@baothientran how much time do you think it would take to get a procedural MSL ellipsoid working?

**Comment by baothientran** [comment]
I can't say for sure as there are a lot of code changes involved, and it needs to be heavily unit tested before ready. Still on progress at the moment

**Comment by argallegos** [comment]
This is a duplicate of https://github.com/CesiumGS/cesium-unreal/issues/423, closing.
