### ISSUE TITLE
UE5 recompiles the plugin each time I recompile my C++ project

### ISSUE THREAD

**Issue by demonixis** [CesiumGS/cesium-unreal#821]
Hello,
I'm not sure if it's my UE5 installation or a problem with the plugin, but each time I recompile my C++ project, it recompiles the plugin. I tried to put the plugin into the Plugins folder and use the marketplace version, but I've the same behaviour for both modes.
Is it a known issue?

**Comment by kring** [comment]
When you say "the Plugins folder", do you mean your project's plugins folder, or the Engine plugins folder?

In general, a plugin installed in [Your Project]\Plugins will be built with your project, while an engine plugin will not. You should delete all copies from your project directory and then install the plugin from the Marketplace.

Note that even if you do this, the Unreal Build Tool will compile all of the plugins you use into a shipping build of your project. That's normal behavior.

I don't think there's an action here, so I'm going to close this. If you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).
