### ISSUE TITLE
Deleting EncodedMetadataComponent doesn't remove styling

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#836]
Even after refreshing the tileset, deleting an EncodedMetadataComponent doesn't stop metadata from being saved into textures. This is the responsible line:
https://github.com/CesiumGS/cesium-unreal/blob/a949dc8bd8837ac7b4c8fc712d997e8d8644a302/Source/CesiumRuntime/Private/Cesium3DTileset.cpp#L803-L809

We should set the _encodedMetadataDescription to be empty if there is not EncodedMetadataComponent during LoadTileset.

**Comment by argallegos** [comment]
@nithinp7 looks like this was fixed in #837. Ok to close this issue?
