### ISSUE TITLE
Bounding boxes are incorrect away from the georeference origin

### ISSUE THREAD

**Issue by Aqiang223** [CesiumGS/cesium-unreal#839]
https://user-images.githubusercontent.com/29616723/167078082-133730dd-8bd5-4ff4-a698-cfac5af3c766.mp4

https://docs.unrealengine.com/4.27/en-US/TestingAndOptimization/PerformanceAndProfiling/Visualizers/OutOfBoundsPixels/

**Comment by kring** [comment]
Hi @Aqiang223, can you tell us more about what is happening here? What did you do to create this flickering? We haven't seen anything like that ourselves.

**Comment by Aqiang223** [comment]
@kring  My world origin is 119.016181,30.631082, and the camera is 108.960495,34.220991. Open out of bounds pixels and bounds, find the pixel near the camera and make it at the edge of the screen.

https://user-images.githubusercontent.com/29616723/167093977-dfc01f52-60ac-446a-b729-ac2ace66d780.mp4

**Comment by kring** [comment]
Thanks @Aqiang223! I found I had to switch to Unlit mode to see the out-of-bounds highlight, for some reason.

In any case, I can reproduce this. The bounding volumes look good near the georeference origin, but are incorrect farther away. I'll investigate.

**Comment by nithinp7** [comment]
@Aqiang223 The fix for this is merged and will be released in a patch release soon. In the meanwhile feel free to try out the `ue4-main` branch which has the fix. Closing this now, feel free to reopen it if it doesn't fix your issue!
