### ISSUE TITLE
Tile rendering leaves a hole on globe

### ISSUE THREAD

**Issue by MuhammedKalkan** [CesiumGS/cesium-unreal#840]
ION tileset id is 986442

You can see holes within the terrain. CesiumJS rendering is perfectly fine.

![image](https://user-images.githubusercontent.com/19736494/167271240-7c6b1811-9114-41ed-91a9-8b2ff4f7eb17.png)

Also with my custom tiles, where Cesium JS  renders perfectly again, Unreal Engine plugin leaves a hole where it should up sample parent tile (because child tile is not available, layer.json says so) in addition to same bug that also present at ION tileset that i just described above. I can supply that as well if you want to check that out.

![image](https://user-images.githubusercontent.com/19736494/167271339-f1630c56-c772-4482-a94c-bb632ce6c22e.png)

**Comment by kring** [comment]
@MuhammedKalkan what version of Cesium for Unreal are you using? Check the Edit -> Plugins -> Geospatial page. I believe we fixed this problem in 1.13.

**Comment by MuhammedKalkan** [comment]
@kring Downloaded latest release (1.31.1) and extracted into Unreal 5. 

Have you also seen before whole tile missing  thing before or just strip like hole ? Cant decide if you also consider that as a bug and require tile files

![image](https://user-images.githubusercontent.com/19736494/167297189-01676528-e0b8-46c4-809f-fe613775ae6f.png)

**Comment by kring** [comment]
Prior to 1.13, layered terrain didn't work right at all in Cesium for Unreal. It would ignore the underlying layer, and try to fill in missing tiles with aggressive (and perhaps unsuccessful) upsampling. Are you still seeing a problem in 1.13.1?

**Comment by MuhammedKalkan** [comment]
Yup problem is in 1.13.1. My custom tileset uses layer.json rather than metadata extension so as you have pointed out, with this release (1.13.1) i have just tested it. 
About ION generated terrain, never tried with older plugin versions. 
Both tilesets are generated using same DEM file btw

**Comment by kring** [comment]
Ok, can you please supply two Sandcastles with the two problematic datasets? Then we'll investigate why they aren't working the same in Cesium for Unreal. You can email them to me directly if they contain keys that you don't want to share publicly (kevin@cesium.com). Thanks!

**Comment by MuhammedKalkan** [comment]
@kring Sure!

I have sent you an email for both tilesets. Please feel free to ask for any assistance about custom tileset if you have any problems

**Comment by kring** [comment]
I received your email, thanks @MuhammedKalkan. The problem with the ion tileset appears to be a known issue that @joseph-kaile happens to be working on right now. It's possibly related to https://github.com/CesiumGS/cesium-native/issues/385, but Joseph is still investigating.

**Comment by MuhammedKalkan** [comment]
@kring Thats great.

I have emailed you a sandcastle example with hosted custom tileset. 
Please let me know if you  have any troubles

**Comment by kring** [comment]
Fixed by https://github.com/CesiumGS/cesium-native/pull/500.
