### ISSUE TITLE
ktx_read appears twice in CesiumRuntime.Build.cs list of libraries

### ISSUE THREAD

**Issue by lp249839965** [CesiumGS/cesium-unreal#849]
https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Source/CesiumRuntime/CesiumRuntime.Build.cs#L95
https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Source/CesiumRuntime/CesiumRuntime.Build.cs#L87

is it right or not？

**Comment by kring** [comment]
That's a mistake. I don't think it will do any harm, though. Thanks for pointing it out!

**Comment by j9liu** [comment]
Fixed as of v2.5.0 release.
