### ISSUE TITLE
Credit widget blocks UI interaction

### ISSUE THREAD

**Issue by joseph-kaile** [CesiumGS/cesium-unreal#857]
As described in this [forum post](https://community.cesium.com/t/credits-widget-blocks-ui-interaction-even-when-show-credits-on-screen-is-off/18448), the web browser widget can interfere with other UI elements even when there are no credits on the screen.

**Comment by kring** [comment]
@joseph-kaile I believe you fixed this one when you implemented the RTF-based credits, right?

**Comment by joseph-kaile** [comment]
I can't tell if it actually solved the problem. The widget is still spawned even if no credits are on the screen.

**Comment by kring** [comment]
I verified that the credit widget no longer blocks clicks.
