### ISSUE TITLE
Add support for custom pattern XYZ tiles for Raster overlay

### ISSUE THREAD

**Issue by jo-chemla** [CesiumGS/cesium-unreal#863]
Hello there! 
I'd like to use a Raster Map Overlay draped over my cesium-terrain, based on custom pattern XYZ tiles URL - stored as webmercator tiles. I was able to use a TMS raster overlay with a correct TMS server which do have a `tilemapresource.xml` file. 
 - [TMS Overlay url](https://community.cesium.com/t/load-tilemapservice/14506/3) `http://server.domain/image/tms/tilemapresource.xml` requires  inputting url `http://server.domain/image/tms/`
 - [WMS Overlay url](https://community.cesium.com/t/web-map-service-raster-overlay-doesnt-work-requires-service-tag/18155) requires url of the form `https://service.pdok.nl/lv/bag/wms/v2_0` or `https://data.3dbag.nl/api/BAG3D_v2/wms 2`

Unfortunately, for my imagery, there is no existing TMS or WMS published server available. I only know the pattern of the tiles URL. Some sample URL patterns are shown below: Z, X and Y represent XYZ or TMS coordinates in the webmercator 3857 CRS
 - `http://server.domain/.../tile/{Z}/{Y}/{X}.jpg`
 - `http://server.domain/.../tile/&z={Z}&x={X}&y={Y}`
 - `http://server.domain/.../tile/{Z}/{X}/{Y}/256/png8?param1=value1`
 - `http://server.domain/.../tile/{Z}/{Y}/{X}.jpg`
 
 Edit: just cross-posted on the [community forums](https://community.cesium.com/t/add-support-for-custom-pattern-xyz-tiles-for-raster-overlay/18776)

**Comment by kring** [comment]
It sounds like you want something like CesiumJS's [UrlTemplateImageryProvider](https://cesium.com/learn/cesiumjs/ref-doc/UrlTemplateImageryProvider.html). Implementing a new class derived from `RasterOverlay` is relatively straightforward, so you may even be interested in having a go yourself. Most of the work will be in [cesium-native](https://github.com/CesiumGS/cesium-native).

**Comment by jo-chemla** [comment]
Thanks for the quick reply, this is indeed exactly what I need! Plus the reverseY param can also be very useful for converting XYZ to TMS schemes. 

I don't think I would be able to implement that class similar to the [TileMapServiceRasterOverlay.cpp](https://github.com/CesiumGS/cesium-native/blob/main/Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp), but in the meantime, I went another route. I've used mapproxy to define a layer and source based on my url schemes and patterns, which then publishes the service as TMS and WMS local url. Unfortunately, 
 - the `tilemapresource.xml` is not served by mapproxy (and is instead accessible through the root of the service `http://localhost:8082/tms/1.0.0/osm_test/webmercator_reversey`), and I've seen on the community forum this is not yet handled by the TMS Raster Overlay on Cesium, pretty similar issue to GeoServer. 
  - So I tried to use the WMS localhost url instead as a URL to the TMSRasterOverlay in unreal, `http://localhost:8082/service?REQUEST=GetCapabilities` and `http://localhost:8082/service` with no luck yet. 
 
Do you have an idea of how I could make the TMS or WMS mapproxy urls work for the TileMapServiceRasterOverlay within Unreal? Thanks again for your help!

**Comment by kring** [comment]
I don't have any first-hand experience with mapproxy... but it sounds like to use its TMS service we'll have to fix https://github.com/CesiumGS/cesium-native/issues/468. Hopefully it's possible already to use its WMS service, though. Try using a `CesiumWebMapServiceRasterOverlay` instead of a `CesiumTileMapServiceRasterOverlay`. You'll want to use `http://localhost:8082/service` as the URL.

**Comment by jo-chemla** [comment]
Thanks for the details. Made me realize I don't have the CesiumWebMapServiceRasterOverlay, probably because I'm using an older version of the unreal plugin! Will try to upgrade, thanks again a lot!
![image](https://user-images.githubusercontent.com/16822841/170491845-8136ce3d-e501-4f71-9ce3-e2e935ccf904.png)

**Comment by jo-chemla** [comment]
Thanks, I was finally able to solve this using mapproxy to serve a WMS service for my custom xyz pattern/scheme urls, and use it with the CesiumWebMapServiceRasterOverlay. Closing the issue!
