### ISSUE TITLE
Hangs/crashes when running out of memory

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/cesium-unreal#87]
This might be old news / irrelevant, but I'm adding this info in case it's helpful for any reason. Please feel free to close this issue.

On one of my home machines (lower specs relative to my Cesium laptop), the crash rate for Project Everywhere 0.1 is very high: it crashes within a few seconds a majority of the time, sometimes instantly. Perhaps relatedly, I never see the `Texture streaming pool over budget` warning message on that machine.

![texture streaming pool over budget](https://user-images.githubusercontent.com/18287035/97910351-9e2af200-1d17-11eb-8e43-6d93c0816fca.png)

It's possible that the program can't recover from whatever causes that warning, or it might just be another memory problem that happens first.

Specs for the home machine:

```
GeForce GTX 1070
Intel Core i5-4670K CPU @ 3.40GHz
16GB RAM
```

**Comment by baothientran** [comment]
this hasn't happened since, so I close it for now. Feel free to re-open if it happens again
