### ISSUE TITLE
CesiumSunSky exposure issue after enabling and disabling the mobile sunsky

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#878]
By default, the CesiumSunSky has a very high brightness and requires the "Extend Default Luminance Range for Auto Exposure" setting to avoid the scene being washed out with white. When switching to mobile rendering, presumably this setting is not possible and so a more reasonable intensity is chosen. When mobile rendering is disabled again, the intensity seems to get reset, but now the scene becomes completely washed out with white. At this point, the "Extended Default Luminance Range..." option is still enabled in the project settings. This bug persists even after deleting and recreating the CesiumSunSky, closing / reopening the project, and anything else I could think to do. The only workaround is to lower the intensity of the CesiumSunSky's directional light component, which makes the scene look unnatural.

**Comment by kring** [comment]
This is a pretty surprising bug, I'm not sure what you make of it. I've certainly seen it take awhile for the auto-exposure to readjust to sunlit levels of lighting, but it's strange that it would never happen. I'm inclined to close it on account of the CesiumSunSky working reasonably well on mobile in recent versions of UE, so there's not too much benefit of using the mobile rendering mode anymore. If anyone is still seeing this and bothered by it, though, then please re-open this issue so we can investigate further.
