### ISSUE TITLE
wrong render result for android

### ISSUE THREAD

**Issue by eusru** [CesiumGS/cesium-unreal#881]
I followed this [issue](https://github.com/CesiumGS/cesium-unreal/issues/661) to fix some render .
but when I move to the highest view , there is some render bug .
![CesiumForUnreal1](https://user-images.githubusercontent.com/31683509/174251106-77ab2399-6598-447f-ad88-4e5eee8be644.jpg)
![CesiumForUnreal2](https://user-images.githubusercontent.com/31683509/174251119-bea3328e-74e4-4b23-9a4f-fa8ad44b62a7.jpg)

**Comment by kring** [comment]
Yes, that issue mentions that it doesn't look good when zoomed out. You might want to stick to the "Enable Mobile Rendering" mode if you need zoomed-out views.

**Comment by eusru** [comment]
> Yes, that issue mentions that it doesn't look good when zoomed out. You might want to stick to the "Enable Mobile Rendering" mode if you need zoomed-out views.

Yes.I did as you say and it work fine Thanks kevin.
And I will close this issue.
For more problem discussion ,check  Cesium community fourm .
