### ISSUE TITLE
Why is cesium-native set as url = ../cesium-native.git ?

### ISSUE THREAD

**Issue by installgentoo** [CesiumGS/cesium-unreal#903]
So why is the dependency set to relative path? This was a minor annoyance for me when i was trying to figure why isn't fetching submodules work by default.
Should this be set to absolute instead?

**Comment by kring** [comment]
We do that so that cesium-native is fetched over either https or ssh, depending on which was used to fetch cesium-unreal. What problem did it cause for you?

**Comment by installgentoo** [comment]
When i forked cesium-native to make pull requests, i had to manually change the path to cesium-native submodule. I suppose alternatively i could fork it too, but then i'd have to fetch it manually on my repo, all the time.

**Comment by kring** [comment]
Ok, I think we could fix that by changing the relative path to `../../CesiumGS/cesium-native.git`. I'm happy to merge a pull request with that change if it works for you.

**Comment by installgentoo** [comment]
Sure it does.
