### ISSUE TITLE
Occlusion retrieval race condition?

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#904]
Joseph ran into an access violation when retrieving the occlusion results in `CesiumViewExtension::BeginRenderViewFamily`. This was not reproducible on subsequent runs and I have not personally run into the issue. I wonder if the occlusion info is not actually game-thread-safe during `BeginRenderViewFamily` as I assumed, we might have to go back to enqueueing render thread tasks to sync occlusion results back to the game thread. Here is the screenshot from Joseph including the crash location as well as a glimpse of the stack trace.

![bug-occlusion](https://user-images.githubusercontent.com/6706316/178849213-c9b281be-8967-4c41-8106-86ae3e47e2f6.PNG)

**Comment by nithinp7** [comment]
Should be fixed by #919, but please reopen this if anyone runs into anything similar related to occlusion.

@kring Did the repo settings change recently to not automatically close issues marked as fixed by a PR?

**Comment by kring** [comment]
> Did the repo settings change recently to not automatically close issues marked as fixed by a PR?

Unfortunately our `ue5-main` branch is considered the "main" one, so linked issues won't be closed until the PR's commits land in that branch. This is probably yet another reason we should make ue4-main the primary branch for now.
