### ISSUE TITLE
Error: Type 'double' is not supported by blueprint

### ISSUE THREAD

**Issue by Neurowerk** [CesiumGS/cesium-unreal#905]
Hi, everyone!
I building Cesium for Unreal v 1.15.1 in Ubuntu 20.04 for Unreal Engine 4.27.
Wen i create package
with
"$UNREAL_ENGINE_DIR/Engine/Build/BatchFiles/RunUAT.sh" BuildPlugin -Plugin="/home/user/workspace/cesium-unreal/CesiumForUnreal.uplugin" -Package="/home/user/workspace/packages/CesiumForUnreal" -CreateSubFolder -TargetPlatforms=Linux
i have many errors as
CesiumForUnreal/packages/CesiumForUnreal/HostProject/Plugins/CesiumForUnreal/Source/CesiumRuntime/Public/GlobeAwareDefaultPawn.h(157) : LogCompile: Error: Type 'double' is not supported by blueprint. FlyToLocationLongitudeLatitudeHeight.YawAtDestination
etc.
How is possible to fix this problem?

**Comment by joseph-kaile** [comment]
Hello, those look like issues when using UE4 with the default ue5-main branch. If that's the case, then switch to the ue4-main branch.

**Comment by Neurowerk** [comment]
Thank you!
