### ISSUE TITLE
Crash when deleting Cesium3Dtileset in the editor.

### ISSUE THREAD

**Issue by Binary1000** [CesiumGS/cesium-unreal#908]
Unreal Engine version: 5.0.3
Cesium For Unreal version: 1.15.1

I can't delete the Cesium3Dtileset in the editor, If I do so and save the level, ue5 crash immediately.
below is the crash report.

LoginId:30239dcc40486d648ab989af5a0f4353
EpicAccountId:70e9990e63ac4ff88a02269895f21f02

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\Templates\Casts.cpp] [Line: 10] Cast of Cesium3DTileset /Game/Main.Main:PersistentLevel.Cesium3DTileset_UAID_A87EEADCC3C2B91D01_1724040348 to MetaData failed

**Comment by ThomasMartinKearns** [comment]
Source Build of 5.0.2
Cesium 1.15.1

We have a similar error when unloading a level, i.e. switching between levels in the editor, closing the editor.

**Comment by kring** [comment]
v1.15.1 is very old at this point. Can you try upgrading to v1.20.1 and see if it fixes the problem?

**Comment by krz9000** [comment]
suffering from the same error message when closing UE5.1.1. was working fine with 5.0.3. since the project convertion to 5.1.1 i get this crash everytime i close the editor. EVERY TIME

**Comment by kring** [comment]
This was fixed in #1111.
