### ISSUE TITLE
Build error Linux

### ISSUE THREAD

**Issue by samhodge** [CesiumGS/cesium-unreal#912]
(base) discobot@mirrorball:~/Documents/github/cesium-unreal/extern$ cmake --build build --target install
[  1%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriCommon.c.o
[  1%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriCompare.c.o
[  1%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriEscape.c.o
[  1%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriFile.c.o
[  1%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriIp4Base.c.o
[  3%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriIp4.c.o
[  3%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriMemory.c.o
[  3%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriNormalizeBase.c.o
[  3%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriNormalize.c.o
[  3%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriParseBase.c.o
[  4%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriParse.c.o
[  4%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriQuery.c.o
[  4%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriRecompose.c.o
[  4%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriResolve.c.o
[  4%] Building C object cesium-native/extern/uriparser/CMakeFiles/uriparser.dir/src/UriShorten.c.o
[  6%] Linking C static library liburiparser.a
[  6%] Built target uriparser
[  7%] Building CXX object cesium-native/CesiumUtility/CMakeFiles/CesiumUtility.dir/src/ExtensibleObject.cpp.o
In file included from /home/discobot/Documents/github/cesium-unreal/extern/cesium-native/CesiumUtility/src/ExtensibleObject.cpp:1:
In file included from /home/discobot/Documents/github/cesium-unreal/extern/cesium-native/CesiumUtility/include/CesiumUtility/ExtensibleObject.h:3:
In file included from /home/discobot/Documents/github/cesium-unreal/extern/cesium-native/CesiumUtility/include/CesiumUtility/JsonValue.h:5:
In file included from /home/discobot/Documents/github/cesium-unreal/extern/cesium-native/extern/GSL/include/gsl/narrow:19:
/home/discobot/Documents/github/cesium-unreal/extern/cesium-native/extern/GSL/include/gsl/assert:38:10: fatal error: 'exception' file not found
#include <exception>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [cesium-native/CesiumUtility/CMakeFiles/CesiumUtility.dir/build.make:63: cesium-native/CesiumUtility/CMakeFiles/CesiumUtility.dir/src/ExtensibleObject.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3365: cesium-native/CesiumUtility/CMakeFiles/CesiumUtility.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by samhodge-aiml** [comment]
nevermind I was able to recompile from the release version and everything works.

**Comment by samhodge** [comment]
sorry wrong account
