### ISSUE TITLE
Landscape Mode support for Cesium tilesets

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unreal#915]
I understand that Cesium's tilesets are Static Mesh actors. But would adding support to make them editable in Landscape Mode be possible in a future release?

**Comment by kring** [comment]
It's commonly requested, and something we'd like to support. It's also quite challenging, though. A tileset is composed of lots (sometimes many millions) of individual tiles forming a multi-resolution pyramid. Each tile is a static mesh, but making that a single coherent object that can be edited - especially within the context of Unreal's landscape system which has certain expectations - is far from straightforward.

So, we do expect to provide the ability to edit tilesets in the future, but I can't currently say when that might be.

**Comment by nithinp7** [comment]
Adding to what Kevin already said, we have an open issue to brainstorm ways to approach this feature: https://github.com/CesiumGS/cesium-unreal/issues/351

Closing this just to avoid duplication, feel free to add more thoughts in the original issue. This will be a super cool feature when we have the time to get around to it.
