### ISSUE TITLE
Rendering priority of Cesium terrain and Ultra Dynamic Weather System

### ISSUE THREAD

**Issue by JoinKomorebi** [CesiumGS/cesium-unreal#920]
Use the Cesium plug-in and the Ultra Dynamic Weather System plug-in at the same time in Unreal, run the program, in mid-air, if there is a Cesium terrain behind the cloud, the engine will render the Cesium terrain first, resulting in the effect that part of the cloud disappears, only when Cesium is not loaded When the terrain is used, the clouds of the weather system will be rendered normally.
   I guess that the rendering priority of Cesium terrain is higher than that of the weather system, so the Cesium terrain is preferentially rendered, and part of the clouds are blocked and invisible behind the Cesium terrain.
   Now I don't know how to fix this bug, I need your help.
![微信图片_20220722142728](https://user-images.githubusercontent.com/104044166/180381031-bca3dae7-dc5a-4e62-9096-0c11ca246d87.png)
![微信图片_20220722142742](https://user-images.githubusercontent.com/104044166/180381032-baf0accb-0fe3-4e36-87b3-a6917b5fbe70.png)

**Comment by robinwood3d** [comment]
你好，The Ultra_Dynamic_Sky actor has a property called Volumetric Cloud Rendering Mode，你看看这个属性是不是被设置成了CBackground Only Clouds. You can switch to Clouds Render Over Opaque Objects(Performance). 我这边这样设置就显示正确了。

**Comment by kring** [comment]
Translation of the comment above:

> Hello, The Ultra_Dynamic_Sky actor has a property called Volumetric Cloud Rendering Mode, please check if this property is set to Background Only Clouds. You can switch to Clouds Render Over Opaque Objects(Performance). If I set it like this here, it will display Correct.

Because that can be solved with a setting change in the other plugin, and I'm not aware of anything we can fix in Cesium for Unreal, I'm going to close this issue.
