### ISSUE TITLE
Loading and unloading Cesium streaming level freezes for 1 second

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#930]
When I load and unload Cesium streaming levels, the scene freezes for a while, about 1 second. I don't know if you have this kind of problem?

**Comment by kring** [comment]
The levels are unfortunately loaded synchronously, which can cause a small or large pause depending on the size of the level. This feature is based on Unreal's World Composition feature, which has been deprecated in UE5, so we're unlikely to do any major work on it. However, there will be a UE5 replacement at some point, and we will definitely keep this in mind when we work on it. See #729. I'm going to close this issue to keep the issue list tidy.
