### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by YourSword** [CesiumGS/cesium-unreal#939]
My new project run in the output log given the follow error msg:

LogCesium: Error: [2022-08-11 15:51:27.239] [error] [SqliteCache.cpp:441] database is locked
LogCesium: Error: [2022-08-11 15:51:27.240] [error] [SqliteCache.cpp:412] database is locked
LogCesium: Error: [2022-08-11 15:51:27.240] [error] [SqliteCache.cpp:441] database is locked

![8163](https://user-images.githubusercontent.com/25164918/184103914-acfd6ac0-f6e7-49ba-87b5-5d713b1748c7.png)

I don't know what it is, and how it happened, help me please!

**Comment by joseph-kaile** [comment]
Hello, I'm not sure what caused the error, but for the time being you could delete (or move) "C:\Users\<username>\AppData\Local\UnrealEngine\<your unreal version>\cesium-request-cache.sqlite", which would hopefully allow you to proceed.

What version of the Cesium plugin are you using?

**Comment by kring** [comment]
As a bit of background, Cesium for Unreal uses as a SQLite database to cache network requests. The most common cause of the error you're seeing is when two applications are trying to use that cache database simultaneously. This can happen if you're running a packaged version of your application while simultaneously running the Unreal Editor. Or perhaps even if you're running two packaged applications simultaneously that use Cesium for Unreal.

In any of these cases, the cache locked error is "mostly" harmless. You may see reduced performance and more network requests, but nothing should break.

But if you're seeing that message while only running one application, then Joseph is on the right track. Check the cesium-request-cache.sqlite file. Has it somehow been marked read-only? Is it on a network drive of some sort such that SQLite locking isn't able to work? Or is it somehow corrupt? (in which case deleting it is the solution).

**Comment by YourSword** [comment]
> Hello, I'm not sure what caused the error, but for the time being you could delete (or move) "C:\Users<username>\AppData\Local\UnrealEngine<your unreal version>\cesium-request-cache.sqlite", which would hopefully allow you to proceed.
> 
> What version of the Cesium plugin are you using?

I'm using the latest version in UE5. Thanks, I delete the sqlite and it work ok

**Comment by YourSword** [comment]
> As a bit of background, Cesium for Unreal uses as a SQLite database to cache network requests. The most common cause of the error you're seeing is when two applications are trying to use that cache database simultaneously. This can happen if you're running a packaged version of your application while simultaneously running the Unreal Editor. Or perhaps even if you're running two packaged applications simultaneously that use Cesium for Unreal.
> 
> In any of these cases, the cache locked error is "mostly" harmless. You may see reduced performance and more network requests, but nothing should break.
> 
> But if you're seeing that message while only running one application, then Joseph is on the right track. Check the cesium-request-cache.sqlite file. Has it somehow been marked read-only? Is it on a network drive of some sort such that SQLite locking isn't able to work? Or is it somehow corrupt? (in which case deleting it is the solution).

Thank you! I see that message while only running one application, and the sqlite file isn't read-only, i delete it and then my project work Ok

**Comment by lincoln310** [comment]
I think the solution should be:
cesium can set path of the SQlite to use.
or use project/saved path.
