### ISSUE TITLE
LOD transition improvements

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#961]
[Dithered LOD transitions ](https://github.com/CesiumGS/cesium-unreal/pull/882)improve the look of tile loading and reduce the "pop-in" effect. The feature is now available in the plugin, but let's discuss additional ways to improve the feature.

1. Tile appearance latency. It seems like the current solution can take longer to reach full detail because successive LODs must wait for the prior tile to finish fading in before the next LOD begins, which will always take the amount of time specified by the `LOD transition length` parameter. Some possible ideas to improve this from the PR discussion:

   - Allowing multiple tile levels to fade at once. This apparently works quite well but causes draw call spikes, especially in dense city scenes.
   - A more dynamic transition speed so that transitions are quicker when more tiles are available, or the tile is larger, or something.
   - Abort a transition midway and change the fade-in target if a higher-detail target tile is available.

2. Simultaneous in/out tile fades. Explained more in depth [here](https://github.com/CesiumGS/cesium-unreal/pull/882#discussion_r960352644). Essentially, since the dither effect is screen-space, perhaps we can use the dither opacity mask for the tile fading out as the the inverted opacity mask for the tile fading in. Which may solve the tile clipping/depth fighting effect without causing holes, and halve the time that each transition takes. This idea would also help with the above point, but seems valuable enough that we should consider implementing it regardless.

**Comment by nithinp7** [comment]
The second idea here was implemented and merged, closing this - thanks @argallegos! (Reopen this if you find any further issues or suggestions for the current state of LOD transitions of course!)
