### ISSUE TITLE
CesiumGltfComponent (and primitive) should inherit its mobility from the tileset and its root component

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#970]
Currently Cesium for Unreal hard-codes `Gltf->SetMobility(EComponentMobility::Static);`. Usually that's what we want, but sometimes, in some applications, it's actually useful to move tilesets, and this makes it impossible. Instead, we should inherit the mobility of the Tileset's root component. That way the user can easily make a tileset movable by changing the property in one place.

This is needed for Project Anywhere XR, so would be good to do it soon.

CC @AlbanBERGERET-Epic (who reported this)

**Comment by gvindiol** [comment]
We've imported the ProjectAnywhereXR into our project awhile back, and at some point these messages started appearing after play-in-edtior.
![image](https://user-images.githubusercontent.com/44582391/190551543-0f011737-b9d8-45b8-ad4e-18c9d0b12197.png)
