### ISSUE TITLE
Support WMTS Servers

### ISSUE THREAD

**Issue by smqh007** [CesiumGS/cesium-unreal#971]

**Comment by LeoYohg** [comment]
Already supported WMTS? if no, When to Support? I really need it badly.

**Comment by kring** [comment]
No, it's not implemented yet. We would welcome a pull request from the community for this. Adding new types of raster overlays is a fairly straightforward contribution.

**Comment by hermygong1231** [comment]
hope to support WMTS soon!

**Comment by j9liu** [comment]
Closed by #1245
