### ISSUE TITLE
Error using the Unreal-Linux-From-Windows-Toolchain.cmake

### ISSUE THREAD

**Issue by KieranCoppins** [CesiumGS/cesium-unreal#985]
Hi there,

I am currently trying to build Linux binaries from the extern directory for this plugin for packaging my unreal project for Linux OS. After some research I discovered how to target this toolchain using cmake and ran the following command:
`cmake -B build -S . --toolchain "unreal-linux-from-windows-toolchain.cmake"` and `cmake . --toolchain "unreal-linux-from-windows-toolchain.cmake"` both yielded the following error:
```
-- Building for: Visual Studio 17 2022
-- The CXX compiler identification is MSVC 19.33.31630.0
-- The C compiler identification is MSVC 19.33.31630.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Kieran/Documents/iventis_unreal/Plugins/cesium-unreal/extern/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_0adec.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      x86_64-unknown-linux-gnu
    c1xx : fatal  error C1083: Cannot open source file: 'x86_64-unknown-linux-gnu': No such file or directory [C:\Users\Kieran\Documents\unreal\Plugins\cesium-unreal\extern\CMakeFiles\CMakeTmp\cmTC_0adec.vcxproj]
      testCXXCompiler.cxx
      cl /c /I\include /I\include\c++\v1 /W1 /WX- /diagnostics:column /O2 /D _MBCS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_0adec.dir\Debug\\" /Fd"cmTC_0adec.dir\Debug\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue  -nostdinc++ -target x86_64-unknown-linux-gnu "C:\Users\Kieran\Documents\unreal\Plugins\cesium-unreal\extern\CMakeFiles\CMakeTmp\testCXXCompiler.cxx"
    cl : command line  warning D9002: ignoring unknown option '-nostdinc++' [C:\Users\Kieran\Documents\unreal\Plugins\cesium-unreal\extern\CMakeFiles\CMakeTmp\cmTC_0adec.vcxproj]
    cl : command line  warning D9002: ignoring unknown option '-target' [C:\Users\Kieran\Documents\unreal\Plugins\cesium-unreal\extern\CMakeFiles\CMakeTmp\cmTC_0adec.vcxproj]
      Generating Code...





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)
```

Not sure what I'm doing wrong and can't find any documentation on this. I can confirm that building linux binaries on linux works and windows on windows but can't figure windows to linux.

**Comment by joseph-kaile** [comment]
Hello @KieranCoppins, I'd recommend using the compiler from this page: https://docs.unrealengine.com/4.26/en-US/SharingAndReleasing/Linux/GettingStarted/.

That is the compiler that is used in the CI: https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/.github/workflows/build.yml.

Hope this helps.

**Comment by kring** [comment]
@KieranCoppins I think the bit you're missing is `-G Ninja` on your initial cmake line. Otherwise CMake tries to build with Visual Studio, which won't work when the target is Linux. You'll need to have Ninja installed. 

You can take a look at the exact steps our CI system uses to build the plugin for Linux from a Windows system:
https://github.com/CesiumGS/cesium-unreal/blob/f398c75196961674a6291641a44539dd50b34e01/.github/workflows/build.yml#L67

If you're not modifying Cesium for Unreal, precompiled Linux binaries are included in the distributions on our Releases page: https://github.com/CesiumGS/cesium-unreal/releases

**Comment by albright999** [comment]
Also trying to get up and running on Linux.  I just downloaded CesiumForUnreal-500-v1.18.0-ue5.zip, but only see Mac and Win64 under "Binaries" directory?

> If you're not modifying Cesium for Unreal, precompiled Linux binaries are included in the distributions on our Releases page: https://github.com/CesiumGS/cesium-unreal/releases

**Comment by kring** [comment]
The `Binaries` directory is used for the Editor. We don't currently ship the binaries necessary for running Cesium for Unreal in the Editor on Linux. However, we do support running the Editor on Windows and cross-compiling the game for Linux, which is what I inferred you're doing from the fact that you're using `unreal-linux-from-windows-toolchain.cmake`. The binaries necessary for that scenario are found in `Intermediate\Build\Linux` in the distribution ZIP file.

**Comment by kring** [comment]
Sorry, just realized you're not the original author of this issue, @albright999. If you're trying to run in the Editor on Linux, you'll have to build Cesium for Unreal yourself rather than using the pre-built package.

**Comment by albright999** [comment]
Thanks @kring for the information, I didn't mean to hijack this thread.  I am working through the docs/forums on building Cesium for Unreal directly on Linux.

**Comment by kring** [comment]
We now ship complete Linux binaries for UE 5.2, and our build scripts show how it's done. So I don't think there's anything else actionable here.
