### ISSUE TITLE
Linux build for editor cannot find libUnrealEditor-SunPosition.so

### ISSUE THREAD

**Issue by albright999** [CesiumGS/cesium-unreal#988]
I've worked my way through the ue5-main documentation for building the plugin on Linux.  Unreal Engine(5.0.3) finds the Cesium plugin, but when I open cesium-unreal-samples sample project (or a new project and add the plugin), I am getting this in the terminal : 

`[2022.10.21-16.47.03:815][  0]LogCore: Warning: dlopen failed: libUnrealEditor-SunPosition.so: cannot open shared object file: No such file or directory
`
Doing a find, this files *does* exist :

```
find . -name "libUnrealEditor-SunPosition.so"
./Plugins/Runtime/SunPosition/Binaries/Linux/libUnrealEditor-SunPosition.so

```

Seems like a simple path problem, but not sure where to change it.

**Comment by kring** [comment]
After you build the plugin successfully, where do you put it? It's essential that it be in UE's `Engine/Plugins/Marketplace/CesiumForUnreal` directory, otherwise the relative paths to other modules that are embedded in the Cesium plugin will be incorrect.

**Comment by albright999** [comment]
Yes, I followed the instructions at : https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup-linux.md ,   I have confirmed that the plugin is place in  Engine/Plugins/Marketplace/CesiumForUnreal
I'm launching UnrealEditor form the terminal (in the Engine directory) using "./Binaries/Linux/UnrealEditor", then browsing to ~/dev/cesium-unreal-samples/CesiumForUnrealSamples.uproject.  It then says "This project was made with a different version of Unreal Engine"  (to be expected according to the docs), I choose Open a copy and it proceeds to start loading, I then get a dialog "Plugin 'CesiumForUnreal' failed to load because module 'CesiumRuntime' could not be loaded. . . .", in the UnrealEditor logging in the terminal it says "Warning: dlopen failed, LibUnrealEditor-SunPosition.so cannot open shared object file: No such file or directory"      I've tried launching launching UnrealEditor from different starting directories, but get the same each time.

**Comment by kring** [comment]
I've had some success fixing this problem by using patchelf to fix the incorrect RPATH that Unreal builds into our plugin. Like this:
https://github.com/CesiumGS/cesium-unreal/compare/linux-editor#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R368
(.github/workflows/build.yml line 368)

**Comment by kring** [comment]
We now include Linux binaries for UE 5.2. And you can see how our build scripts fix the RPATH problem, so this technique can probably be applied to UE 5.0 and 5.1 as well, if necessary:
https://github.com/CesiumGS/cesium-unreal/blob/v1.28.0/.github/workflows/build.yml#L593
I'm closing this because I don't think there's anything more actionable here.
