### ISSUE TITLE
Cesium splash screen attribution

### ISSUE THREAD

**Issue by brandondsantos** [CesiumGS/cesium-unreal#989]
Currently, Cesium has a watermark that appears in PIE. This takes up screen space. Instead of having a watermark, I think it should be changed to a splash screen that appears once an application is launched.

**Comment by brandondsantos** [comment]
Hi, any update on this? Is it even feasible?

I see it as a better alternative to the Cesium watermark taking up space on the HUD.

**Comment by kring** [comment]
That would be nice, but is not permitted by the terms of service of most data providers.

**Comment by kring** [comment]
I'm closing this because unfortunately I don't think it's allowed, in general.
