### ISSUE TITLE
Painting Quixel materials onto the landscape?

### ISSUE THREAD

**Issue by KnedlikMCPE** [CesiumGS/cesium-unreal#992]
Hello.
I would like to use Cesium to make a combat simulator, but the image quality is not good enough as you could imagine. Is there a way to overwrite the material at a certain point on the landscape? If not, is it planned?
Thanks in advance,
-Knedlik

**Comment by kring** [comment]
You can add Quixel assets on top of the landscape (https://cesium.com/learn/unreal/importing-quixel-assets/). Or you can specify a new Material Instance to use to render a tileset (https://cesium.com/learn/unreal/unreal-edit-materials/).
