### ISSUE TITLE
3DTileset can't set owner and set owner no see

### ISSUE THREAD

**Issue by leozejia** [CesiumGS/cesium-unreal#993]
The problem we met is when we set splitscreen by two pawns,we want to set the actors to specific pawn,so some actor can show in left viewport,and hide in the right viewport.But the Cesium3DTileset could't set owner to something

**Comment by kring** [comment]
This issue is fairly old, and I'm not quite sure what it's asking. If you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) and tell us in more detail what you're trying to accomplish.
