### ISSUE TITLE
RunUAT failure - Ubuntu 20.04 - UE5 - Size mismatch

### ISSUE THREAD

**Issue by wurrego** [CesiumGS/cesium-unreal#994]
I have done builds on fresh multiple machines now, including an AWS EC2 instance, and over the past few months I consistently get this failure on a fresh clone of the ue5-main branch. I really thought it was my environment first, but now having done in 3 separate environments/systems I am convinced there is an issue.

When running `./RunUAT.sh BuildPlugin -Plugin="$CESIUM_FOR_UNREAL_DIR/CesiumForUnreal.uplugin" -Package="$CESIUM_FOR_UNREAL_DIR/../packages/CesiumForUnreal" -CreateSubFolder -TargetPlatforms=Linux`

it fails on every file with a size mismatch error

`Size mismatch /home/ubuntu/develop/cesium-unreal/extern/cesium-native/extern/KTX-Software/other_lib/mac/Debug/SDL2.framework/Versions/A/Frameworks/hidapi.framework/hidapi = 23 to /home/ubuntu/develop/packages/CesiumForUnreal/HostProject/Plugins/CesiumForUnreal/extern/cesium-native/extern/KTX-Software/other_lib/mac/Debug/SDL2.framework/Versions/A/Frameworks/hidapi.framework/hidapi = 130
`

When i execute this on my corporate VPN, which is sometimes subject to packet loss and significant latency/jitter I even get a timestamps are not valid (because it took longer than 2 seconds for the copy to complete).

The resolution I have used is to modify the source code of the UE5 AutomationTool Utils so that it does not do any of these file copy verify checks. Primarily by commenting out these lines and making sure Retry is never set to True
https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Programs/AutomationTool/AutomationUtils/Utils.cs#L418-L438

[Link to Issue posted on UE5 Forum](https://forums.unrealengine.com/t/runuat-fails-on-building-cesium-for-unreal-ue-5-0-3-ubuntu-20-04-size-mismatch/688884)

**Comment by kring** [comment]
This is usually caused by git-lfs not being installed on your system.

**Comment by kring** [comment]
Actually, sorry, I'm misremembering. Your problem sounds the same as this one, though:
https://github.com/CesiumGS/cesium-unreal/issues/955#issuecomment-1238924646

**Comment by wurrego** [comment]
Thanks @kring that indeed is the issue. 
_"the Unreal Build Tool can't cope with the symlinks in the KTX-Software submodule."_

After running the cmake build of cesium for unreal. i deleted the cesium-unreal/extern folder and was able to build the plugin with UAT.
