### ISSUE TITLE
I had an error compiling the Unreal5.0.3 project using CesiumForUnity1.19.0

### ISSUE THREAD

**Issue by yiyeqingfeng** [CesiumGS/cesium-unreal#999]
UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winnt.h(611): warning C4005: "TEXT" : macro redefine

UATHelper: Package (Windows): D:\Program Files\UE_5 \Engine\Source\Runtime\Core\Public\HAL\Platform.h(1171): note: See "TEXT" for the previous definition

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10326): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10332): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10337): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10341): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10348): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10358): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\ Winioct. h(10362): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10367): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10374): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10377): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10380): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10385): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10388): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10588): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(10612): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(14093): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(15406): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(15525): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(15675): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(15688): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winioctl.h(15916): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"

UATHelper: Package (Windows): E:\Cesium_Unreal_Proj\CesiumTest\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26):  error C2059: Syntax error: "constant"

UATHelper: Package (Windows): E:\Cesium_Unreal_Proj\CesiumTest\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(26):  error C2238: Unexpected flag located at ";" before

UATHelper: Package (Windows): E:\Cesium_Unreal_Proj\CesiumTest\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(92):  error C2589: "Constant" : ":" illegal flag to the right

UATHelper: Package (Windows): E:\Cesium_Unreal_Proj\CesiumTest\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf\Material.h(92):  error C2062: Unexpected type "unknown-type"

UATHelper: Package (Windows): E:\Cesium_Unreal_Proj\CesiumTest\Plugins\CesiumForUnreal\Source\CesiumRuntime\Public\CesiumCreditSystem.h(5):  Fatal error C1083: cannot open include file: "Components/WidgetComponent. H" : No to the file or directory

UATHelper: packaging (Windows) : [17/20] the Compile CesiumGameInstance. Gen. CPP

UATHelper: Packaging (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winnt.h(611): warning C4005: "TEXT" : macro redefine

UATHelper: Pack (Win

**Comment by kring** [comment]
Do you get errors like this with the [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) project as well? Or only in your own project? I don't think I've seen errors like that before.

**Comment by YuchebHu** [comment]
Hi @kring，I reproduce the errors above. 

Environment：
OS: Windows10 Pro 21H2 19044.2728
Compiler: Visual Studio 2019 14.29.30136
CesiumForUnreal version: 1.23.0-release

The recurrent steps are below:
- Create a blank c++ unreal project (eg: Named CesiumUpdate)
- Put the CesiumForUnreal into directory "CesiumUpdate/Plugins" and enable the CesiumForUnreal Plugins in CesiumUpdate.uproject
- Open CesiumUpate.build.cs file and add CesiumRuntime module to PrivateDependencyModuleNames 
  ```
  PrivateDependencyModuleNames.AddRange(new string[] { "CesiumRuntime" });
  CppStandard = CppStandardVersion.Cpp17;
  ```
- Edit CesiumUpdateGameModeBase.h like that
  ```
  #pragma once
  
  #include "CoreMinimal.h"
  #include "GameFramework/GameModeBase.h"
  
  #include "Cesium3DTileset.h"
  
  #include "CesiumUpdateGameModeBase.generated.h"
  
  /**
   * 
   */
  UCLASS()
  class CESIUMUPDATE_API ACesiumUpdateGameModeBase : public AGameModeBase
  {
	  GENERATED_BODY()
  
  public:
	  ACesium3DTileset* CreateTileset() const
	  {
		  return nullptr;
	  }
  };
  ```
- Complie the CesiumTest as Shipping mode

Then you find the error message in the output windows
```
1>Building CesiumUpdate...
1>Using Visual Studio 2019 14.29.30136 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 14 actions with 8 processes...
1>  [1/14] Default.rc2
1>  [2/14] PCH.CesiumRuntime.cpp
1>  [3/14] Module.CesiumRuntime.gen.3_of_4.cpp
1>  [4/14] Module.CesiumRuntime.gen.2_of_4.cpp
1>  [5/14] Module.CesiumRuntime.gen.4_of_4.cpp
1>  [6/14] Module.CesiumRuntime.gen.1_of_4.cpp
1>  [7/14] SharedPCH.Engine.ShadowErrors.Cpp17.cpp
1>  [8/14] CesiumUpdate.init.gen.cpp
1>  [9/14] CesiumUpdate.cpp
1>  [10/14] CesiumUpdateGameModeBase.cpp
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(603): warning C4005: "TEXT" : macro redefine
1>  D:\Unreal Engine\UE_4.27\Engine\Source\Runtime\Core\Public\HAL/Platform.h(1085): note: See "TEXT" for the previous definition
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10229): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10235): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10240): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10244): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10251): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10261): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10265): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10270): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10277): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10280): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10283): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10288): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10291): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10486): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10510): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(13950): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15111): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15128): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15147): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15266): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15416): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15429): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15657): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(27): error C2059: Syntax error: "constant"
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(27): error C2238: Unexpected flag located at ";" before
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(93): error C2589: "Constant" : ":" illegal flag to the right
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(93): error C2062: Unexpected type "unknown-type"
1>  [11/14] CesiumUpdateGameModeBase.gen.cpp
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(603): warning C4005: "TEXT" : macro redefine
1>  D:\Unreal Engine\UE_4.27\Engine\Source\Runtime\Core\Public\HAL/Platform.h(1085): note: See "TEXT" for the previous definition
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10229): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10235): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10240): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10244): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10251): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10261): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10265): error C4668: Did not define "_WIN32_WINNT_WIN10_TH2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10270): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10277): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10280): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10283): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10288): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10291): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10486): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(10510): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(13950): error C4668: Did not define "_WIN32_WINNT_WIN10_RS5" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15111): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15128): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15147): error C4668: Did not define "_WIN32_WINNT_WIN10_RS2" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15266): error C4668: Did not define "_WIN32_WINNT_WIN10_RS3" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15416): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15429): error C4668: Did not define "_WIN32_WINNT_WIN10_RS4" as a preprocessor macro, replace "#if/#elif" with "0"
1>C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winioctl.h(15657): error C4668: Did not define "_WIN32_WINNT_WIN10_RS1" as a preprocessor macro, replace "#if/#elif" with "0"
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(27): error C2059: Syntax error: "constant"
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(27): error C2238: Unexpected flag located at ";" before
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(93): error C2589: "Constant" : ":" illegal flag to the right
1>E:\UE5 Workspace\CesiumUpdate\Plugins\CesiumForUnreal\Source\ThirdParty\include\CesiumGltf/Material.h(93): error C2062: Unexpected type "unknown-type"
```

**Comment by kring** [comment]
You probably need to enable exceptions. See here:
https://community.cesium.com/t/unable-to-package-ue5-0-3-project-with-cesium-v1-19-0/21162/19

**Comment by YuchebHu** [comment]
It looks good! Thank you for your help!

**Comment by YuchebHu** [comment]
I have no problem. I think you can close this issue. Thank you!

**Comment by newpeople123** [comment]
This problem still exists in the latest version and cannot be resolved using the solution you provided earlier.
